"""Public interface for freeCAM."""

from .pi_cam import (
    CASES,
    CAMBoundaryProvider,
    CESMOnlineBoundaryProvider,
    CaseConfig,
    CaseRegistry,
    Driver,
    FreeCAM,
    HeldSurfaceModel,
    OnlineBoundaryContext,
    OnlineBoundaryFields,
    OnlineBoundaryProvider,
    Physics,
    Property,
    ProcessSpec,
    PICAMAction,
    PICAMActionTrace,
    PICAMCase,
    PICAMCaseStepPlot,
    PICAMConfig,
    PICAMNotebookError,
    PICAMNotebookSession,
    PICAMOutputView,
    PICAMProfilePlot,
    PICAMStateView,
    PICAMStepGridPlot,
    PICAMStepPlot,
    PICAMStepPlan,
    PICAMWorkflowAction,
    PICAMWorkflowView,
    PythonStateView,
    RunHandle,
    RunProgress,
    RunResult,
    Variable,
    WorkflowFactory,
    WorkflowPreview,
    WorkflowPreviewAction,
    WorkflowTemplate,
    plot_steps,
    process,
    prepare_cesm_online_run,
)

__all__ = [
    "CASES",
    "HookCallback",
    "NativeModel",
    "CAMBoundaryProvider",
    "CESMOnlineBoundaryProvider",
    "CaseConfig",
    "CaseRegistry",
    "Driver",
    "FreeCAM",
    "HeldSurfaceModel",
    "OnlineBoundaryContext",
    "OnlineBoundaryFields",
    "OnlineBoundaryProvider",
    "Physics",
    "Property",
    "ProcessSpec",
    "RunHandle",
    "RunProgress",
    "RunResult",
    "PICAMAction",
    "PICAMActionTrace",
    "PICAMCase",
    "PICAMCaseStepPlot",
    "PICAMConfig",
    "PICAMNotebookError",
    "PICAMNotebookSession",
    "PICAMOutputView",
    "PICAMProfilePlot",
    "PICAMStateView",
    "PICAMStepGridPlot",
    "PICAMStepPlot",
    "PICAMStepPlan",
    "PICAMWorkflowAction",
    "PICAMWorkflowView",
    "Variable",
    "WorkflowFactory",
    "WorkflowPreview",
    "WorkflowPreviewAction",
    "WorkflowTemplate",
    "plot_steps",
    "process",
    "prepare_cesm_online_run",
    "PythonStateView",
]

from . import physics  # noqa: E402  (single-column physics functions)
from .physics.native_model import HookCallback, NativeModel  # noqa: E402  (what may stand at a kernel's hook)

__version__ = "0.19.0"
