! gw_tend (gw_drag.F90:897-1360) hoisted for the
! gwd segment runner: its locals as module state, its body in pieces the
! runner calls in the source's order, its dummies bound by the caller.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/gravity_wave_drag.yaml.  Do not edit by hand; edit the spec.
module pycam_gwd_driver
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_loc, c_null_ptr, c_f_pointer
  use shr_kind_mod, only: r8 => shr_kind_r8
  use shr_log_mod, only: errMsg => shr_log_errMsg
  use shr_assert_mod, only: shr_assert
  use ppgrid, only: pcols, pver
  use constituents, only: pcnst
  use physics_types, only: physics_state, physics_ptend, physics_ptend_init
  use spmd_utils, only: masterproc
  use cam_history, only: outfld
  use cam_logfile, only: iulog
  use cam_abortutils, only: endrun
  use ref_pres, only: do_molec_diff, ntop_molec, nbot_molec
  use physconst, only: cpair
  use phys_control, only: use_gw_oro, use_gw_front, use_gw_front_igw, use_gw_convect_dp, use_gw_convect_sh
  use gw_common, only: GWBand
  use gw_convect, only: BeresSourceDesc
  use gw_front, only: CMSourceDesc
  use physics_buffer, only: physics_buffer_desc, pbuf_get_field
  use camsrfexch, only: cam_in_t
  use physconst, only: cpairv, pi
  use coords_1d, only: Coords1D
  use gw_common, only: gw_prof, gw_drag_prof, calc_taucd, momentum_flux, momentum_fixer, energy_change, energy_fixer, coriolis_speed, adjust_inertial
  use gw_oro, only: gw_oro_src
  use gw_front, only: gw_cm_src
  use gw_convect, only: gw_beres_src
  use gw_drag, only: band_oro, band_mid, band_long, effgw_oro, effgw_cm, effgw_cm_igw, effgw_beres_dp, effgw_beres_sh, gw_polar_taper, beres_dp_desc, beres_sh_desc, cm_desc, cm_igw_desc, kvt_idx, ttend_dp_idx, ttend_sh_idx, frontgf_idx, frontga_idx, gw_spec_outflds
  implicit none
  private
  public :: driver_piece_1, driver_piece_2, driver_piece_3, driver_piece_4, gw_drag_prof_frame, gw_drag_prof_original, driver_bind

  integer(c_int64_t), parameter :: zero_shape(1) = (/ 0_c_int64_t /)

  ! the routine's dummies, bound by the caller
  type(physics_state), pointer, save, public :: state => null()
  real(r8), pointer, save, public :: sgh(:) => null()
  type(physics_buffer_desc), pointer, save, public :: pbuf(:) => null()
  real(r8), save, public :: dt
  type(physics_ptend), pointer, save, public :: ptend => null()
  type(cam_in_t), pointer, save, public :: cam_in => null()
  real(r8), pointer, save, public :: flx_heat(:) => null()

  ! the routine's locals, held for the chunk in flight
  real(r8), allocatable, save, target, public :: c(:,:)
  real(r8), allocatable, save, target, public :: de(:)
  real(r8), allocatable, save, target, public :: dse(:,:)
  real(r8), allocatable, save, target, public :: dttdf(:,:)
  real(r8), allocatable, save, target, public :: dttke(:,:)
  real(r8), allocatable, save, target, public :: effgw(:)
  real(r8), allocatable, save, target, public :: egwdffi(:,:)
  real(r8), allocatable, save, target, public :: egwdffi_tot(:,:)
  real(r8), pointer, save, public :: frontga(:,:) => null()
  real(r8), pointer, save, public :: frontgf(:,:) => null()
  real(r8), allocatable, save, target, public :: gwut(:,:,:)
  real(r8), allocatable, save, target, public :: hdepth(:)
  integer, save, target, public :: k
  real(r8), pointer, save, public :: kvt_in(:,:) => null()
  real(r8), allocatable, save, target, public :: kvtt(:,:)
  integer, save, target, public :: lchnk
  logical, save, target, public :: lq(pcnst)
  integer, save, target, public :: m
  real(r8), allocatable, save, target, public :: maxq0(:)
  integer, save, target, public :: ncol
  real(r8), allocatable, save, target, public :: ni(:,:)
  real(r8), allocatable, save, target, public :: nm(:,:)
  type(Coords1D), save, target, public :: p
  real(r8), allocatable, save, target, public :: piln(:,:)
  real(r8), allocatable, save, target, public :: q(:,:,:)
  real(r8), allocatable, save, target, public :: qtgw(:,:,:)
  real(r8), allocatable, save, target, public :: rhoi(:,:)
  real(r8), allocatable, save, target, public :: ro_adjust(:,:,:)
  real(r8), allocatable, save, target, public :: sgh_scaled(:)
  integer, allocatable, save, target, public :: src_level(:)
  real(r8), allocatable, save, target, public :: t(:,:)
  real(r8), allocatable, save, target, public :: tau(:,:,:)
  real(r8), allocatable, save, target, public :: tau0x(:)
  real(r8), allocatable, save, target, public :: tau0y(:)
  real(r8), allocatable, save, target, public :: taucd(:,:,:)
  integer, allocatable, save, target, public :: tend_level(:)
  real(r8), pointer, save, public :: ttend_dp(:,:) => null()
  real(r8), pointer, save, public :: ttend_sh(:,:) => null()
  real(r8), allocatable, save, target, public :: ttgw(:,:)
  real(r8), allocatable, save, target, public :: u(:,:)
  real(r8), allocatable, save, target, public :: u_coriolis(:)
  real(r8), allocatable, save, target, public :: ubi(:,:)
  real(r8), allocatable, save, target, public :: ubm(:,:)
  real(r8), allocatable, save, target, public :: um_flux(:)
  real(r8), allocatable, save, target, public :: utgw(:,:)
  real(r8), allocatable, save, target, public :: v(:,:)
  real(r8), allocatable, save, target, public :: vm_flux(:)
  real(r8), allocatable, save, target, public :: vtgw(:,:)
  real(r8), allocatable, save, target, public :: xv(:)
  real(r8), allocatable, save, target, public :: yv(:)
  real(r8), allocatable, save, target, public :: zm(:,:)

  ! gw_drag.F90:127-130: the module's own declaration, verbatim
    character(len=1), parameter :: cm_pf = " "
    character(len=1), parameter :: cm_igw_pf = "I"
    character(len=1), parameter :: beres_dp_pf = "B"
    character(len=1), parameter :: beres_sh_pf = "S"

contains

  subroutine driver_bind(a_state, a_sgh, a_pbuf, a_dt, a_ptend, a_cam_in, a_flx_heat)
    ! the dummies of gw_tend, as the caller's statement passes them
    type(physics_state), target, intent(inout) :: a_state
    real(r8), target, intent(inout) :: a_sgh(:)
    type(physics_buffer_desc), target, intent(inout) :: a_pbuf(:)
    real(r8), intent(in) :: a_dt
    type(physics_ptend), target, intent(inout) :: a_ptend
    type(cam_in_t), target, intent(inout) :: a_cam_in
    real(r8), target, intent(inout) :: a_flx_heat(:)
    state => a_state
    sgh => a_sgh
    pbuf => a_pbuf
    dt = a_dt
    ptend => a_ptend
    cam_in => a_cam_in
    flx_heat => a_flx_heat
    if (allocated(de)) then
      if (any(shape(de) /= (/ state%ncol /))) deallocate(de)
    end if
    if (.not. allocated(de)) allocate(de(state%ncol))
    if (allocated(dse)) then
      if (any(shape(dse) /= (/ state%ncol, pver /))) deallocate(dse)
    end if
    if (.not. allocated(dse)) allocate(dse(state%ncol,pver))
    if (allocated(dttdf)) then
      if (any(shape(dttdf) /= (/ state%ncol, pver /))) deallocate(dttdf)
    end if
    if (.not. allocated(dttdf)) allocate(dttdf(state%ncol,pver))
    if (allocated(dttke)) then
      if (any(shape(dttke) /= (/ state%ncol, pver /))) deallocate(dttke)
    end if
    if (.not. allocated(dttke)) allocate(dttke(state%ncol,pver))
    if (allocated(effgw)) then
      if (any(shape(effgw) /= (/ state%ncol /))) deallocate(effgw)
    end if
    if (.not. allocated(effgw)) allocate(effgw(state%ncol))
    if (allocated(egwdffi)) then
      if (any(shape(egwdffi) /= (/ state%ncol, pver+1 /))) deallocate(egwdffi)
    end if
    if (.not. allocated(egwdffi)) allocate(egwdffi(state%ncol,pver+1))
    if (allocated(egwdffi_tot)) then
      if (any(shape(egwdffi_tot) /= (/ state%ncol, pver+1 /))) deallocate(egwdffi_tot)
    end if
    if (.not. allocated(egwdffi_tot)) allocate(egwdffi_tot(state%ncol,pver+1))
    if (allocated(hdepth)) then
      if (any(shape(hdepth) /= (/ state%ncol /))) deallocate(hdepth)
    end if
    if (.not. allocated(hdepth)) allocate(hdepth(state%ncol))
    if (allocated(kvtt)) then
      if (any(shape(kvtt) /= (/ state%ncol, pver+1 /))) deallocate(kvtt)
    end if
    if (.not. allocated(kvtt)) allocate(kvtt(state%ncol,pver+1))
    if (allocated(maxq0)) then
      if (any(shape(maxq0) /= (/ state%ncol /))) deallocate(maxq0)
    end if
    if (.not. allocated(maxq0)) allocate(maxq0(state%ncol))
    if (allocated(ni)) then
      if (any(shape(ni) /= (/ state%ncol, pver+1 /))) deallocate(ni)
    end if
    if (.not. allocated(ni)) allocate(ni(state%ncol,pver+1))
    if (allocated(nm)) then
      if (any(shape(nm) /= (/ state%ncol, pver /))) deallocate(nm)
    end if
    if (.not. allocated(nm)) allocate(nm(state%ncol,pver))
    if (allocated(piln)) then
      if (any(shape(piln) /= (/ state%ncol, pver+1 /))) deallocate(piln)
    end if
    if (.not. allocated(piln)) allocate(piln(state%ncol,pver+1))
    if (allocated(q)) then
      if (any(shape(q) /= (/ state%ncol, pver, pcnst /))) deallocate(q)
    end if
    if (.not. allocated(q)) allocate(q(state%ncol,pver,pcnst))
    if (allocated(qtgw)) then
      if (any(shape(qtgw) /= (/ state%ncol, pver, pcnst /))) deallocate(qtgw)
    end if
    if (.not. allocated(qtgw)) allocate(qtgw(state%ncol,pver,pcnst))
    if (allocated(rhoi)) then
      if (any(shape(rhoi) /= (/ state%ncol, pver+1 /))) deallocate(rhoi)
    end if
    if (.not. allocated(rhoi)) allocate(rhoi(state%ncol,pver+1))
    if (allocated(sgh_scaled)) then
      if (any(shape(sgh_scaled) /= (/ state%ncol /))) deallocate(sgh_scaled)
    end if
    if (.not. allocated(sgh_scaled)) allocate(sgh_scaled(state%ncol))
    if (allocated(src_level)) then
      if (any(shape(src_level) /= (/ state%ncol /))) deallocate(src_level)
    end if
    if (.not. allocated(src_level)) allocate(src_level(state%ncol))
    if (allocated(t)) then
      if (any(shape(t) /= (/ state%ncol, pver /))) deallocate(t)
    end if
    if (.not. allocated(t)) allocate(t(state%ncol,pver))
    if (allocated(tau0x)) then
      if (any(shape(tau0x) /= (/ state%ncol /))) deallocate(tau0x)
    end if
    if (.not. allocated(tau0x)) allocate(tau0x(state%ncol))
    if (allocated(tau0y)) then
      if (any(shape(tau0y) /= (/ state%ncol /))) deallocate(tau0y)
    end if
    if (.not. allocated(tau0y)) allocate(tau0y(state%ncol))
    if (allocated(taucd)) then
      if (any(shape(taucd) /= (/ state%ncol, pver+1, 4 /))) deallocate(taucd)
    end if
    if (.not. allocated(taucd)) allocate(taucd(state%ncol,pver+1,4))
    if (allocated(tend_level)) then
      if (any(shape(tend_level) /= (/ state%ncol /))) deallocate(tend_level)
    end if
    if (.not. allocated(tend_level)) allocate(tend_level(state%ncol))
    if (allocated(ttgw)) then
      if (any(shape(ttgw) /= (/ state%ncol, pver /))) deallocate(ttgw)
    end if
    if (.not. allocated(ttgw)) allocate(ttgw(state%ncol,pver))
    if (allocated(u)) then
      if (any(shape(u) /= (/ state%ncol, pver /))) deallocate(u)
    end if
    if (.not. allocated(u)) allocate(u(state%ncol,pver))
    if (allocated(u_coriolis)) then
      if (any(shape(u_coriolis) /= (/ state%ncol /))) deallocate(u_coriolis)
    end if
    if (.not. allocated(u_coriolis)) allocate(u_coriolis(state%ncol))
    if (allocated(ubi)) then
      if (any(shape(ubi) /= (/ state%ncol, pver+1 /))) deallocate(ubi)
    end if
    if (.not. allocated(ubi)) allocate(ubi(state%ncol,pver+1))
    if (allocated(ubm)) then
      if (any(shape(ubm) /= (/ state%ncol, pver /))) deallocate(ubm)
    end if
    if (.not. allocated(ubm)) allocate(ubm(state%ncol,pver))
    if (allocated(um_flux)) then
      if (any(shape(um_flux) /= (/ state%ncol /))) deallocate(um_flux)
    end if
    if (.not. allocated(um_flux)) allocate(um_flux(state%ncol))
    if (allocated(utgw)) then
      if (any(shape(utgw) /= (/ state%ncol, pver /))) deallocate(utgw)
    end if
    if (.not. allocated(utgw)) allocate(utgw(state%ncol,pver))
    if (allocated(v)) then
      if (any(shape(v) /= (/ state%ncol, pver /))) deallocate(v)
    end if
    if (.not. allocated(v)) allocate(v(state%ncol,pver))
    if (allocated(vm_flux)) then
      if (any(shape(vm_flux) /= (/ state%ncol /))) deallocate(vm_flux)
    end if
    if (.not. allocated(vm_flux)) allocate(vm_flux(state%ncol))
    if (allocated(vtgw)) then
      if (any(shape(vtgw) /= (/ state%ncol, pver /))) deallocate(vtgw)
    end if
    if (.not. allocated(vtgw)) allocate(vtgw(state%ncol,pver))
    if (allocated(xv)) then
      if (any(shape(xv) /= (/ state%ncol /))) deallocate(xv)
    end if
    if (.not. allocated(xv)) allocate(xv(state%ncol))
    if (allocated(yv)) then
      if (any(shape(yv) /= (/ state%ncol /))) deallocate(yv)
    end if
    if (.not. allocated(yv)) allocate(yv(state%ncol))
    if (allocated(zm)) then
      if (any(shape(zm) /= (/ state%ncol, pver /))) deallocate(zm)
    end if
    if (.not. allocated(zm)) allocate(zm(state%ncol,pver))
  end subroutine driver_bind

  subroutine driver_piece_1()
    ! gw_drag.F90:897-1272, verbatim

      lchnk = state%lchnk
      ncol  = state%ncol

      p = Coords1D(state%pint(:ncol,:))

      dse = state%s(:ncol,:)
      t = state%t(:ncol,:)
      u = state%u(:ncol,:)
      v = state%v(:ncol,:)
      q = state%q(:ncol,:,:)
      piln = state%lnpint(:ncol,:)
      zm = state%zm(:ncol,:)

      lq = .true.
      call physics_ptend_init(ptend, state%psetcols, "Gravity wave drag", &
           ls=.true., lu=.true., lv=.true., lq=lq)

      ! Profiles of background state variables
      call gw_prof(ncol, p, cpair, t, rhoi, nm, ni)

      if (do_molec_diff) then
         !--------------------------------------------------------
         ! Initialize and calculate local molecular diffusivity
         !--------------------------------------------------------

         call pbuf_get_field(pbuf, kvt_idx, kvt_in)  ! kvt_in(1:pcols,1:pver+1)

         ! Set kvtt from pbuf field; kvtt still needs a factor of 1/cpairv.
         kvtt = kvt_in(:ncol,:)

         ! Use linear extrapolation of cpairv to top interface.
         kvtt(:,ntop_molec) = kvtt(:,ntop_molec) / &
              (1.5_r8*cpairv(:ncol,ntop_molec,lchnk) - &
              0.5_r8*cpairv(:ncol,ntop_molec+1,lchnk))

         ! Interpolate cpairv to other interfaces.
         do k = ntop_molec+1, nbot_molec
            kvtt(:,k) = kvtt(:,k) / &
                 (cpairv(:ncol,k+1,lchnk)+cpairv(:ncol,k,lchnk)) * 2._r8
         enddo

      else

         kvtt = 0._r8

      end if

      if (use_gw_front_igw) then
         u_coriolis = coriolis_speed(band_long, state%lat(:ncol))
      end if

      ! Totals that accumulate over different sources.
      egwdffi_tot = 0._r8
      flx_heat = 0._r8

      if (use_gw_convect_dp) then
         !------------------------------------------------------------------
         ! Convective gravity waves (Beres scheme, deep).
         !------------------------------------------------------------------

         ! Allocate wavenumber fields.
         allocate(tau(ncol,-band_mid%ngwv:band_mid%ngwv,pver+1))
         allocate(gwut(ncol,pver,-band_mid%ngwv:band_mid%ngwv))
         allocate(c(ncol,-band_mid%ngwv:band_mid%ngwv))

         ! Set up heating
         call pbuf_get_field(pbuf, ttend_dp_idx, ttend_dp)

         ! Efficiency of gravity wave momentum transfer.
         ! This is really only to remove the pole points.
         where (pi/2._r8 - abs(state%lat(:ncol)) >= 4*epsilon(1._r8))
            effgw = effgw_beres_dp
         elsewhere
            effgw = 0._r8
         end where

         ! Determine wave sources for Beres deep scheme
         call gw_beres_src(ncol, band_mid, beres_dp_desc, &
              u, v, ttend_dp(:ncol,:), zm, src_level, tend_level, tau, &
              ubm, ubi, xv, yv, c, hdepth, maxq0)

         ! Solve for the drag profile with Beres source spectrum.
         call gw_drag_prof(ncol, band_mid, p, src_level, tend_level, dt, &
              t,    &
              piln, rhoi,       nm,   ni, ubm,  ubi,  xv,    yv,   &
              effgw,   c,       kvtt, q,  dse,  tau,  utgw,  vtgw, &
              ttgw, qtgw, egwdffi,  gwut, dttdf, dttke)

         ! Project stress into directional components.
         taucd = calc_taucd(ncol, band_mid%ngwv, tend_level, tau, c, xv, yv, ubi)

         !  add the diffusion coefficients
         do k = 1, pver+1
            egwdffi_tot(:,k) = egwdffi_tot(:,k) + egwdffi(:,k)
         end do

         ! Store constituents tendencies
         do m=1, pcnst
            do k = 1, pver
               ptend%q(:ncol,k,m) = ptend%q(:ncol,k,m) + qtgw(:,k,m)
            end do
         end do

         ! Find momentum flux, and use it to fix the wind tendencies below
         ! the gravity wave region.
         call momentum_flux(tend_level, taucd, um_flux, vm_flux)
         call momentum_fixer(tend_level, p, um_flux, vm_flux, utgw, vtgw)

         ! Add the momentum tendencies to the output tendency arrays.
         do k = 1, pver
            ptend%u(:ncol,k) = ptend%u(:ncol,k) + utgw(:,k)
            ptend%v(:ncol,k) = ptend%v(:ncol,k) + vtgw(:,k)
         end do

         ! Find energy change in the current state, and use fixer to apply
         ! the difference in lower levels.
         call energy_change(dt, p, u, v, ptend%u(:ncol,:), &
              ptend%v(:ncol,:), ptend%s(:ncol,:)+ttgw, de)
         call energy_fixer(tend_level, p, de-flx_heat(:ncol), ttgw)

         do k = 1, pver
            ptend%s(:ncol,k) = ptend%s(:ncol,k) + ttgw(:,k)
         end do

         ! Change ttgw to a temperature tendency before outputing it.
         ttgw = ttgw / cpair
         call gw_spec_outflds(beres_dp_pf, lchnk, ncol, band_mid, c, u, v, &
              xv, yv, gwut, dttdf, dttke, tau(:,:,2:), utgw, vtgw, ttgw, &
              taucd)

         ! Diagnostic outputs (convert hdepth to km).
         call outfld('NETDT', ttend_dp, pcols, lchnk)
         call outfld('HDEPTH', hdepth/1000._r8, ncol, lchnk)
         call outfld('MAXQ0', maxq0, ncol, lchnk)

         deallocate(tau, gwut, c)

      end if

      if (use_gw_convect_sh) then
         !------------------------------------------------------------------
         ! Convective gravity waves (Beres scheme, shallow).
         !------------------------------------------------------------------

         ! Allocate wavenumber fields.
         allocate(tau(ncol,-band_mid%ngwv:band_mid%ngwv,pver+1))
         allocate(gwut(ncol,pver,-band_mid%ngwv:band_mid%ngwv))
         allocate(c(ncol,-band_mid%ngwv:band_mid%ngwv))

         ! Set up heating
         call pbuf_get_field(pbuf, ttend_sh_idx, ttend_sh)

         ! Efficiency of gravity wave momentum transfer.
         ! This is really only to remove the pole points.
         where (pi/2._r8 - abs(state%lat(:ncol)) >= 4*epsilon(1._r8))
            effgw = effgw_beres_sh
         elsewhere
            effgw = 0._r8
         end where

         ! Determine wave sources for Beres shallow scheme
         call gw_beres_src(ncol, band_mid, beres_sh_desc, &
              u, v, ttend_sh(:ncol,:), zm, src_level, tend_level, tau, &
              ubm, ubi, xv, yv, c, hdepth, maxq0)

         ! Solve for the drag profile with Beres source spectrum.
         call gw_drag_prof(ncol, band_mid, p, src_level, tend_level,  dt, &
              t,    &
              piln, rhoi,       nm,   ni, ubm,  ubi,  xv,    yv,   &
              effgw,   c,       kvtt, q,  dse,  tau,  utgw,  vtgw, &
              ttgw, qtgw, egwdffi,  gwut, dttdf, dttke)

         ! Project stress into directional components.
         taucd = calc_taucd(ncol, band_mid%ngwv, tend_level, tau, c, xv, yv, ubi)

         !  add the diffusion coefficients
         do k = 1, pver+1
            egwdffi_tot(:,k) = egwdffi_tot(:,k) + egwdffi(:,k)
         end do

         ! Store constituents tendencies
         do m=1, pcnst
            do k = 1, pver
               ptend%q(:ncol,k,m) = ptend%q(:ncol,k,m) + qtgw(:,k,m)
            end do
         end do

         ! Add the momentum tendencies to the output tendency arrays.
         ! Don't calculate fixers, since we are too close to the ground to
         ! spread momentum/energy differences across low layers.
         do k = 1, pver
            ptend%u(:ncol,k) = ptend%u(:ncol,k) + utgw(:,k)
            ptend%v(:ncol,k) = ptend%v(:ncol,k) + vtgw(:,k)
            ptend%s(:ncol,k) = ptend%s(:ncol,k) + ttgw(:,k)
         end do

         ! Calculate energy change for output to CAM's energy checker.
         ! This is sort of cheating; we don't have a good a priori idea of the
         ! energy coming from surface stress, so we just integrate what we and
         ! actually have so far and overwrite flx_heat with that.
         call energy_change(dt, p, u, v, ptend%u(:ncol,:), &
              ptend%v(:ncol,:), ptend%s(:ncol,:), de)
         flx_heat(:ncol) = de

         ! Change ttgw to a temperature tendency before outputing it.
         ttgw = ttgw / cpair
         call gw_spec_outflds(beres_sh_pf, lchnk, ncol, band_mid, c, u, v, &
              xv, yv, gwut, dttdf, dttke, tau(:,:,2:), utgw, vtgw, ttgw, &
              taucd)

         ! Diagnostic outputs (convert SHDEPTH to km).
         call outfld ('SNETDT', ttend_sh, pcols, lchnk)
         call outfld ('SHDEPTH', hdepth/1000._r8, ncol, lchnk)
         call outfld ('SMAXQ0', maxq0, ncol, lchnk)

         deallocate(tau, gwut, c)

      end if

      if (use_gw_front .or. use_gw_front_igw) then
         ! Get frontogenesis physics buffer fields set by dynamics.
         call pbuf_get_field(pbuf, frontgf_idx, frontgf)
         call pbuf_get_field(pbuf, frontga_idx, frontga)

         ! Output for diagnostics.
         call outfld ('FRONTGF', frontgf, pcols, lchnk)
         call outfld ('FRONTGFA', frontga, pcols, lchnk)
      end if

      if (use_gw_front) then
         !------------------------------------------------------------------
         ! Frontally generated gravity waves
         !------------------------------------------------------------------

         ! Allocate wavenumber fields.
         allocate(tau(ncol,-band_mid%ngwv:band_mid%ngwv,pver+1))
         allocate(gwut(ncol,pver,-band_mid%ngwv:band_mid%ngwv))
         allocate(c(ncol,-band_mid%ngwv:band_mid%ngwv))

         ! Efficiency of gravity wave momentum transfer.
         effgw = effgw_cm
         ! Frontogenesis is too high at the poles (at least for the FV
         ! dycore), so introduce a polar taper.
         if (gw_polar_taper) effgw = effgw * cos(state%lat(:ncol))

         ! Determine the wave source for C&M background spectrum
         call gw_cm_src(ncol, band_mid, cm_desc, u, v, frontgf(:ncol,:), &
              src_level, tend_level, tau, ubm, ubi, xv, yv, c)

         ! Solve for the drag profile with C&M source spectrum.
         call gw_drag_prof(ncol, band_mid, p, src_level, tend_level,  dt, &
              t,    &
              piln, rhoi,       nm,   ni, ubm,  ubi,  xv,    yv,   &
              effgw,   c,       kvtt, q,  dse,  tau,  utgw,  vtgw, &
              ttgw, qtgw, egwdffi,  gwut, dttdf, dttke)

         ! Project stress into directional components.
         taucd = calc_taucd(ncol, band_mid%ngwv, tend_level, tau, c, xv, yv, ubi)

         !  add the diffusion coefficients
         do k = 1, pver+1
            egwdffi_tot(:,k) = egwdffi_tot(:,k) + egwdffi(:,k)
         end do

         !Add the constituent tendencies
         do m=1, pcnst
            do k = 1, pver
               ptend%q(:ncol,k,m) = ptend%q(:ncol,k,m) + qtgw(:,k,m)
            end do
         end do

         ! Find momentum flux, and use it to fix the wind tendencies below
         ! the gravity wave region.
         call momentum_flux(tend_level, taucd, um_flux, vm_flux)
         call momentum_fixer(tend_level, p, um_flux, vm_flux, utgw, vtgw)

         ! add the momentum tendencies to the output tendency arrays
         do k = 1, pver
            ptend%u(:ncol,k) = ptend%u(:ncol,k) + utgw(:,k)
            ptend%v(:ncol,k) = ptend%v(:ncol,k) + vtgw(:,k)
         end do

         ! Find energy change in the current state, and use fixer to apply
         ! the difference in lower levels.
         call energy_change(dt, p, u, v, ptend%u(:ncol,:), &
              ptend%v(:ncol,:), ptend%s(:ncol,:)+ttgw, de)
         call energy_fixer(tend_level, p, de-flx_heat(:ncol), ttgw)

         do k = 1, pver
            ptend%s(:ncol,k) = ptend%s(:ncol,k) + ttgw(:,k)
         end do

         ! Change ttgw to a temperature tendency before outputing it.
         ttgw = ttgw / cpair
         call gw_spec_outflds(cm_pf, lchnk, ncol, band_mid, c, u, v, &
              xv, yv, gwut, dttdf, dttke, tau(:,:,2:), utgw, vtgw, ttgw, &
              taucd)

         deallocate(tau, gwut, c)

      end if

      if (use_gw_front_igw) then
         !------------------------------------------------------------------
         ! Frontally generated inertial gravity waves
         !------------------------------------------------------------------

         ! Allocate wavenumber fields.
         allocate(tau(ncol,-band_long%ngwv:band_long%ngwv,pver+1))
         allocate(gwut(ncol,pver,-band_long%ngwv:band_long%ngwv))
         allocate(c(ncol,-band_long%ngwv:band_long%ngwv))
         allocate(ro_adjust(ncol,-band_long%ngwv:band_long%ngwv,pver+1))

         ! Efficiency of gravity wave momentum transfer.
         effgw = effgw_cm_igw

         ! Determine the wave source for C&M background spectrum
         call gw_cm_src(ncol, band_long, cm_igw_desc, u, v, frontgf(:ncol,:), &
              src_level, tend_level, tau, ubm, ubi, xv, yv, c)

         call adjust_inertial(band_long, tend_level, u_coriolis, c, ubi, &
              tau, ro_adjust)

         ! Solve for the drag profile with C&M source spectrum.
         call gw_drag_prof(ncol, band_long, p, src_level, tend_level,  dt, &
              t,    &
              piln, rhoi,       nm,   ni, ubm,  ubi,  xv,    yv,   &
              effgw,   c,       kvtt, q,  dse,  tau,  utgw,  vtgw, &
              ttgw, qtgw, egwdffi,  gwut, dttdf, dttke, ro_adjust=ro_adjust)

         ! Project stress into directional components.
         taucd = calc_taucd(ncol, band_long%ngwv, tend_level, tau, c, xv, yv, ubi)

         !  add the diffusion coefficients
         do k = 1, pver+1
            egwdffi_tot(:,k) = egwdffi_tot(:,k) + egwdffi(:,k)
         end do

         !Add the constituent tendencies
         do m=1, pcnst
            do k = 1, pver
               ptend%q(:ncol,k,m) = ptend%q(:ncol,k,m) + qtgw(:,k,m)
            end do
         end do

         ! Find momentum flux, and use it to fix the wind tendencies below
         ! the gravity wave region.
         call momentum_flux(tend_level, taucd, um_flux, vm_flux)
         call momentum_fixer(tend_level, p, um_flux, vm_flux, utgw, vtgw)

         ! add the momentum tendencies to the output tendency arrays
         do k = 1, pver
            ptend%u(:ncol,k) = ptend%u(:ncol,k) + utgw(:,k)
            ptend%v(:ncol,k) = ptend%v(:ncol,k) + vtgw(:,k)
         end do

         ! Find energy change in the current state, and use fixer to apply
         ! the difference in lower levels.
         call energy_change(dt, p, u, v, ptend%u(:ncol,:), &
              ptend%v(:ncol,:), ptend%s(:ncol,:)+ttgw, de)
         call energy_fixer(tend_level, p, de-flx_heat(:ncol), ttgw)

         do k = 1, pver
            ptend%s(:ncol,k) = ptend%s(:ncol,k) + ttgw(:,k)
         end do

         ! Change ttgw to a temperature tendency before outputing it.
         ttgw = ttgw / cpair
         call gw_spec_outflds(cm_igw_pf, lchnk, ncol, band_long, c, u, v, &
              xv, yv, gwut, dttdf, dttke, tau(:,:,2:), utgw, vtgw, ttgw, &
              taucd)

         deallocate(tau, gwut, c)

      end if


  end subroutine driver_piece_1

  subroutine driver_piece_2()
    ! gw_drag.F90:1274-1298, verbatim

         !---------------------------------------------------------------------
         ! Orographic stationary gravity waves
         !---------------------------------------------------------------------

         ! Allocate wavenumber fields.
         allocate(tau(ncol,band_oro%ngwv:band_oro%ngwv,pver+1))
         allocate(gwut(ncol,pver,band_oro%ngwv:band_oro%ngwv))
         allocate(c(ncol,band_oro%ngwv:band_oro%ngwv))

         ! Efficiency of gravity wave momentum transfer.
         ! Take into account that wave sources are only over land.
         where (cam_in%landfrac(:ncol) >= epsilon(1._r8))
            effgw = effgw_oro * cam_in%landfrac(:ncol)
            sgh_scaled = sgh(:ncol) / sqrt(cam_in%landfrac(:ncol))
         elsewhere
            effgw = 0._r8
            sgh_scaled = 0._r8
         end where

         ! Determine the orographic wave source
         call gw_oro_src(ncol, band_oro, p, &
              u, v, t, sgh_scaled, zm, nm, &
              src_level, tend_level, tau, ubm, ubi, xv, yv, c)

         ! Solve for the drag profile with orographic sources.

  end subroutine driver_piece_2

  subroutine driver_piece_3()
    ! gw_drag.F90:1304-1351, verbatim


         ! For orographic waves, don't bother with taucd, since there are no
         ! momentum conservation routines or directional diagnostics.

         !  add the diffusion coefficients
         do k = 1, pver+1
            egwdffi_tot(:,k) = egwdffi_tot(:,k) + egwdffi(:,k)
         end do

         ! Add the orographic tendencies to the spectrum tendencies.
         ! Don't calculate fixers, since we are too close to the ground to
         ! spread momentum/energy differences across low layers.
         do k = 1, pver
            ptend%u(:ncol,k) = ptend%u(:ncol,k) + utgw(:,k)
            ptend%v(:ncol,k) = ptend%v(:ncol,k) + vtgw(:,k)
            ptend%s(:ncol,k) = ptend%s(:ncol,k) + ttgw(:,k)
            ! Convert to temperature tendency for output.
            ttgw(:,k) = ttgw(:,k) / cpairv(:ncol, k, lchnk)
         end do

         ! Calculate energy change for output to CAM's energy checker.
         ! This is sort of cheating; we don't have a good a priori idea of the
         ! energy coming from surface stress, so we just integrate what we and
         ! actually have so far and overwrite flx_heat with that.
         call energy_change(dt, p, u, v, ptend%u(:ncol,:), &
              ptend%v(:ncol,:), ptend%s(:ncol,:), de)
         flx_heat(:ncol) = de

         do m = 1, pcnst
            do k = 1, pver
               ptend%q(:ncol,k,m) = ptend%q(:ncol,k,m) + qtgw(:,k,m)
            end do
         end do

         ! Write output fields to history file
         call outfld('UTGWORO', utgw,  ncol, lchnk)
         call outfld('VTGWORO', vtgw,  ncol, lchnk)
         call outfld('TTGWORO', ttgw,  ncol, lchnk)
         call outfld('TTGWSDFORO', dttdf / cpair,  ncol, lchnk)
         call outfld('TTGWSKEORO', dttke / cpair,  ncol, lchnk)
         tau0x = tau(:,0,pver+1) * xv
         tau0y = tau(:,0,pver+1) * yv
         call outfld('TAUGWX', tau0x, ncol, lchnk)
         call outfld('TAUGWY', tau0y, ncol, lchnk)
         call outfld('SGH   ',   sgh,pcols, lchnk)

         deallocate(tau, gwut, c)


  end subroutine driver_piece_3

  subroutine driver_piece_4()
    ! gw_drag.F90:1353-1360, verbatim


      ! Write totals to history file.
      call outfld ('EKGW', egwdffi_tot , ncol, lchnk)
      call outfld ('TTGW', ptend%s/cpairv(:,:,lchnk),  pcols, lchnk)

      ! Destroy objects.
      call p%finalize()


  end subroutine driver_piece_4

  subroutine gw_drag_prof_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
    ! the paused `call gw_drag_prof(ncol, band_oro, p, src_level, tend_level, dt, t, pil...` in the callee's argument order
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer(c_int), intent(out) :: ncol_out
    integer(c_int32_t), save, target :: sc_1
    integer(c_int32_t), save, target :: sc_2
    real(c_double), save, target :: sc_3
    real(c_double), save, target :: sc_4
    real(c_double), save, target :: sc_5
    ncol_out = int(ncol, c_int)
    sc_1 = int(ncol, c_int32_t)
    call put_slot(1, c_loc(sc_1), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_2 = int(band_oro%ngwv, c_int32_t)
    call put_slot(2, c_loc(sc_2), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_3 = real(band_oro%effkwv, c_double)
    call put_slot(3, c_loc(sc_3), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_4 = real(band_oro%kwv, c_double)
    call put_slot(4, c_loc(sc_4), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(5, c_loc(p%rdel), 2, (/ int(size(p%rdel,1), c_int64_t), int(size(p%rdel,2), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(6, c_loc(p%del), 2, (/ int(size(p%del,1), c_int64_t), int(size(p%del,2), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(7, c_loc(src_level(1)), 1, (/ int((ncol), c_int64_t) /), 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(8, c_loc(tend_level(1)), 1, (/ int((ncol), c_int64_t) /), 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_5 = real(dt, c_double)
    call put_slot(9, c_loc(sc_5), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(10, c_loc(t(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(11, c_loc(piln(1,1)), 2, (/ int((ncol), c_int64_t), int(pver+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(12, c_loc(rhoi(1,1)), 2, (/ int((ncol), c_int64_t), int(pver+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(13, c_loc(nm(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(14, c_loc(ni(1,1)), 2, (/ int((ncol), c_int64_t), int(pver+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(15, c_loc(ubm(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(16, c_loc(ubi(1,1)), 2, (/ int((ncol), c_int64_t), int(pver+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(17, c_loc(xv(1)), 1, (/ int((ncol), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(18, c_loc(yv(1)), 1, (/ int((ncol), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(19, c_loc(effgw(1)), 1, (/ int((ncol), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    if (allocated(c)) then
      call put_slot(20, c_loc(c(1,1)), 2, (/ int(size(c,1), c_int64_t), int(size(c,2), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(20, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(21, c_loc(kvtt(1,1)), 2, (/ int((ncol), c_int64_t), int(pver+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(22, c_loc(q(1,1,1)), 3, (/ int(size(q,1), c_int64_t), int(size(q,2), c_int64_t), int(size(q,3), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(23, c_loc(dse(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    if (allocated(tau)) then
      call put_slot(24, c_loc(tau(1,1,1)), 3, (/ int(size(tau,1), c_int64_t), int(size(tau,2), c_int64_t), int(size(tau,3), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(24, 3, 1, 2, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(25, c_loc(utgw(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(26, c_loc(vtgw(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(27, c_loc(ttgw(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(28, c_loc(qtgw(1,1,1)), 3, (/ int(size(qtgw,1), c_int64_t), int(size(qtgw,2), c_int64_t), int(size(qtgw,3), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(29, c_loc(egwdffi(1,1)), 2, (/ int((ncol), c_int64_t), int(pver+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    if (allocated(gwut)) then
      call put_slot(30, c_loc(gwut(1,1,1)), 3, (/ int(size(gwut,1), c_int64_t), int(size(gwut,2), c_int64_t), int(size(gwut,3), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(30, 3, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(31, c_loc(dttdf(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(32, c_loc(dttke(1,1)), 2, (/ int((ncol), c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call empty_slot(33, 3, 1, 0, ptrs, ndims, shapes, dtypes, intents)
  end subroutine gw_drag_prof_frame

  subroutine gw_drag_prof_original()
    ! the original call, gw_drag.F90:1299-1303, verbatim
         call gw_drag_prof(ncol, band_oro, p, src_level, tend_level,   dt,   &
              t,    &
              piln, rhoi,       nm,   ni, ubm,  ubi,  xv,    yv,   &
              effgw,c,          kvtt, q,  dse,  tau,  utgw,  vtgw, &
              ttgw, qtgw, egwdffi,  gwut, dttdf, dttke)
  end subroutine gw_drag_prof_original

  subroutine put_slot(index, address, rank, shape, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(in) :: address
    integer(c_int64_t), intent(in) :: shape(:)
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer :: axis
    ptrs(index) = address
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    do axis = 1, rank
      shapes(axis, index) = shape(axis)
    end do
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine put_slot

  subroutine empty_slot(index, rank, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    ! an argument with no storage in this call: a null address and zero extents
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    ptrs(index) = c_null_ptr
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine empty_slot

end module pycam_gwd_driver
