! tphysac (physpkg.F90:1458-1471) hoisted for the
! chem segment runner: its locals as module state, its body in pieces the
! runner calls in the source's order, its dummies bound by the caller.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/chemistry_tendencies.yaml.  Do not edit by hand; edit the spec.
module pycam_chem_glue
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_loc, c_null_ptr, c_f_pointer
  use shr_kind_mod, only: r8 => shr_kind_r8
  use pycam_stage_hosts, only: host_state, host_tend, host_pbuf2d, host_cam_in, host_cam_out
  use physics_buffer, only: pbuf_get_chunk
  use time_manager, only: get_nstep, get_step_size
  use spmd_utils, only: masterproc
  use physconst, only: latvap, latice, rh2o
  use physics_types, only: physics_state, physics_tend, physics_state_set_grid, physics_ptend, physics_tend_init, physics_update, physics_type_alloc, physics_ptend_dealloc, physics_state_alloc, physics_state_dealloc, physics_tend_alloc, physics_tend_dealloc
  use phys_grid, only: get_ncols_p
  use phys_gmean, only: gmean_mass
  use ppgrid, only: begchunk, endchunk, pcols, pver, pverp, psubcols
  use constituents, only: pcnst, cnst_name, cnst_get_ind
  use camsrfexch, only: cam_out_t, cam_in_t
  use cam_control_mod, only: ideal_phys, adiabatic
  use phys_control, only: phys_do_flux_avg, phys_getopts, waccmx_is
  use scamMod, only: single_column, scm_crm_mode
  use flux_avg, only: flux_avg_init
  use infnan, only: posinf, assignment(=)
  use mpishorthand
  use perf_mod
  use cam_logfile, only: iulog
  use camsrfexch, only: cam_export
  use modal_aero_calcsize, only: modal_aero_calcsize_init, modal_aero_calcsize_diag, modal_aero_calcsize_reg
  use modal_aero_wateruptake, only: modal_aero_wateruptake_init, modal_aero_wateruptake_dr, modal_aero_wateruptake_reg
  use physics_buffer, only: physics_buffer_desc, pbuf_set_field, pbuf_get_index, pbuf_get_field, pbuf_old_tim_idx
  use chemistry, only: chem_is_active, chem_timestep_tend, chem_emissions
  use cam_diagnostics, only: diag_phys_tend_writeout
  use gw_drag, only: gw_tend
  use vertical_diffusion, only: vertical_diffusion_tend
  use rayleigh_friction, only: rayleigh_friction_tend
  use constituents, only: cnst_get_ind
  use physics_types, only: physics_state, physics_tend, physics_ptend, physics_update, physics_dme_adjust, set_dry_to_wet, physics_state_check
  use majorsp_diffusion, only: mspd_intr
  use ionosphere, only: ionos_tend
  use tracers, only: tracers_timestep_tend
  use aoa_tracers, only: aoa_tracers_timestep_tend
  use physconst, only: rhoh2o, latvap,latice
  use aero_model, only: aero_model_drydep
  use carma_intr, only: carma_emission_tend, carma_timestep_tend
  use carma_flags_mod, only: carma_do_aerosol, carma_do_emission
  use check_energy, only: check_energy_chng
  use check_energy, only: check_tracers_data, check_tracers_init, check_tracers_chng
  use time_manager, only: get_nstep
  use cam_abortutils, only: endrun
  use dycore, only: dycore_is
  use cam_control_mod, only: aqua_planet
  use mo_gas_phase_chemdr,only: map2chm
  use clybry_fam, only: clybry_fam_set
  use charge_neutrality, only: charge_fix
  use qbo, only: qbo_relax
  use iondrag, only: iondrag_calc, do_waccm_ions
  use clubb_intr, only: clubb_surface
  use flux_avg, only: flux_avg_run
  use unicon_cam, only: unicon_cam_org_diags
  use water_tracer_vars, only: trace_water, wtrc_iatype, wtrc_bulk_indices
  use water_tracers, only: wtrc_check_h2o
  use comsrf, only: comsrf_fsds => fsds
  use pycam_chem_driver, only: driver_bind
  implicit none
  private
  public :: glue_piece_1, glue_piece_2, glue_enter, glue_bind_driver

  integer(c_int64_t), parameter :: zero_shape(1) = (/ 0_c_int64_t /)

  ! the routine's dummies, bound by the caller
  real(r8), save, public :: ztodt
  type(cam_in_t), pointer, save, public :: cam_in => null()
  real(r8), pointer, save, public :: sgh(:) => null()
  real(r8), pointer, save, public :: sgh30(:) => null()
  type(cam_out_t), pointer, save, public :: cam_out => null()
  type(physics_state), pointer, save, public :: state => null()
  type(physics_tend), pointer, save, public :: tend => null()
  type(physics_buffer_desc), pointer, save, public :: pbuf(:) => null()
  real(r8), pointer, save, public :: fsds(:) => null()

  ! locals that are pycesm carries of derived type: pointers to physpkg's records
  type(check_tracers_data), pointer, save, public :: tracerint => null()

  ! a piece's return, cycle or exit at the routine's level, for the runner to carry out
  integer, save, public :: flow = 0

  ! the routine's locals, held for the chunk in flight
  real(r8), save, target, public :: fh2o(pcols)
  logical, save, target, public :: isok
  integer, save, target, public :: lchnk
  integer, save, target, public :: ncol
  integer, save, target, public :: nstep
  type(physics_ptend), save, target, public :: ptend
  real(r8), save, target, public :: zero(pcols)

contains

  subroutine glue_enter(lchnk_in)
    ! tphysbc's dummies for this chunk, its carries as views, and the entry
    ! statements every stage relies on (lchnk, ncol, nstep, ...)
    use cam_abortutils, only: endrun
    interface
      integer(c_int) function pycam_ac_tracerint_addr_v1(lchnk, ptr) bind(C, name='pycam_ac_tracerint_addr_v1')
        import :: c_int, c_ptr
        integer(c_int), value, intent(in) :: lchnk
        type(c_ptr), intent(out) :: ptr
      end function pycam_ac_tracerint_addr_v1
    end interface
    integer, intent(in) :: lchnk_in
    type(c_ptr) :: address
    integer(c_int) :: ndims, status
    integer(c_int64_t) :: extents(4)
    ztodt = real(get_step_size(), r8)
    cam_in => host_cam_in(lchnk_in)
    cam_out => host_cam_out(lchnk_in)
    state => host_state(lchnk_in)
    tend => host_tend(lchnk_in)
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk_in)
    call glue_view(comsrf_fsds(:, lchnk_in), address)
    call c_f_pointer(address, fsds, (/ pcols /))
    status = pycam_ac_tracerint_addr_v1(int(lchnk_in, c_int), address)
    if (status /= 0_c_int) call endrun('pycam_chem_runner: record tracerint refused')
    call c_f_pointer(address, tracerint)
    lchnk = state%lchnk
    ncol = state%ncol
    nstep = get_nstep()
    zero = 0._r8
  end subroutine glue_enter

  subroutine glue_bind_driver()
    ! physpkg.F90:1459-1460: the call's actuals bound to the unit's dummies
    call driver_bind(state, ptend, cam_in, cam_out, ztodt, pbuf, fh2o, fsds)
  end subroutine glue_bind_driver

  subroutine glue_piece_1()
    ! physpkg.F90:1462-1465, verbatim

           call physics_update(state, ptend, ztodt, tend)
           call check_energy_chng(state, tend, "chem", nstep, ztodt, fh2o, zero, zero, zero)
           call check_tracers_chng(state, tracerint, "chem_timestep_tend", nstep, ztodt, &
                cam_in%cflx)

  end subroutine glue_piece_1

  subroutine glue_piece_2()
    ! physpkg.F90:1469-1471, verbatim

         if(trace_water) then
           isOK = wtrc_check_h2o("after-tracer source/sink", state, state%q, ztodt)
         end if

  end subroutine glue_piece_2

  subroutine glue_view(field, address)
    ! a TARGET dummy so c_loc is legal whatever the actual argument's attributes;
    ! a contiguous actual is passed without a copy
    real(r8), intent(inout), target :: field(*)
    type(c_ptr), intent(out) :: address
    address = c_loc(field(1))
  end subroutine glue_view

  subroutine put_slot(index, address, rank, shape, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(in) :: address
    integer(c_int64_t), intent(in) :: shape(:)
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer :: axis
    ptrs(index) = address
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    do axis = 1, rank
      shapes(axis, index) = shape(axis)
    end do
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine put_slot

  subroutine empty_slot(index, rank, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    ! an argument with no storage in this call: a null address and zero extents
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    ptrs(index) = c_null_ptr
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine empty_slot

end module pycam_chem_glue
