! The segment runner for cam_run2.chemistry_tendencies_leaf: the original Fortran, pausable at
! gas_phase_chemdr.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/chemistry_tendencies.yaml.  Do not edit by hand; edit the spec.
!
! The runner is a state machine over the units' pieces: start() runs from the
! top of the action for every chunk of this rank and returns either DONE or,
! when a replaced kernel's call is reached, NEEDS_PYTHON_KERNEL with the
! program counter parked before the call; frame() describes the call's
! arguments where they live; resume() continues past the call; original()
! runs the very call on the paused frame.  Python makes every call; Fortran
! never calls Python.
module pycam_chem_runner
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_char, c_null_ptr, c_loc
  use ppgrid, only: begchunk, endchunk
  use pycam_stage_hosts, only: stage_hosts_ok
  use pycam_chem_glue, only: glue_piece_1, glue_piece_2, glue_bind_driver, glue_enter
  use pycam_chem_driver, only: driver_piece_1, driver_piece_2, gas_phase_chemdr_frame, gas_phase_chemdr_original, driver_flow => flow
  use chemistry, only: chem_is_active
  implicit none
  private

  integer(c_int), parameter :: ev_done = 0_c_int, ev_needs_kernel = 1_c_int, ev_error = 2_c_int
  integer, parameter :: pc_idle = 0
  integer, parameter :: pc_chunk_begin = 1
  integer, parameter :: pc_chunk_end = 2
  integer, parameter :: pc_glue_piece_2_1 = 3
  integer, parameter :: pc_glue_piece_1_1 = 4
  integer, parameter :: pc_driver_piece_2_1 = 5
  integer, parameter :: pc_before_gas_phase_chemdr_1 = 6
  integer, parameter :: pc_at_gas_phase_chemdr = 7
  integer, parameter :: pc_after_gas_phase_chemdr = 8
  integer, parameter :: pc_driver_piece_1_1 = 9
  integer, parameter :: pc_leave_driver_1 = 10
  integer, parameter :: pc_enter_driver_1 = 11
  integer, parameter :: pc_if_1 = 12
  integer(c_int), parameter :: kernel_gas_phase_chemdr = 1_c_int
  integer, parameter :: nkernels = 1
  integer, parameter, public :: frame_slots = 34
  integer, parameter :: context_id = 1

  logical, save :: created = .false.
  integer, save :: pc = pc_idle
  integer, save :: lchnk = 0
  integer(c_int), save :: token = 0_c_int, call_index = 0_c_int
  logical, save :: replace(nkernels) = .false.
  character(len=256), save :: last_error = ' '

contains

  ! ------------------------------------------------------------------ !
  ! The ABI Python drives
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_chem_create_v1(context) bind(C, name='pycam_chem_create_v1') result(status)
    integer(c_int), intent(out) :: context
    context = 0_c_int
    status = 1_c_int
    if (created) then
      last_error = 'chem context already exists'; return
    end if
    if (.not. stage_hosts_ok(int(begchunk, c_int))) then
      last_error = 'chem: the stage hosts are not bound (pycam_stagehost_bind_v1 first)'; return
    end if
    status = 2_c_int
    created = .true.
    pc = pc_idle
    context = int(context_id, c_int)
    status = 0_c_int
  end function pycam_chem_create_v1

  integer(c_int) function pycam_chem_start_v1(context, count, mask, event) bind(C, name='pycam_chem_start_v1') result(status)
    integer(c_int), value, intent(in) :: context, count
    integer(c_int), intent(in) :: mask(count)
    integer(c_int), intent(out) :: event
    integer :: k
    event = ev_error
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no chem context'; return
    end if
    if (pc /= pc_idle) then
      last_error = 'chem is not idle; resume or reset it first'; status = 2_c_int; return
    end if
    if (count < nkernels) then
      last_error = 'replacement mask is too short'; status = 3_c_int; return
    end if
    do k = 1, nkernels
      replace(k) = mask(k) /= 0_c_int
    end do
    call_index = 0_c_int
    lchnk = begchunk
    pc = pc_chunk_begin
    call advance(event)
    status = 0_c_int
  end function pycam_chem_start_v1

  integer(c_int) function pycam_chem_resume_v1(context, kernel, token_in, event) bind(C, name='pycam_chem_resume_v1') result(status)
    integer(c_int), value, intent(in) :: context, kernel, token_in
    integer(c_int), intent(out) :: event
    event = ev_error
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no chem context'; return
    end if
    if (token_in /= token) then
      last_error = 'stale resume: the frame token does not match the pause'; status = 4_c_int; return
    end if
    select case (pc)
    case (pc_at_gas_phase_chemdr)
      if (kernel /= kernel_gas_phase_chemdr) then
        last_error = 'chem is paused on gas_phase_chemdr, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_gas_phase_chemdr
    case default
      last_error = 'chem is not paused'; status = 2_c_int; return
    end select
    token = token + 1_c_int
    call advance(event)
    status = 0_c_int
  end function pycam_chem_resume_v1

  integer(c_int) function pycam_chem_frame_v1(context, kernel, index_out, lchnk_out, ncol_out, &
       substep_out, token_out, count, ptrs, ndims, shapes, dtypes, intents) bind(C, name='pycam_chem_frame_v1') result(status)
    integer(c_int), value, intent(in) :: context, count
    integer(c_int), intent(out) :: kernel, index_out, lchnk_out, ncol_out, substep_out, token_out
    type(c_ptr), intent(out) :: ptrs(count)
    integer(c_int), intent(out) :: ndims(count), dtypes(count), intents(count)
    integer(c_int64_t), intent(out) :: shapes(5, count)
    kernel = 0_c_int; index_out = 0_c_int; lchnk_out = 0_c_int; ncol_out = 0_c_int
    substep_out = 0_c_int; token_out = 0_c_int
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no chem context'; return
    end if
    if (count < frame_slots) then
      last_error = 'frame table is too short'; status = 3_c_int; return
    end if
    select case (pc)
    case (pc_at_gas_phase_chemdr)
      call gas_phase_chemdr_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_gas_phase_chemdr
    case default
      last_error = 'chem is not paused; there is no frame'; status = 2_c_int; return
    end select
    index_out = call_index
    lchnk_out = int(lchnk, c_int)
    substep_out = 1_c_int
    token_out = token
    status = 0_c_int
  end function pycam_chem_frame_v1

  integer(c_int) function pycam_chem_original_v1(context, kernel) bind(C, name='pycam_chem_original_v1') result(status)
    ! Run the original call on the paused frame: the validation gate's
    ! replacement, exercising the pause, the frame and the resume.
    integer(c_int), value, intent(in) :: context, kernel
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no chem context'; return
    end if
    select case (pc)
    case (pc_at_gas_phase_chemdr)
      if (kernel /= kernel_gas_phase_chemdr) then
        last_error = 'chem is paused on gas_phase_chemdr, not on the kernel asked for'; status = 3_c_int; return
      end if
      call gas_phase_chemdr_original()
    case default
      last_error = 'chem is not paused; there is nothing to run'; status = 2_c_int; return
    end select
    status = 0_c_int
  end function pycam_chem_original_v1

  integer(c_int) function pycam_chem_error_v1(context, buffer, length) bind(C, name='pycam_chem_error_v1') result(status)
    integer(c_int), value, intent(in) :: context, length
    character(kind=c_char), intent(out) :: buffer(length)
    integer :: n, i
    n = min(length - 1, len_trim(last_error))
    do i = 1, n
      buffer(i) = last_error(i:i)
    end do
    buffer(n + 1) = c_char_'\0'
    status = 0_c_int
    if (context /= context_id) status = 1_c_int
  end function pycam_chem_error_v1

  integer(c_int) function pycam_chem_reset_v1(context) bind(C, name='pycam_chem_reset_v1') result(status)
    integer(c_int), value, intent(in) :: context
    status = 1_c_int
    if (.not. created .or. context /= context_id) return
    pc = pc_idle
    status = 0_c_int
  end function pycam_chem_reset_v1

  integer(c_int) function pycam_chem_destroy_v1(context) bind(C, name='pycam_chem_destroy_v1') result(status)
    integer(c_int), value, intent(in) :: context
    status = 1_c_int
    if (.not. created .or. context /= context_id) return
    created = .false.
    pc = pc_idle
    status = 0_c_int
  end function pycam_chem_destroy_v1

  ! ------------------------------------------------------------------ !
  ! The state machine
  ! ------------------------------------------------------------------ !

  subroutine advance(event)
    integer(c_int), intent(out) :: event
    do
      select case (pc)
      case (pc_chunk_begin)
        if (lchnk > endchunk) then
          pc = pc_idle
          event = ev_done
          return
        end if
        call glue_enter(lchnk)
        pc = pc_if_1
      case (pc_chunk_end)
        lchnk = lchnk + 1
        pc = pc_chunk_begin
      case (pc_glue_piece_2_1)
        call glue_piece_2()
        pc = pc_chunk_end
      case (pc_glue_piece_1_1)
        call glue_piece_1()
        pc = pc_glue_piece_2_1
      case (pc_driver_piece_2_1)
        call driver_piece_2()
        pc = pc_leave_driver_1
      case (pc_before_gas_phase_chemdr_1)
        if (replace(1)) then
          token = token + 1_c_int
          pc = pc_at_gas_phase_chemdr
          event = ev_needs_kernel
          return
        end if
        call gas_phase_chemdr_original()
        pc = pc_after_gas_phase_chemdr
      case (pc_at_gas_phase_chemdr)
        last_error = 'chem is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_gas_phase_chemdr)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_2_1
      case (pc_driver_piece_1_1)
        call driver_piece_1()
        select case (driver_flow)
        case (3)
          driver_flow = 0
          pc = pc_leave_driver_1
        case default
          pc = pc_before_gas_phase_chemdr_1
        end select
      case (pc_leave_driver_1)
        pc = pc_glue_piece_1_1
      case (pc_enter_driver_1)
        call glue_bind_driver()
        pc = pc_driver_piece_1_1
      case (pc_if_1)
        if (chem_is_active()) then
          pc = pc_enter_driver_1
        else
          pc = pc_glue_piece_2_1
        end if
      case default
        last_error = 'chem program counter is corrupt'
        event = ev_error
        return
      end select
    end do
  end subroutine advance

end module pycam_chem_runner
