! aero_model_wetdep (aero_model.F90:896-1255) hoisted for the
! awet segment runner: its locals as module state, its body in pieces the
! runner calls in the source's order, its dummies bound by the caller.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/aerosol_wet_deposition.yaml.  Do not edit by hand; edit the spec.
module pycam_awet_driver
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_loc, c_null_ptr, c_f_pointer
  use shr_kind_mod, only: r8 => shr_kind_r8
  use constituents, only: pcnst, cnst_name, cnst_get_ind
  use ppgrid, only: pcols, pver, pverp
  use cam_abortutils, only: endrun
  use cam_logfile, only: iulog
  use perf_mod, only: t_startf, t_stopf
  use camsrfexch, only: cam_in_t, cam_out_t
  use aerodep_flx, only: aerodep_flx_prescribed
  use physics_types, only: physics_state, physics_ptend, physics_ptend_init
  use physics_buffer, only: physics_buffer_desc
  use physics_buffer, only: pbuf_get_field, pbuf_get_index, pbuf_set_field
  use physconst, only: gravit, rair, rhoh2o
  use spmd_utils, only: masterproc
  use cam_history, only: outfld, fieldname_len
  use chem_mods, only: gas_pcnst, adv_mass
  use mo_tracname, only: solsym
  use modal_aero_data,only: cnst_name_cw
  use modal_aero_data,only: ntot_amode, modename_amode
  use ref_pres, only: top_lev => clim_modal_aero_top_lev
  use modal_aero_wateruptake, only: modal_strat_sulfate
  use modal_aero_deposition, only: set_srf_wetdep
  use wetdep, only: wetdepa_v2, wetdep_inputs_set, wetdep_inputs_t
  use modal_aero_data
  use modal_aero_calcsize, only: modal_aero_calcsize_sub
  use modal_aero_wateruptake,only: modal_aero_wateruptake_dr
  use aero_model, only: nmodes, dgnumwet_idx, qaerwat_idx, fracis_idx, nwetdep, wetdep_lq, sol_facti_cloud_borne, sol_factb_interstitial, sol_factic_interstitial, modal_aero_bcscavcoef_get
  implicit none
  private
  public :: driver_piece_1, driver_piece_2, driver_piece_3, driver_piece_4, driver_piece_5, driver_piece_6, driver_piece_7, driver_piece_8, driver_piece_9, wetdepa_v2_1_frame, wetdepa_v2_2_frame, wetdepa_v2_1_original, wetdepa_v2_2_original, driver_bind

  integer(c_int64_t), parameter :: zero_shape(1) = (/ 0_c_int64_t /)

  ! the routine's dummies, bound by the caller
  type(physics_state), pointer, save, public :: state => null()
  real(r8), save, public :: dt
  real(r8), pointer, save, public :: dlf(:,:) => null()
  type(cam_out_t), pointer, save, public :: cam_out => null()
  type(physics_ptend), pointer, save, public :: ptend => null()
  type(physics_buffer_desc), pointer, save, public :: pbuf(:) => null()

  ! a piece's return, cycle or exit at the routine's level, for the runner to carry out
  integer, save, public :: flow = 0

  ! the routine's locals, held for the chunk in flight
  real(r8), save, target, public :: aerdepwetcw(pcols,pcnst)
  real(r8), save, target, public :: aerdepwetis(pcols,pcnst)
  real(r8), save, target, public :: bcscavt(pcols,pver)
  real(r8), save, target, public :: bsscavt(pcols,pver)
  type(wetdep_inputs_t), save, target, public :: dep_inputs
  real(r8), pointer, save, public :: dgnumwet(:,:,:) => null()
  real(r8), save, target, public :: dqdt_tmp(pcols,pver)
  real(r8), save, target, public :: f_act_conv(pcols,pver)
  real(r8), save, target, public :: f_act_conv_coarse(pcols,pver)
  real(r8), save, target, public :: f_act_conv_coarse_dust
  real(r8), save, target, public :: f_act_conv_coarse_nacl
  real(r8), pointer, save, public :: fldcw(:,:) => null()
  real(r8), pointer, save, public :: fracis(:,:,:) => null()
  real(r8), save, target, public :: fracis_cw(pcols,pver)
  real(r8), save, target, public :: hygro_sum_del(pcols,pver)
  real(r8), save, target, public :: hygro_sum_new_ik
  real(r8), save, target, public :: hygro_sum_old(pcols,pver)
  real(r8), save, target, public :: hygro_sum_old_ik
  integer, save, target, public :: i
  real(r8), save, target, public :: icscavt(pcols,pver)
  real(r8), save, target, public :: iscavt(pcols,pver)
  logical, save, target, public :: isprx(pcols,pver)
  real(r8), save, target, public :: isscavt(pcols,pver)
  integer, save, target, public :: jnv
  integer, save, target, public :: k
  integer, save, target, public :: lchnk
  integer, save, target, public :: lcoardust
  integer, save, target, public :: lcoarnacl
  integer, save, target, public :: lphase
  integer, save, target, public :: lspec
  integer, save, target, public :: m
  integer, save, target, public :: mm
  integer, save, target, public :: ncol
  real(r8), save, target, public :: prec(pcols)
  real(r8), save, target, public :: q_tmp(pcols,pver)
  real(r8), pointer, save, public :: qaerwat(:,:,:) => null()
  real(r8), save, target, public :: scavcoefnv(pcols,pver,0:2)
  real(r8), save, target, public :: sflx(pcols)
  real(r8), save, target, public :: sol_factb
  real(r8), save, target, public :: sol_facti
  real(r8), save, target, public :: sol_factic(pcols,pver)
  real(r8), save, target, public :: tmpa
  real(r8), save, target, public :: tmpb
  real(r8), save, target, public :: tmpdust
  real(r8), save, target, public :: tmpnacl
  real(r8), save, target, public :: water_new
  real(r8), save, target, public :: water_old

contains

  subroutine driver_bind(a_state, a_dt, a_dlf, a_cam_out, a_ptend, a_pbuf)
    ! the dummies of aero_model_wetdep, as the caller's statement passes them
    type(physics_state), target, intent(inout) :: a_state
    real(r8), intent(in) :: a_dt
    real(r8), target, intent(inout) :: a_dlf(:,:)
    type(cam_out_t), target, intent(inout) :: a_cam_out
    type(physics_ptend), target, intent(inout) :: a_ptend
    type(physics_buffer_desc), target, intent(inout) :: a_pbuf(:)
    state => a_state
    dt = a_dt
    dlf => a_dlf
    cam_out => a_cam_out
    ptend => a_ptend
    pbuf => a_pbuf
  end subroutine driver_bind

  subroutine driver_piece_1()
    ! aero_model.F90:896-958, verbatim but for the flow statements the runner carries out

        lchnk = state%lchnk
        ncol  = state%ncol

        call physics_ptend_init(ptend, state%psetcols, 'aero_model_wetdep', lq=wetdep_lq)

        ! Do calculations of mode radius and water uptake if:
        ! 1) modal aerosols are affecting the climate, or
        ! 2) prognostic modal aerosols are enabled

        call t_startf('calcsize')
        ! for prognostic modal aerosols the transfer of mass between aitken and accumulation
        ! modes is done in conjunction with the dry radius calculation
        call modal_aero_calcsize_sub(state, ptend, dt, pbuf)
        call t_stopf('calcsize')

        call t_startf('wateruptake')
        call modal_aero_wateruptake_dr(state, pbuf)
        call t_stopf('wateruptake')

        if (nwetdep<1) then   ! return at the routine's level: the runner leaves the routine
          flow = 3
          return
        end if

        call wetdep_inputs_set( state, pbuf, dep_inputs )

        call pbuf_get_field(pbuf, dgnumwet_idx,       dgnumwet, start=(/1,1,1/), kount=(/pcols,pver,nmodes/) )
        call pbuf_get_field(pbuf, qaerwat_idx,        qaerwat,  start=(/1,1,1/), kount=(/pcols,pver,nmodes/) )
        call pbuf_get_field(pbuf, fracis_idx,         fracis, start=(/1,1,1/), kount=(/pcols, pver, pcnst/) )

        prec(:ncol)=0._r8
        do k=1,pver
           where (prec(:ncol) >= 1.e-7_r8)
              isprx(:ncol,k) = .true.
           elsewhere
              isprx(:ncol,k) = .false.
           endwhere
           prec(:ncol) = prec(:ncol) + (dep_inputs%prain(:ncol,k) + dep_inputs%cmfdqr(:ncol,k) - dep_inputs%evapr(:ncol,k)) &
                *state%pdel(:ncol,k)/gravit
        end do

        ! calculate the mass-weighted sol_factic for coarse mode species
        ! sol_factic_coarse(:,:) = 0.30_r8 ! tuned 1/4
        f_act_conv_coarse(:,:) = 0.60_r8 ! rce 2010/05/02
        f_act_conv_coarse_dust = 0.40_r8 ! rce 2010/05/02
        f_act_conv_coarse_nacl = 0.80_r8 ! rce 2010/05/02
        if (modeptr_coarse > 0) then
           lcoardust = lptr_dust_a_amode(modeptr_coarse)
           lcoarnacl = lptr_nacl_a_amode(modeptr_coarse)
           if ((lcoardust > 0) .and. (lcoarnacl > 0)) then
              do k = 1, pver
                 do i = 1, ncol
                    tmpdust = max( 0.0_r8, state%q(i,k,lcoardust) + ptend%q(i,k,lcoardust)*dt )
                    tmpnacl = max( 0.0_r8, state%q(i,k,lcoarnacl) + ptend%q(i,k,lcoarnacl)*dt )
                    if ((tmpdust+tmpnacl) > 1.0e-30_r8) then
                       ! sol_factic_coarse(i,k) = (0.2_r8*tmpdust + 0.4_r8*tmpnacl)/(tmpdust+tmpnacl) ! tuned 1/6
                       f_act_conv_coarse(i,k) = (f_act_conv_coarse_dust*tmpdust &
                            + f_act_conv_coarse_nacl*tmpnacl)/(tmpdust+tmpnacl) ! rce 2010/05/02
                    end if
                 end do
              end do
           end if
        end if

        scavcoefnv(:,:,0) = 0.0_r8 ! below-cloud scavcoef = 0.0 for cloud-borne species


  end subroutine driver_piece_1

  subroutine driver_piece_2()
    ! aero_model.F90:962-1020, verbatim


              ! sol_factb and sol_facti values
              ! sol_factb - currently this is basically a tuning factor
              ! sol_facti & sol_factic - currently has a physical basis, and reflects activation fraction
              !
              ! 2008-mar-07 rce - sol_factb (interstitial) changed from 0.3 to 0.1
              ! - sol_factic (interstitial, dust modes) changed from 1.0 to 0.5
              ! - sol_factic (cloud-borne, pcarb modes) no need to set it to 0.0
              ! because the cloud-borne pcarbon == 0 (no activation)
              !
              ! rce 2010/05/02
              ! prior to this date, sol_factic was used for convective in-cloud wet removal,
              ! and its value reflected a combination of an activation fraction (which varied between modes)
              ! and a tuning factor
              ! from this date forward, two parameters are used for convective in-cloud wet removal
              ! f_act_conv is the activation fraction
              ! note that "non-activation" of aerosol in air entrained into updrafts should
              ! be included here
              ! eventually we might use the activate routine (with w ~= 1 m/s) to calculate
              ! this, but there is still the entrainment issue
              ! sol_factic is strictly a tuning factor
              !
              if (lphase == 1) then ! interstial aerosol
                 hygro_sum_old(:,:) = 0.0_r8
                 hygro_sum_del(:,:) = 0.0_r8
                 call modal_aero_bcscavcoef_get( m, ncol, isprx, dgnumwet, &
                      scavcoefnv(:,:,1), scavcoefnv(:,:,2) )

                 sol_factb = sol_factb_interstitial ! all below-cloud scav ON (0.1 "tuning factor")

                 sol_facti = 0.0_r8 ! strat in-cloud scav totally OFF for institial

                 sol_factic = sol_factic_interstitial

                 if (m == modeptr_pcarbon) then
                    ! sol_factic = 0.0_r8 ! conv in-cloud scav OFF (0.0 activation fraction)
                    f_act_conv = 0.0_r8 ! rce 2010/05/02
                 else if ((m == modeptr_finedust) .or. (m == modeptr_coardust)) then
                    ! sol_factic = 0.2_r8 ! conv in-cloud scav ON (0.5 activation fraction) ! tuned 1/4
                    f_act_conv = 0.4_r8 ! rce 2010/05/02
                 else
                    ! sol_factic = 0.4_r8 ! conv in-cloud scav ON (1.0 activation fraction) ! tuned 1/4
                    f_act_conv = 0.8_r8 ! rce 2010/05/02
                 end if

              else ! cloud-borne aerosol (borne by stratiform cloud drops)

                 sol_factb  = 0.0_r8   ! all below-cloud scav OFF (anything cloud-borne is located "in-cloud")
                 sol_facti  = sol_facti_cloud_borne   ! strat  in-cloud scav cloud-borne tuning factor
                 sol_factic = 0.0_r8   ! conv   in-cloud scav OFF (having this on would mean
                                       !        that conv precip collects strat droplets)
                 f_act_conv = 0.0_r8   ! conv   in-cloud scav OFF (having this on would mean

              end if
              !
              ! rce 2010/05/03
              ! wetdepa has "sol_fact" parameters:
              ! sol_facti, sol_factic, sol_factb for liquid cloud


  end subroutine driver_piece_2

  subroutine driver_piece_3()
    ! aero_model.F90:1022-1075, verbatim but for the flow statements the runner carries out


                 if (lspec == 0) then ! number
                    if (lphase == 1) then
                       mm = numptr_amode(m)
                       jnv = 1
                    else
                       mm = numptrcw_amode(m)
                       jnv = 0
                    endif
                 else if (lspec <= nspec_amode(m)) then ! non-water mass
                    if (lphase == 1) then
                       mm = lmassptr_amode(lspec,m)
                       jnv = 2
                    else
                       mm = lmassptrcw_amode(lspec,m)
                       jnv = 0
                    endif
                 else ! water mass
                    ! bypass wet removal of aerosol water
                    flow = 1   ! cycle at the routine's level: the runner moves its loop
                    return
                    if (lphase == 1) then
                       mm = 0
                       ! mm = lwaterptr_amode(m)
                       jnv = 2
                    else
                       mm = 0
                       jnv = 0
                    endif
                 endif

                 if (mm <= 0) then   ! cycle at the routine's level: the runner moves its loop
                   flow = 1
                   return
                 end if


                 ! set f_act_conv for interstitial (lphase=1) coarse mode species
                 ! for the convective in-cloud, we conceptually treat the coarse dust and seasalt
                 ! as being externally mixed, and apply f_act_conv = f_act_conv_coarse_dust/nacl to dust/seasalt
                 ! number and sulfate are conceptually partitioned to the dust and seasalt
                 ! on a mass basis, so the f_act_conv for number and sulfate are
                 ! mass-weighted averages of the values used for dust/seasalt
                 if ((lphase == 1) .and. (m == modeptr_coarse)) then
                    ! sol_factic = sol_factic_coarse
                    f_act_conv = f_act_conv_coarse ! rce 2010/05/02
                    if (lspec > 0) then
                       if (lmassptr_amode(lspec,m) == lptr_dust_a_amode(m)) then
                          ! sol_factic = 0.2_r8 ! tuned 1/4
                          f_act_conv = f_act_conv_coarse_dust ! rce 2010/05/02
                       else if (lmassptr_amode(lspec,m) == lptr_nacl_a_amode(m)) then
                          ! sol_factic = 0.4_r8 ! tuned 1/6
                          f_act_conv = f_act_conv_coarse_nacl ! rce 2010/05/02
                       end if
                    end if
                 end if



  end subroutine driver_piece_3

  subroutine driver_piece_4()
    ! aero_model.F90:1077-1082, verbatim

                    ptend%lq(mm) = .TRUE.
                    dqdt_tmp(:,:) = 0.0_r8
                    ! q_tmp reflects changes from modal_aero_calcsize and is the "most current" q
                    q_tmp(1:ncol,:) = state%q(1:ncol,:,mm) + ptend%q(1:ncol,:,mm)*dt
                    fldcw => qqcw_get_field(pbuf, mm,lchnk)


  end subroutine driver_piece_4

  subroutine driver_piece_5()
    ! aero_model.F90:1096-1151, verbatim

                    ptend%q(1:ncol,:,mm) = ptend%q(1:ncol,:,mm) + dqdt_tmp(1:ncol,:)

                    call outfld( trim(cnst_name(mm))//'WET', dqdt_tmp(:,:), pcols, lchnk)
                    call outfld( trim(cnst_name(mm))//'SIC', icscavt, pcols, lchnk)
                    call outfld( trim(cnst_name(mm))//'SIS', isscavt, pcols, lchnk)
                    call outfld( trim(cnst_name(mm))//'SBC', bcscavt, pcols, lchnk)
                    call outfld( trim(cnst_name(mm))//'SBS', bsscavt, pcols, lchnk)

                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+dqdt_tmp(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name(mm))//'SFWET', sflx, pcols, lchnk)
                    aerdepwetis(:ncol,mm) = sflx(:ncol)

                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+icscavt(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name(mm))//'SFSIC', sflx, pcols, lchnk)
                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+isscavt(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name(mm))//'SFSIS', sflx, pcols, lchnk)
                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+bcscavt(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name(mm))//'SFSBC', sflx, pcols, lchnk)
                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+bsscavt(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name(mm))//'SFSBS', sflx, pcols, lchnk)

                    if (lspec > 0) then
                       tmpa = spechygro(lspectype_amode(lspec,m))/ &
                            specdens_amode(lspectype_amode(lspec,m))
                       tmpb = tmpa*dt
                       hygro_sum_old(1:ncol,:) = hygro_sum_old(1:ncol,:) &
                            + tmpa*q_tmp(1:ncol,:)
                       hygro_sum_del(1:ncol,:) = hygro_sum_del(1:ncol,:) &
                            + tmpb*dqdt_tmp(1:ncol,:)
                    end if


  end subroutine driver_piece_5

  subroutine driver_piece_6()
    ! aero_model.F90:1191-1193, verbatim

                    dqdt_tmp(:,:) = 0.0_r8
                    fldcw => qqcw_get_field(pbuf, mm,lchnk)


  end subroutine driver_piece_6

  subroutine driver_piece_7()
    ! aero_model.F90:1205-1244, verbatim

                    fldcw(1:ncol,:) = fldcw(1:ncol,:) + dqdt_tmp(1:ncol,:) * dt

                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+dqdt_tmp(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name_cw(mm))//'SFWET', sflx, pcols, lchnk)
                    aerdepwetcw(:ncol,mm) = sflx(:ncol)

                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+icscavt(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name_cw(mm))//'SFSIC', sflx, pcols, lchnk)
                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+isscavt(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name_cw(mm))//'SFSIS', sflx, pcols, lchnk)
                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+bcscavt(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name_cw(mm))//'SFSBC', sflx, pcols, lchnk)
                    sflx(:)=0._r8
                    do k=1,pver
                       do i=1,ncol
                          sflx(i)=sflx(i)+bsscavt(i,k)*state%pdel(i,k)/gravit
                       enddo
                    enddo
                    call outfld( trim(cnst_name_cw(mm))//'SFSBS', sflx, pcols, lchnk)


  end subroutine driver_piece_7

  subroutine driver_piece_8()
    ! aero_model.F90:1153-1189, verbatim

                    ! aerosol water -- because of how wetdepa treats evaporation of stratiform
                    ! precip, it is not appropriate to apply wetdepa to aerosol water
                    ! instead, "hygro_sum" = [sum of (mass*hygro/dens)] is calculated before and
                    ! after wet removal, and new water is calculated using
                    ! new_water = old_water*min(10,(hygro_sum_new/hygro_sum_old))
                    ! the "min(10,...)" is to avoid potential problems when hygro_sum_old ~= 0
                    ! also, individual wet removal terms (ic,is,bc,bs) are not output to history
                    ! ptend%lq(mm) = .TRUE.
                    ! dqdt_tmp(:,:) = 0.0_r8
                    do k = 1, pver
                       do i = 1, ncol
                          ! water_old = max( 0.0_r8, state%q(i,k,mm)+ptend%q(i,k,mm)*dt )
                          water_old = max( 0.0_r8, qaerwat(i,k,mm) )
                          hygro_sum_old_ik = max( 0.0_r8, hygro_sum_old(i,k) )
                          hygro_sum_new_ik = max( 0.0_r8, hygro_sum_old_ik+hygro_sum_del(i,k) )
                          if (hygro_sum_new_ik >= 10.0_r8*hygro_sum_old_ik) then
                             water_new = 10.0_r8*water_old
                          else
                             water_new = water_old*(hygro_sum_new_ik/hygro_sum_old_ik)
                          end if
                          ! dqdt_tmp(i,k) = (water_new - water_old)/dt
                          qaerwat(i,k,mm) = water_new
                       end do
                    end do

                    ! ptend%q(1:ncol,:,mm) = ptend%q(1:ncol,:,mm) + dqdt_tmp(1:ncol,:)

                    ! call outfld( trim(cnst_name(mm))

                    ! sflx(:)=0._r8
                    ! do k=1,pver
                    ! do i=1,ncol
                    ! sflx(i)=sflx(i)+dqdt_tmp(i,k)*state%pdel(i,k)/gravit
                    ! enddo
                    ! enddo
                    ! call outfld( trim(cnst_name(mm))


  end subroutine driver_piece_8

  subroutine driver_piece_9()
    ! aero_model.F90:1253-1255, verbatim

        if (.not.aerodep_flx_prescribed()) then
           call set_srf_wetdep(aerdepwetis, aerdepwetcw, cam_out)
        endif

  end subroutine driver_piece_9

  subroutine wetdepa_v2_1_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
    ! the paused `call wetdepa_v2( state%pmid, state%q(:,:,1), state%pdel, dep_inputs%cl...` in the callee's argument order
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer(c_int), intent(out) :: ncol_out
    real(c_double), save, target :: sc_1
    real(c_double), save, target :: sc_2
    integer(c_int32_t), save, target :: sc_3
    integer(c_int32_t), save, target :: sc_4
    real(c_double), save, target :: sc_5
    ncol_out = int(ncol, c_int)
    call put_slot(1, c_loc(state%pmid(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(2, c_loc(state%q(1,1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(3, c_loc(state%pdel(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(4, c_loc(dep_inputs%cldt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(5, c_loc(dep_inputs%cldcu(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(6, c_loc(dep_inputs%cmfdqr(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(7, c_loc(dep_inputs%evapc(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(8, c_loc(dep_inputs%conicw(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(9, c_loc(dep_inputs%prain(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(10, c_loc(dep_inputs%qme(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(11, c_loc(dep_inputs%evapr(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(12, c_loc(dep_inputs%totcond(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(13, c_loc(q_tmp(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_1 = real(dt, c_double)
    call put_slot(14, c_loc(sc_1), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(15, c_loc(dqdt_tmp(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(16, c_loc(iscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(17, c_loc(dep_inputs%cldvcu(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(18, c_loc(dep_inputs%cldvst(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(19, c_loc(dlf(lbound(dlf,1),lbound(dlf,2))), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    if (associated(fracis)) then
      call put_slot(20, c_loc(fracis(lbound(fracis,1),lbound(fracis,2),mm)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(20, 2, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    sc_2 = real(sol_factb, c_double)
    call put_slot(21, c_loc(sc_2), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_3 = int(ncol, c_int32_t)
    call put_slot(22, c_loc(sc_3), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(23, c_loc(scavcoefnv(1,1,jnv)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_4 = int(merge(1, 0, .false.), c_int32_t)
    call put_slot(24, c_loc(sc_4), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    if (associated(fldcw)) then
      call put_slot(25, c_loc(fldcw(lbound(fldcw,1),lbound(fldcw,2))), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(25, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(26, c_loc(f_act_conv(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(27, c_loc(icscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(28, c_loc(isscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(29, c_loc(bcscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(30, c_loc(bsscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    sc_5 = real(sol_facti, c_double)
    call put_slot(31, c_loc(sc_5), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(32, c_loc(sol_factic(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
  end subroutine wetdepa_v2_1_frame

  subroutine wetdepa_v2_1_original()
    ! the original call, aero_model.F90:1083-1094, verbatim
                    call wetdepa_v2( state%pmid, state%q(:,:,1), state%pdel, &
                         dep_inputs%cldt, dep_inputs%cldcu, dep_inputs%cmfdqr, &
                         dep_inputs%evapc, dep_inputs%conicw, dep_inputs%prain, dep_inputs%qme, &
                         dep_inputs%evapr, dep_inputs%totcond, q_tmp, dt, &
                         dqdt_tmp, iscavt, dep_inputs%cldvcu, dep_inputs%cldvst, &
                         dlf, fracis(:,:,mm), sol_factb, ncol, &
                         scavcoefnv(:,:,jnv), &
                         is_strat_cloudborne=.false.,  &
                         qqcw=fldcw,  &
                         f_act_conv=f_act_conv, &
                         icscavt=icscavt, isscavt=isscavt, bcscavt=bcscavt, bsscavt=bsscavt, &
                         sol_facti_in=sol_facti, sol_factic_in=sol_factic )
  end subroutine wetdepa_v2_1_original

  subroutine wetdepa_v2_2_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
    ! the paused `call wetdepa_v2(state%pmid, state%q(:,:,1), state%pdel, dep_inputs%cld...` in the callee's argument order
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer(c_int), intent(out) :: ncol_out
    real(c_double), save, target :: sc_1
    real(c_double), save, target :: sc_2
    integer(c_int32_t), save, target :: sc_3
    integer(c_int32_t), save, target :: sc_4
    real(c_double), save, target :: sc_5
    ncol_out = int(ncol, c_int)
    call put_slot(1, c_loc(state%pmid(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(2, c_loc(state%q(1,1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(3, c_loc(state%pdel(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(4, c_loc(dep_inputs%cldt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(5, c_loc(dep_inputs%cldcu(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(6, c_loc(dep_inputs%cmfdqr(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(7, c_loc(dep_inputs%evapc(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(8, c_loc(dep_inputs%conicw(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(9, c_loc(dep_inputs%prain(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(10, c_loc(dep_inputs%qme(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(11, c_loc(dep_inputs%evapr(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(12, c_loc(dep_inputs%totcond(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    if (associated(fldcw)) then
      call put_slot(13, c_loc(fldcw(lbound(fldcw,1),lbound(fldcw,2))), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(13, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    end if
    sc_1 = real(dt, c_double)
    call put_slot(14, c_loc(sc_1), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(15, c_loc(dqdt_tmp(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(16, c_loc(iscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(17, c_loc(dep_inputs%cldvcu(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(18, c_loc(dep_inputs%cldvst(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(19, c_loc(dlf(lbound(dlf,1),lbound(dlf,2))), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(20, c_loc(fracis_cw(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    sc_2 = real(sol_factb, c_double)
    call put_slot(21, c_loc(sc_2), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_3 = int(ncol, c_int32_t)
    call put_slot(22, c_loc(sc_3), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(23, c_loc(scavcoefnv(1,1,jnv)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_4 = int(merge(1, 0, .true.), c_int32_t)
    call put_slot(24, c_loc(sc_4), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call empty_slot(25, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call empty_slot(26, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(27, c_loc(icscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(28, c_loc(isscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(29, c_loc(bcscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(30, c_loc(bsscavt(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    sc_5 = real(sol_facti, c_double)
    call put_slot(31, c_loc(sc_5), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(32, c_loc(sol_factic(1,1)), 2, (/ int(pcols, c_int64_t), int(pver, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
  end subroutine wetdepa_v2_2_frame

  subroutine wetdepa_v2_2_original()
    ! the original call, aero_model.F90:1194-1203, verbatim
                    call wetdepa_v2(state%pmid, state%q(:,:,1), state%pdel, &
                         dep_inputs%cldt, dep_inputs%cldcu, dep_inputs%cmfdqr, &
                         dep_inputs%evapc, dep_inputs%conicw, dep_inputs%prain, dep_inputs%qme, &
                         dep_inputs%evapr, dep_inputs%totcond, fldcw, dt, &
                         dqdt_tmp, iscavt, dep_inputs%cldvcu, dep_inputs%cldvst, &
                         dlf, fracis_cw, sol_factb, ncol, &
                         scavcoefnv(:,:,jnv), &
                         is_strat_cloudborne=.true.,  &
                         icscavt=icscavt, isscavt=isscavt, bcscavt=bcscavt, bsscavt=bsscavt, &
                         sol_facti_in=sol_facti, sol_factic_in=sol_factic )
  end subroutine wetdepa_v2_2_original

  subroutine put_slot(index, address, rank, shape, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(in) :: address
    integer(c_int64_t), intent(in) :: shape(:)
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer :: axis
    ptrs(index) = address
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    do axis = 1, rank
      shapes(axis, index) = shape(axis)
    end do
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine put_slot

  subroutine empty_slot(index, rank, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    ! an argument with no storage in this call: a null address and zero extents
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    ptrs(index) = c_null_ptr
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine empty_slot

end module pycam_awet_driver
