! One Python-visible boundary at CAM5's liquid macrophysics kernel.
!
! `mmacro_pcond` is the only pure-numerical leaf inside `macrop_driver_tend`
! (macrop_driver.F90:1028, the sole call site in the code base).  This module
! turns that call site into a boundary Python can stand at, so a trained
! surrogate can take the kernel's place without the layer above it leaving
! Fortran, and without Fortran ever calling into Python: the routine is cut in
! two, Python is the caller of both halves, and this module carries across the
! gap what the second half needs.
!
! GENERATED by tools/generate_pi_cam_macro_split.py from the reviewed
! specification native/pi_cam/functions/mmacro_pcond.yaml.  Do not edit by
! hand; edit the specification or the generator.
!
! The exposed record is registered as a state-bridge owner, so every component
! reaches Python as a zero-copy `macro_split.<name>` view.  `in_*` are the
! 35 arguments the kernel reads, `out_*` and `ref_*` the 23 it returns --
! 17 outputs and the 6 in/out values as they leave.  Those are exactly the
! `input__*` and `output__*`/`updated__*` variables of a training set built by
! examples/generate_mmacro_pcond_dataset.py, so a surrogate keeps one layout
! from training to substitution.
!
! `kernel_mode`, written by Python, selects who computes those 23:
!
!   0  the original mmacro_pcond.  Its answer is published in `out_*` and read
!      back from `out_*`, so a Python process that only copies them proves the
!      round trip is exact without changing a single value.
!   1  Python.  The kernel is not called; `out_*` is whatever Python wrote.
!   2  the original, published in `ref_*` and read back from `ref_*`.  Python
!      sees the model's answer beside its own inputs and can score itself
!      inside a real integration without being able to perturb it.
!
! Nothing here is reached on the monolithic path (`stage == 0`): the original
! call runs untouched, which is what keeps the bit-for-bit gate meaningful.
!
! Not thread safe by construction: the admitted PI-atm build runs
! OMP_NUM_THREADS=1 and one chunk at a time per rank.

module pycam_macro_split

  use shr_kind_mod,   only: r8 => shr_kind_r8
  use ppgrid,         only: pcols, pver, begchunk, endchunk
  use physics_types,  only: physics_state, physics_ptend
  use water_types,    only: pwtype
  use cldwat2m_macro, only: mmacro_pcond
  use shr_sys_mod,    only: shr_sys_abort

  implicit none
  private

  public :: pycam_macro_record_t, pycam_macro_record
  public :: pycam_macro_before, pycam_macro_after

  integer, parameter, public :: pycam_macro_stage_first  = 1
  integer, parameter, public :: pycam_macro_stage_second = 2

  ! The kernel boundary, one record per chunk of this rank.  Registered in
  ! native/pi_cam/state_bridge.yaml; tests/unit/test_pi_cam_macro_split.py
  ! checks it component for component against the specification.
  type pycam_macro_record_t
     integer  :: kernel_mode
     integer  :: stage_seen
     real(r8) :: in_dt
     real(r8) :: in_p(pcols,pver)
     real(r8) :: in_dp(pcols,pver)
     real(r8) :: in_t0(pcols,pver)
     real(r8) :: in_qv0(pcols,pver)
     real(r8) :: in_ql0(pcols,pver)
     real(r8) :: in_qi0(pcols,pver)
     real(r8) :: in_nl0(pcols,pver)
     real(r8) :: in_ni0(pcols,pver)
     real(r8) :: in_a_t(pcols,pver)
     real(r8) :: in_a_qv(pcols,pver)
     real(r8) :: in_a_ql(pcols,pver)
     real(r8) :: in_a_qi(pcols,pver)
     real(r8) :: in_a_nl(pcols,pver)
     real(r8) :: in_a_ni(pcols,pver)
     real(r8) :: in_c_t(pcols,pver)
     real(r8) :: in_c_qv(pcols,pver)
     real(r8) :: in_c_ql(pcols,pver)
     real(r8) :: in_c_qi(pcols,pver)
     real(r8) :: in_c_nl(pcols,pver)
     real(r8) :: in_c_ni(pcols,pver)
     real(r8) :: in_c_qlst(pcols,pver)
     real(r8) :: in_d_t(pcols,pver)
     real(r8) :: in_d_qv(pcols,pver)
     real(r8) :: in_d_ql(pcols,pver)
     real(r8) :: in_d_qi(pcols,pver)
     real(r8) :: in_d_nl(pcols,pver)
     real(r8) :: in_d_ni(pcols,pver)
     real(r8) :: in_a_cud(pcols,pver)
     real(r8) :: in_a_cu0(pcols,pver)
     real(r8) :: in_clrw_old(pcols,pver)
     real(r8) :: in_clri_old(pcols,pver)
     real(r8) :: in_landfrac(pcols)
     real(r8) :: in_snowh(pcols)
     integer  :: in_do_cldice
     real(r8) :: out_s_tendout(pcols,pver)
     real(r8) :: out_qv_tendout(pcols,pver)
     real(r8) :: out_ql_tendout(pcols,pver)
     real(r8) :: out_qi_tendout(pcols,pver)
     real(r8) :: out_nl_tendout(pcols,pver)
     real(r8) :: out_ni_tendout(pcols,pver)
     real(r8) :: out_qme(pcols,pver)
     real(r8) :: out_qvadj(pcols,pver)
     real(r8) :: out_qladj(pcols,pver)
     real(r8) :: out_qiadj(pcols,pver)
     real(r8) :: out_qllim(pcols,pver)
     real(r8) :: out_qilim(pcols,pver)
     real(r8) :: out_cld(pcols,pver)
     real(r8) :: out_al_st_star(pcols,pver)
     real(r8) :: out_ai_st_star(pcols,pver)
     real(r8) :: out_ql_st_star(pcols,pver)
     real(r8) :: out_qi_st_star(pcols,pver)
     real(r8) :: out_t0(pcols,pver)
     real(r8) :: out_qv0(pcols,pver)
     real(r8) :: out_ql0(pcols,pver)
     real(r8) :: out_qi0(pcols,pver)
     real(r8) :: out_nl0(pcols,pver)
     real(r8) :: out_ni0(pcols,pver)
     real(r8) :: ref_s_tendout(pcols,pver)
     real(r8) :: ref_qv_tendout(pcols,pver)
     real(r8) :: ref_ql_tendout(pcols,pver)
     real(r8) :: ref_qi_tendout(pcols,pver)
     real(r8) :: ref_nl_tendout(pcols,pver)
     real(r8) :: ref_ni_tendout(pcols,pver)
     real(r8) :: ref_qme(pcols,pver)
     real(r8) :: ref_qvadj(pcols,pver)
     real(r8) :: ref_qladj(pcols,pver)
     real(r8) :: ref_qiadj(pcols,pver)
     real(r8) :: ref_qllim(pcols,pver)
     real(r8) :: ref_qilim(pcols,pver)
     real(r8) :: ref_cld(pcols,pver)
     real(r8) :: ref_al_st_star(pcols,pver)
     real(r8) :: ref_ai_st_star(pcols,pver)
     real(r8) :: ref_ql_st_star(pcols,pver)
     real(r8) :: ref_qi_st_star(pcols,pver)
     real(r8) :: ref_t0(pcols,pver)
     real(r8) :: ref_qv0(pcols,pver)
     real(r8) :: ref_ql0(pcols,pver)
     real(r8) :: ref_qi0(pcols,pver)
     real(r8) :: ref_nl0(pcols,pver)
     real(r8) :: ref_ni0(pcols,pver)
  end type pycam_macro_record_t

  type(pycam_macro_record_t), allocatable, target, save :: pycam_macro_record(:)

  ! Not a user boundary: continuity for the second half only.  These are the
  ! 14 values it reads that the kernel interface does not carry.
  type pycam_macro_carry_t
     real(r8) :: cldsice(pcols,pver)
     real(r8) :: cldst(pcols,pver)
     real(r8) :: fice(pcols,pver)
     real(r8) :: icecldf(pcols,pver)
     real(r8) :: liqcldf(pcols,pver)
     real(r8) :: mr_ccice(pcols,pver)
     real(r8) :: mr_ccliq(pcols,pver)
     real(r8) :: mr_lsice(pcols,pver)
     real(r8) :: mr_lsliq(pcols,pver)
     real(r8) :: nqctn(pcols,pver)
     real(r8) :: nqitn(pcols,pver)
     real(r8) :: pqctn(pcols,pver)
     real(r8) :: pqitn(pcols,pver)
     real(r8) :: process_rates(pcols,pver,pwtype,pwtype,pwtype)
  end type pycam_macro_carry_t

  type(pycam_macro_carry_t), allocatable, target, save :: carry(:)
  type(physics_state), allocatable, save :: carried_state(:)
  type(physics_ptend), allocatable, save :: carried_ptend(:)

contains

  subroutine ensure_allocated()
    if (allocated(pycam_macro_record)) return
    allocate(pycam_macro_record(begchunk:endchunk))
    allocate(carry(begchunk:endchunk))
    allocate(carried_state(begchunk:endchunk))
    allocate(carried_ptend(begchunk:endchunk))
    pycam_macro_record(:)%kernel_mode = 0
    pycam_macro_record(:)%stage_seen  = 0
  end subroutine ensure_allocated

  ! ------------------------------------------------------------------- !
  ! Tail of the first half: publish the boundary, run the kernel unless
  ! Python owns it, and park what the second half will need.
  ! ------------------------------------------------------------------- !
  subroutine pycam_macro_before( &
       stage, lchnk, ncol, dt, p, dp, t0, qv0, ql0, qi0, nl0, ni0, a_t, a_qv, &
       a_ql, a_qi, a_nl, a_ni, c_t, c_qv, c_ql, c_qi, c_nl, c_ni, c_qlst, &
       d_t, d_qv, d_ql, d_qi, d_nl, d_ni, a_cud, a_cu0, clrw_old, clri_old, &
       landfrac, snowh, tke, qtl_flx, qti_flx, cmfr_det, qlr_det, qir_det, &
       s_tendout, qv_tendout, ql_tendout, qi_tendout, nl_tendout, ni_tendout, &
       qme, qvadj, qladj, qiadj, qllim, qilim, cld, al_st_star, ai_st_star, &
       ql_st_star, qi_st_star, do_cldice, cldsice, cldst, fice, icecldf, &
       liqcldf, mr_ccice, mr_ccliq, mr_lsice, mr_lsliq, nqctn, nqitn, pqctn, &
       pqitn, process_rates, state_loc, ptend_loc)

    integer, intent(in) :: stage
    integer, intent(in) :: lchnk
    integer, intent(in) :: ncol
    real(r8), intent(in) :: dt
    real(r8), intent(in) :: p(pcols,pver)
    real(r8), intent(in) :: dp(pcols,pver)
    real(r8), intent(inout) :: t0(pcols,pver)
    real(r8), intent(inout) :: qv0(pcols,pver)
    real(r8), intent(inout) :: ql0(pcols,pver)
    real(r8), intent(inout) :: qi0(pcols,pver)
    real(r8), intent(inout) :: nl0(pcols,pver)
    real(r8), intent(inout) :: ni0(pcols,pver)
    real(r8), intent(in) :: a_t(pcols,pver)
    real(r8), intent(in) :: a_qv(pcols,pver)
    real(r8), intent(in) :: a_ql(pcols,pver)
    real(r8), intent(in) :: a_qi(pcols,pver)
    real(r8), intent(in) :: a_nl(pcols,pver)
    real(r8), intent(in) :: a_ni(pcols,pver)
    real(r8), intent(in) :: c_t(pcols,pver)
    real(r8), intent(in) :: c_qv(pcols,pver)
    real(r8), intent(in) :: c_ql(pcols,pver)
    real(r8), intent(in) :: c_qi(pcols,pver)
    real(r8), intent(in) :: c_nl(pcols,pver)
    real(r8), intent(in) :: c_ni(pcols,pver)
    real(r8), intent(in) :: c_qlst(pcols,pver)
    real(r8), intent(in) :: d_t(pcols,pver)
    real(r8), intent(in) :: d_qv(pcols,pver)
    real(r8), intent(in) :: d_ql(pcols,pver)
    real(r8), intent(in) :: d_qi(pcols,pver)
    real(r8), intent(in) :: d_nl(pcols,pver)
    real(r8), intent(in) :: d_ni(pcols,pver)
    real(r8), intent(in) :: a_cud(pcols,pver)
    real(r8), intent(in) :: a_cu0(pcols,pver)
    real(r8), intent(in) :: clrw_old(pcols,pver)
    real(r8), intent(in) :: clri_old(pcols,pver)
    real(r8), intent(in) :: landfrac(pcols)
    real(r8), intent(in) :: snowh(pcols)
    real(r8), pointer :: tke(:,:)
    real(r8), pointer :: qtl_flx(:,:)
    real(r8), pointer :: qti_flx(:,:)
    real(r8), pointer :: cmfr_det(:,:)
    real(r8), pointer :: qlr_det(:,:)
    real(r8), pointer :: qir_det(:,:)
    real(r8), intent(inout) :: s_tendout(pcols,pver)
    real(r8), intent(inout) :: qv_tendout(pcols,pver)
    real(r8), intent(inout) :: ql_tendout(pcols,pver)
    real(r8), intent(inout) :: qi_tendout(pcols,pver)
    real(r8), intent(inout) :: nl_tendout(pcols,pver)
    real(r8), intent(inout) :: ni_tendout(pcols,pver)
    real(r8), intent(inout) :: qme(pcols,pver)
    real(r8), intent(inout) :: qvadj(pcols,pver)
    real(r8), intent(inout) :: qladj(pcols,pver)
    real(r8), intent(inout) :: qiadj(pcols,pver)
    real(r8), intent(inout) :: qllim(pcols,pver)
    real(r8), intent(inout) :: qilim(pcols,pver)
    real(r8), intent(inout) :: cld(pcols,pver)
    real(r8), intent(inout) :: al_st_star(pcols,pver)
    real(r8), intent(inout) :: ai_st_star(pcols,pver)
    real(r8), intent(inout) :: ql_st_star(pcols,pver)
    real(r8), intent(inout) :: qi_st_star(pcols,pver)
    logical, intent(in) :: do_cldice
    real(r8), intent(in) :: cldsice(pcols,pver)
    real(r8), intent(in) :: cldst(pcols,pver)
    real(r8), intent(in) :: fice(pcols,pver)
    real(r8), intent(in) :: icecldf(pcols,pver)
    real(r8), intent(in) :: liqcldf(pcols,pver)
    real(r8), intent(in) :: mr_ccice(pcols,pver)
    real(r8), intent(in) :: mr_ccliq(pcols,pver)
    real(r8), intent(in) :: mr_lsice(pcols,pver)
    real(r8), intent(in) :: mr_lsliq(pcols,pver)
    real(r8), intent(in) :: nqctn(pcols,pver)
    real(r8), intent(in) :: nqitn(pcols,pver)
    real(r8), intent(in) :: pqctn(pcols,pver)
    real(r8), intent(in) :: pqitn(pcols,pver)
    real(r8), intent(in) :: process_rates(pcols,pver,pwtype,pwtype,pwtype)
    type(physics_state), intent(in) :: state_loc
    type(physics_ptend), intent(in) :: ptend_loc

    type(pycam_macro_record_t), pointer :: slot
    type(pycam_macro_carry_t),  pointer :: hold
    integer :: mode

    if (stage == 0) then
       ! Monolithic path: the original call, and nothing else.
       call mmacro_pcond( &
            lchnk, ncol, dt, p, dp, t0, qv0, ql0, qi0, nl0, ni0, a_t, a_qv, &
            a_ql, a_qi, a_nl, a_ni, c_t, c_qv, c_ql, c_qi, c_nl, c_ni, &
            c_qlst, d_t, d_qv, d_ql, d_qi, d_nl, d_ni, a_cud, a_cu0, &
            clrw_old, clri_old, landfrac, snowh, tke, qtl_flx, qti_flx, &
            cmfr_det, qlr_det, qir_det, s_tendout, qv_tendout, ql_tendout, &
            qi_tendout, nl_tendout, ni_tendout, qme, qvadj, qladj, qiadj, &
            qllim, qilim, cld, al_st_star, ai_st_star, ql_st_star, &
            qi_st_star, do_cldice)
       return
    end if

    call ensure_allocated()
    slot => pycam_macro_record(lchnk)
    hold => carry(lchnk)
    mode = slot%kernel_mode
    slot%stage_seen = pycam_macro_stage_first

    slot%in_dt = dt
    slot%in_p = p
    slot%in_dp = dp
    slot%in_t0 = t0
    slot%in_qv0 = qv0
    slot%in_ql0 = ql0
    slot%in_qi0 = qi0
    slot%in_nl0 = nl0
    slot%in_ni0 = ni0
    slot%in_a_t = a_t
    slot%in_a_qv = a_qv
    slot%in_a_ql = a_ql
    slot%in_a_qi = a_qi
    slot%in_a_nl = a_nl
    slot%in_a_ni = a_ni
    slot%in_c_t = c_t
    slot%in_c_qv = c_qv
    slot%in_c_ql = c_ql
    slot%in_c_qi = c_qi
    slot%in_c_nl = c_nl
    slot%in_c_ni = c_ni
    slot%in_c_qlst = c_qlst
    slot%in_d_t = d_t
    slot%in_d_qv = d_qv
    slot%in_d_ql = d_ql
    slot%in_d_qi = d_qi
    slot%in_d_nl = d_nl
    slot%in_d_ni = d_ni
    slot%in_a_cud = a_cud
    slot%in_a_cu0 = a_cu0
    slot%in_clrw_old = clrw_old
    slot%in_clri_old = clri_old
    slot%in_landfrac = landfrac
    slot%in_snowh = snowh
    slot%in_do_cldice = merge(1, 0, do_cldice)

    if (mode /= 1) then
       call mmacro_pcond( &
            lchnk, ncol, dt, p, dp, t0, qv0, ql0, qi0, nl0, ni0, a_t, a_qv, &
            a_ql, a_qi, a_nl, a_ni, c_t, c_qv, c_ql, c_qi, c_nl, c_ni, &
            c_qlst, d_t, d_qv, d_ql, d_qi, d_nl, d_ni, a_cud, a_cu0, &
            clrw_old, clri_old, landfrac, snowh, tke, qtl_flx, qti_flx, &
            cmfr_det, qlr_det, qir_det, s_tendout, qv_tendout, ql_tendout, &
            qi_tendout, nl_tendout, ni_tendout, qme, qvadj, qladj, qiadj, &
            qllim, qilim, cld, al_st_star, ai_st_star, ql_st_star, &
            qi_st_star, do_cldice)
    end if

    select case (mode)
    case (0)
       slot%out_s_tendout = s_tendout
       slot%out_qv_tendout = qv_tendout
       slot%out_ql_tendout = ql_tendout
       slot%out_qi_tendout = qi_tendout
       slot%out_nl_tendout = nl_tendout
       slot%out_ni_tendout = ni_tendout
       slot%out_qme = qme
       slot%out_qvadj = qvadj
       slot%out_qladj = qladj
       slot%out_qiadj = qiadj
       slot%out_qllim = qllim
       slot%out_qilim = qilim
       slot%out_cld = cld
       slot%out_al_st_star = al_st_star
       slot%out_ai_st_star = ai_st_star
       slot%out_ql_st_star = ql_st_star
       slot%out_qi_st_star = qi_st_star
       slot%out_t0 = t0
       slot%out_qv0 = qv0
       slot%out_ql0 = ql0
       slot%out_qi0 = qi0
       slot%out_nl0 = nl0
       slot%out_ni0 = ni0
    case (2)
       slot%ref_s_tendout = s_tendout
       slot%ref_qv_tendout = qv_tendout
       slot%ref_ql_tendout = ql_tendout
       slot%ref_qi_tendout = qi_tendout
       slot%ref_nl_tendout = nl_tendout
       slot%ref_ni_tendout = ni_tendout
       slot%ref_qme = qme
       slot%ref_qvadj = qvadj
       slot%ref_qladj = qladj
       slot%ref_qiadj = qiadj
       slot%ref_qllim = qllim
       slot%ref_qilim = qilim
       slot%ref_cld = cld
       slot%ref_al_st_star = al_st_star
       slot%ref_ai_st_star = ai_st_star
       slot%ref_ql_st_star = ql_st_star
       slot%ref_qi_st_star = qi_st_star
       slot%ref_t0 = t0
       slot%ref_qv0 = qv0
       slot%ref_ql0 = ql0
       slot%ref_qi0 = qi0
       slot%ref_nl0 = nl0
       slot%ref_ni0 = ni0
    end select

    hold%cldsice = cldsice
    hold%cldst = cldst
    hold%fice = fice
    hold%icecldf = icecldf
    hold%liqcldf = liqcldf
    hold%mr_ccice = mr_ccice
    hold%mr_ccliq = mr_ccliq
    hold%mr_lsice = mr_lsice
    hold%mr_lsliq = mr_lsliq
    hold%nqctn = nqctn
    hold%nqitn = nqitn
    hold%pqctn = pqctn
    hold%pqitn = pqitn
    hold%process_rates = process_rates
    carried_state(lchnk) = state_loc
    carried_ptend(lchnk) = ptend_loc
  end subroutine pycam_macro_before

  ! ------------------------------------------------------------------- !
  ! Head of the second half: restore what died with the first half, then
  ! take the 23 returned values from whoever owns them.
  ! ------------------------------------------------------------------- !
  subroutine pycam_macro_after( &
       stage, lchnk, s_tendout, qv_tendout, ql_tendout, qi_tendout, &
       nl_tendout, ni_tendout, qme, qvadj, qladj, qiadj, qllim, qilim, cld, &
       al_st_star, ai_st_star, ql_st_star, qi_st_star, t0, qv0, ql0, qi0, &
       nl0, ni0, clrw_old, clri_old, d_ql, d_qi, cldsice, cldst, fice, &
       icecldf, liqcldf, mr_ccice, mr_ccliq, mr_lsice, mr_lsliq, nqctn, &
       nqitn, pqctn, pqitn, process_rates, state_loc, ptend_loc)

    integer, intent(in) :: stage
    integer, intent(in) :: lchnk
    real(r8), intent(inout) :: s_tendout(pcols,pver)
    real(r8), intent(inout) :: qv_tendout(pcols,pver)
    real(r8), intent(inout) :: ql_tendout(pcols,pver)
    real(r8), intent(inout) :: qi_tendout(pcols,pver)
    real(r8), intent(inout) :: nl_tendout(pcols,pver)
    real(r8), intent(inout) :: ni_tendout(pcols,pver)
    real(r8), intent(inout) :: qme(pcols,pver)
    real(r8), intent(inout) :: qvadj(pcols,pver)
    real(r8), intent(inout) :: qladj(pcols,pver)
    real(r8), intent(inout) :: qiadj(pcols,pver)
    real(r8), intent(inout) :: qllim(pcols,pver)
    real(r8), intent(inout) :: qilim(pcols,pver)
    real(r8), intent(inout) :: cld(pcols,pver)
    real(r8), intent(inout) :: al_st_star(pcols,pver)
    real(r8), intent(inout) :: ai_st_star(pcols,pver)
    real(r8), intent(inout) :: ql_st_star(pcols,pver)
    real(r8), intent(inout) :: qi_st_star(pcols,pver)
    real(r8), intent(inout) :: t0(pcols,pver)
    real(r8), intent(inout) :: qv0(pcols,pver)
    real(r8), intent(inout) :: ql0(pcols,pver)
    real(r8), intent(inout) :: qi0(pcols,pver)
    real(r8), intent(inout) :: nl0(pcols,pver)
    real(r8), intent(inout) :: ni0(pcols,pver)
    real(r8), intent(inout) :: clrw_old(pcols,pver)
    real(r8), intent(inout) :: clri_old(pcols,pver)
    real(r8), intent(inout) :: d_ql(pcols,pver)
    real(r8), intent(inout) :: d_qi(pcols,pver)
    real(r8), intent(inout) :: cldsice(pcols,pver)
    real(r8), intent(inout) :: cldst(pcols,pver)
    real(r8), intent(inout) :: fice(pcols,pver)
    real(r8), intent(inout) :: icecldf(pcols,pver)
    real(r8), intent(inout) :: liqcldf(pcols,pver)
    real(r8), intent(inout) :: mr_ccice(pcols,pver)
    real(r8), intent(inout) :: mr_ccliq(pcols,pver)
    real(r8), intent(inout) :: mr_lsice(pcols,pver)
    real(r8), intent(inout) :: mr_lsliq(pcols,pver)
    real(r8), intent(inout) :: nqctn(pcols,pver)
    real(r8), intent(inout) :: nqitn(pcols,pver)
    real(r8), intent(inout) :: pqctn(pcols,pver)
    real(r8), intent(inout) :: pqitn(pcols,pver)
    real(r8), intent(inout) :: process_rates(pcols,pver,pwtype,pwtype,pwtype)
    type(physics_state), intent(inout) :: state_loc
    type(physics_ptend), intent(inout) :: ptend_loc

    type(pycam_macro_record_t), pointer :: slot
    type(pycam_macro_carry_t),  pointer :: hold
    integer :: mode

    if (stage == 0) return

    if (.not. allocated(pycam_macro_record)) then
       call shr_sys_abort('pycam_macro_after: the first half has never run')
    end if
    slot => pycam_macro_record(lchnk)
    hold => carry(lchnk)
    mode = slot%kernel_mode
    if (slot%stage_seen /= pycam_macro_stage_first) then
       call shr_sys_abort('pycam_macro_after: out of order for this chunk')
    end if
    slot%stage_seen = pycam_macro_stage_second

    cldsice = hold%cldsice
    cldst = hold%cldst
    fice = hold%fice
    icecldf = hold%icecldf
    liqcldf = hold%liqcldf
    mr_ccice = hold%mr_ccice
    mr_ccliq = hold%mr_ccliq
    mr_lsice = hold%mr_lsice
    mr_lsliq = hold%mr_lsliq
    nqctn = hold%nqctn
    nqitn = hold%nqitn
    pqctn = hold%pqctn
    pqitn = hold%pqitn
    process_rates = hold%process_rates
    state_loc = carried_state(lchnk)
    ptend_loc = carried_ptend(lchnk)

    clrw_old = slot%in_clrw_old
    clri_old = slot%in_clri_old
    d_ql = slot%in_d_ql
    d_qi = slot%in_d_qi

    if (mode == 2) then
       s_tendout = slot%ref_s_tendout
       qv_tendout = slot%ref_qv_tendout
       ql_tendout = slot%ref_ql_tendout
       qi_tendout = slot%ref_qi_tendout
       nl_tendout = slot%ref_nl_tendout
       ni_tendout = slot%ref_ni_tendout
       qme = slot%ref_qme
       qvadj = slot%ref_qvadj
       qladj = slot%ref_qladj
       qiadj = slot%ref_qiadj
       qllim = slot%ref_qllim
       qilim = slot%ref_qilim
       cld = slot%ref_cld
       al_st_star = slot%ref_al_st_star
       ai_st_star = slot%ref_ai_st_star
       ql_st_star = slot%ref_ql_st_star
       qi_st_star = slot%ref_qi_st_star
       t0 = slot%ref_t0
       qv0 = slot%ref_qv0
       ql0 = slot%ref_ql0
       qi0 = slot%ref_qi0
       nl0 = slot%ref_nl0
       ni0 = slot%ref_ni0
    else
       s_tendout = slot%out_s_tendout
       qv_tendout = slot%out_qv_tendout
       ql_tendout = slot%out_ql_tendout
       qi_tendout = slot%out_qi_tendout
       nl_tendout = slot%out_nl_tendout
       ni_tendout = slot%out_ni_tendout
       qme = slot%out_qme
       qvadj = slot%out_qvadj
       qladj = slot%out_qladj
       qiadj = slot%out_qiadj
       qllim = slot%out_qllim
       qilim = slot%out_qilim
       cld = slot%out_cld
       al_st_star = slot%out_al_st_star
       ai_st_star = slot%out_ai_st_star
       ql_st_star = slot%out_ql_st_star
       qi_st_star = slot%out_qi_st_star
       t0 = slot%out_t0
       qv0 = slot%out_qv0
       ql0 = slot%out_ql0
       qi0 = slot%out_qi0
       nl0 = slot%out_nl0
       ni0 = slot%out_ni0
    end if
  end subroutine pycam_macro_after

end module pycam_macro_split
