! The segment runner for cam_run2.vertical_diffusion: the original Fortran, pausable at
! compute_tms, compute_eddy_diff, compute_vdiff.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/vertical_diffusion.yaml.  Do not edit by hand; edit the spec.
!
! The runner is a state machine over the units' pieces: start() runs from the
! top of the action for every chunk of this rank and returns either DONE or,
! when a replaced kernel's call is reached, NEEDS_PYTHON_KERNEL with the
! program counter parked before the call; frame() describes the call's
! arguments where they live; resume() continues past the call; original()
! runs the very call on the paused frame.  Python makes every call; Fortran
! never calls Python.
module pycam_vdiff_runner
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_char, c_null_ptr, c_loc
  use ppgrid, only: begchunk, endchunk
  use pycam_stage_hosts, only: stage_hosts_ok
  use pycam_vdiff_glue, only: glue_piece_1, glue_piece_2, glue_piece_3, glue_piece_4, glue_bind_driver, glue_enter, &
       glue_configure, do_clubb_sgs
  use pycam_vdiff_driver, only: driver_piece_1, driver_piece_2, driver_piece_3, driver_piece_4, driver_piece_5, driver_piece_6, &
       driver_piece_7, driver_piece_8, driver_piece_9, driver_piece_10, driver_piece_11, driver_piece_12, &
       driver_piece_13, compute_tms_frame, compute_eddy_diff_frame, compute_vdiff_1_frame, compute_vdiff_2_frame, compute_tms_original, &
       compute_eddy_diff_original, compute_vdiff_1_original, compute_vdiff_2_original, driver_flow => flow
  use vertical_diffusion, only: do_tms, eddy_scheme, fieldlist_wet, fieldlist_dry
  use diffusion_solver, only: any
  implicit none
  private

  integer(c_int), parameter :: ev_done = 0_c_int, ev_needs_kernel = 1_c_int, ev_error = 2_c_int
  integer, parameter :: pc_idle = 0
  integer, parameter :: pc_chunk_begin = 1
  integer, parameter :: pc_chunk_end = 2
  integer, parameter :: pc_glue_piece_4_1 = 3
  integer, parameter :: pc_glue_piece_1_1 = 4
  integer, parameter :: pc_glue_piece_3_1 = 5
  integer, parameter :: pc_driver_piece_13_1 = 6
  integer, parameter :: pc_driver_piece_12_1 = 7
  integer, parameter :: pc_before_compute_vdiff_1 = 8
  integer, parameter :: pc_at_compute_vdiff_2 = 9
  integer, parameter :: pc_after_compute_vdiff_2 = 10
  integer, parameter :: pc_driver_piece_11_1 = 11
  integer, parameter :: pc_if_1 = 12
  integer, parameter :: pc_driver_piece_10_1 = 13
  integer, parameter :: pc_driver_piece_9_1 = 14
  integer, parameter :: pc_before_compute_vdiff_2 = 15
  integer, parameter :: pc_at_compute_vdiff_1 = 16
  integer, parameter :: pc_after_compute_vdiff_1 = 17
  integer, parameter :: pc_driver_piece_8_1 = 18
  integer, parameter :: pc_if_2 = 19
  integer, parameter :: pc_driver_piece_7_1 = 20
  integer, parameter :: pc_driver_piece_6_1 = 21
  integer, parameter :: pc_before_compute_eddy_diff_1 = 22
  integer, parameter :: pc_at_compute_eddy_diff = 23
  integer, parameter :: pc_after_compute_eddy_diff = 24
  integer, parameter :: pc_driver_piece_5_1 = 25
  integer, parameter :: pc_select_1 = 26
  integer, parameter :: pc_driver_piece_4_1 = 27
  integer, parameter :: pc_driver_piece_2_1 = 28
  integer, parameter :: pc_before_compute_tms_1 = 29
  integer, parameter :: pc_at_compute_tms = 30
  integer, parameter :: pc_after_compute_tms = 31
  integer, parameter :: pc_driver_piece_3_1 = 32
  integer, parameter :: pc_if_3 = 33
  integer, parameter :: pc_driver_piece_1_1 = 34
  integer, parameter :: pc_leave_driver_1 = 35
  integer, parameter :: pc_enter_driver_1 = 36
  integer, parameter :: pc_glue_piece_2_1 = 37
  integer, parameter :: pc_if_4 = 38
  integer(c_int), parameter :: kernel_compute_tms = 1_c_int
  integer(c_int), parameter :: kernel_compute_eddy_diff = 2_c_int
  integer(c_int), parameter :: kernel_compute_vdiff = 3_c_int
  integer, parameter :: nkernels = 3
  integer, parameter, public :: frame_slots = 55
  integer, parameter :: context_id = 1

  logical, save :: created = .false.
  integer, save :: pc = pc_idle
  integer, save :: lchnk = 0
  integer(c_int), save :: token = 0_c_int, call_index = 0_c_int
  logical, save :: replace(nkernels) = .false.
  character(len=256), save :: last_error = ' '

contains

  ! ------------------------------------------------------------------ !
  ! The ABI Python drives
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_vdiff_create_v1(context) bind(C, name='pycam_vdiff_create_v1') result(status)
    integer(c_int), intent(out) :: context
    context = 0_c_int
    status = 1_c_int
    if (created) then
      last_error = 'vdiff context already exists'; return
    end if
    if (.not. stage_hosts_ok(int(begchunk, c_int))) then
      last_error = 'vdiff: the stage hosts are not bound (pycam_stagehost_bind_v1 first)'; return
    end if
    call glue_configure()
    status = 2_c_int
    if (trim(eddy_scheme) /= 'diag_TKE') then
      last_error = 'vdiff: written for the diag_TKE eddy scheme'; return
    end if
    created = .true.
    pc = pc_idle
    context = int(context_id, c_int)
    status = 0_c_int
  end function pycam_vdiff_create_v1

  integer(c_int) function pycam_vdiff_start_v1(context, count, mask, event) bind(C, name='pycam_vdiff_start_v1') result(status)
    integer(c_int), value, intent(in) :: context, count
    integer(c_int), intent(in) :: mask(count)
    integer(c_int), intent(out) :: event
    integer :: k
    event = ev_error
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no vdiff context'; return
    end if
    if (pc /= pc_idle) then
      last_error = 'vdiff is not idle; resume or reset it first'; status = 2_c_int; return
    end if
    if (count < nkernels) then
      last_error = 'replacement mask is too short'; status = 3_c_int; return
    end if
    do k = 1, nkernels
      replace(k) = mask(k) /= 0_c_int
    end do
    call_index = 0_c_int
    lchnk = begchunk
    pc = pc_chunk_begin
    call advance(event)
    status = 0_c_int
  end function pycam_vdiff_start_v1

  integer(c_int) function pycam_vdiff_resume_v1(context, kernel, token_in, event) bind(C, name='pycam_vdiff_resume_v1') result(status)
    integer(c_int), value, intent(in) :: context, kernel, token_in
    integer(c_int), intent(out) :: event
    event = ev_error
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no vdiff context'; return
    end if
    if (token_in /= token) then
      last_error = 'stale resume: the frame token does not match the pause'; status = 4_c_int; return
    end if
    select case (pc)
    case (pc_at_compute_tms)
      if (kernel /= kernel_compute_tms) then
        last_error = 'vdiff is paused on compute_tms, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_compute_tms
    case (pc_at_compute_eddy_diff)
      if (kernel /= kernel_compute_eddy_diff) then
        last_error = 'vdiff is paused on compute_eddy_diff, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_compute_eddy_diff
    case (pc_at_compute_vdiff_1)
      if (kernel /= kernel_compute_vdiff) then
        last_error = 'vdiff is paused on compute_vdiff, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_compute_vdiff_1
    case (pc_at_compute_vdiff_2)
      if (kernel /= kernel_compute_vdiff) then
        last_error = 'vdiff is paused on compute_vdiff, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_compute_vdiff_2
    case default
      last_error = 'vdiff is not paused'; status = 2_c_int; return
    end select
    token = token + 1_c_int
    call advance(event)
    status = 0_c_int
  end function pycam_vdiff_resume_v1

  integer(c_int) function pycam_vdiff_frame_v1(context, kernel, index_out, lchnk_out, ncol_out, &
       substep_out, token_out, count, ptrs, ndims, shapes, dtypes, intents) bind(C, name='pycam_vdiff_frame_v1') result(status)
    integer(c_int), value, intent(in) :: context, count
    integer(c_int), intent(out) :: kernel, index_out, lchnk_out, ncol_out, substep_out, token_out
    type(c_ptr), intent(out) :: ptrs(count)
    integer(c_int), intent(out) :: ndims(count), dtypes(count), intents(count)
    integer(c_int64_t), intent(out) :: shapes(5, count)
    kernel = 0_c_int; index_out = 0_c_int; lchnk_out = 0_c_int; ncol_out = 0_c_int
    substep_out = 0_c_int; token_out = 0_c_int
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no vdiff context'; return
    end if
    if (count < frame_slots) then
      last_error = 'frame table is too short'; status = 3_c_int; return
    end if
    select case (pc)
    case (pc_at_compute_tms)
      call compute_tms_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_compute_tms
    case (pc_at_compute_eddy_diff)
      call compute_eddy_diff_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_compute_eddy_diff
    case (pc_at_compute_vdiff_1)
      call compute_vdiff_1_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_compute_vdiff
    case (pc_at_compute_vdiff_2)
      call compute_vdiff_2_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_compute_vdiff
    case default
      last_error = 'vdiff is not paused; there is no frame'; status = 2_c_int; return
    end select
    index_out = call_index
    lchnk_out = int(lchnk, c_int)
    substep_out = 1_c_int
    token_out = token
    status = 0_c_int
  end function pycam_vdiff_frame_v1

  integer(c_int) function pycam_vdiff_original_v1(context, kernel) bind(C, name='pycam_vdiff_original_v1') result(status)
    ! Run the original call on the paused frame: the validation gate's
    ! replacement, exercising the pause, the frame and the resume.
    integer(c_int), value, intent(in) :: context, kernel
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no vdiff context'; return
    end if
    select case (pc)
    case (pc_at_compute_tms)
      if (kernel /= kernel_compute_tms) then
        last_error = 'vdiff is paused on compute_tms, not on the kernel asked for'; status = 3_c_int; return
      end if
      call compute_tms_original()
    case (pc_at_compute_eddy_diff)
      if (kernel /= kernel_compute_eddy_diff) then
        last_error = 'vdiff is paused on compute_eddy_diff, not on the kernel asked for'; status = 3_c_int; return
      end if
      call compute_eddy_diff_original()
    case (pc_at_compute_vdiff_1)
      if (kernel /= kernel_compute_vdiff) then
        last_error = 'vdiff is paused on compute_vdiff, not on the kernel asked for'; status = 3_c_int; return
      end if
      call compute_vdiff_1_original()
    case (pc_at_compute_vdiff_2)
      if (kernel /= kernel_compute_vdiff) then
        last_error = 'vdiff is paused on compute_vdiff, not on the kernel asked for'; status = 3_c_int; return
      end if
      call compute_vdiff_2_original()
    case default
      last_error = 'vdiff is not paused; there is nothing to run'; status = 2_c_int; return
    end select
    status = 0_c_int
  end function pycam_vdiff_original_v1

  integer(c_int) function pycam_vdiff_error_v1(context, buffer, length) bind(C, name='pycam_vdiff_error_v1') result(status)
    integer(c_int), value, intent(in) :: context, length
    character(kind=c_char), intent(out) :: buffer(length)
    integer :: n, i
    n = min(length - 1, len_trim(last_error))
    do i = 1, n
      buffer(i) = last_error(i:i)
    end do
    buffer(n + 1) = c_char_'\0'
    status = 0_c_int
    if (context /= context_id) status = 1_c_int
  end function pycam_vdiff_error_v1

  integer(c_int) function pycam_vdiff_reset_v1(context) bind(C, name='pycam_vdiff_reset_v1') result(status)
    integer(c_int), value, intent(in) :: context
    status = 1_c_int
    if (.not. created .or. context /= context_id) return
    pc = pc_idle
    status = 0_c_int
  end function pycam_vdiff_reset_v1

  integer(c_int) function pycam_vdiff_destroy_v1(context) bind(C, name='pycam_vdiff_destroy_v1') result(status)
    integer(c_int), value, intent(in) :: context
    status = 1_c_int
    if (.not. created .or. context /= context_id) return
    created = .false.
    pc = pc_idle
    status = 0_c_int
  end function pycam_vdiff_destroy_v1

  ! ------------------------------------------------------------------ !
  ! The state machine
  ! ------------------------------------------------------------------ !

  subroutine advance(event)
    integer(c_int), intent(out) :: event
    do
      select case (pc)
      case (pc_chunk_begin)
        if (lchnk > endchunk) then
          pc = pc_idle
          event = ev_done
          return
        end if
        call glue_enter(lchnk)
        pc = pc_if_4
      case (pc_chunk_end)
        lchnk = lchnk + 1
        pc = pc_chunk_begin
      case (pc_glue_piece_4_1)
        call glue_piece_4()
        pc = pc_chunk_end
      case (pc_glue_piece_1_1)
        call glue_piece_1()
        pc = pc_glue_piece_4_1
      case (pc_glue_piece_3_1)
        call glue_piece_3()
        pc = pc_glue_piece_4_1
      case (pc_driver_piece_13_1)
        call driver_piece_13()
        select case (driver_flow)
        case (3)
          driver_flow = 0
          pc = pc_leave_driver_1
        case default
          pc = pc_leave_driver_1
        end select
      case (pc_driver_piece_12_1)
        call driver_piece_12()
        pc = pc_driver_piece_13_1
      case (pc_before_compute_vdiff_1)
        if (replace(3)) then
          token = token + 1_c_int
          pc = pc_at_compute_vdiff_2
          event = ev_needs_kernel
          return
        end if
        call compute_vdiff_2_original()
        pc = pc_after_compute_vdiff_2
      case (pc_at_compute_vdiff_2)
        last_error = 'vdiff is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_compute_vdiff_2)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_12_1
      case (pc_driver_piece_11_1)
        call driver_piece_11()
        pc = pc_before_compute_vdiff_1
      case (pc_if_1)
        if ( any( fieldlist_dry ) ) then
          pc = pc_driver_piece_11_1
        else
          pc = pc_driver_piece_13_1
        end if
      case (pc_driver_piece_10_1)
        call driver_piece_10()
        pc = pc_if_1
      case (pc_driver_piece_9_1)
        call driver_piece_9()
        pc = pc_driver_piece_10_1
      case (pc_before_compute_vdiff_2)
        if (replace(3)) then
          token = token + 1_c_int
          pc = pc_at_compute_vdiff_1
          event = ev_needs_kernel
          return
        end if
        call compute_vdiff_1_original()
        pc = pc_after_compute_vdiff_1
      case (pc_at_compute_vdiff_1)
        last_error = 'vdiff is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_compute_vdiff_1)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_9_1
      case (pc_driver_piece_8_1)
        call driver_piece_8()
        pc = pc_before_compute_vdiff_2
      case (pc_if_2)
        if ( any(fieldlist_wet) ) then
          pc = pc_driver_piece_8_1
        else
          pc = pc_driver_piece_10_1
        end if
      case (pc_driver_piece_7_1)
        call driver_piece_7()
        pc = pc_if_2
      case (pc_driver_piece_6_1)
        call driver_piece_6()
        pc = pc_driver_piece_7_1
      case (pc_before_compute_eddy_diff_1)
        if (replace(2)) then
          token = token + 1_c_int
          pc = pc_at_compute_eddy_diff
          event = ev_needs_kernel
          return
        end if
        call compute_eddy_diff_original()
        pc = pc_after_compute_eddy_diff
      case (pc_at_compute_eddy_diff)
        last_error = 'vdiff is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_compute_eddy_diff)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_6_1
      case (pc_driver_piece_5_1)
        call driver_piece_5()
        pc = pc_before_compute_eddy_diff_1
      case (pc_select_1)
        select case (eddy_scheme)
        case ('diag_TKE')
          pc = pc_driver_piece_5_1
        case default
          last_error = 'vdiff: eddy_scheme takes a case this runner was not written for'
          event = ev_error
          return
        end select
      case (pc_driver_piece_4_1)
        call driver_piece_4()
        pc = pc_select_1
      case (pc_driver_piece_2_1)
        call driver_piece_2()
        pc = pc_driver_piece_4_1
      case (pc_before_compute_tms_1)
        if (replace(1)) then
          token = token + 1_c_int
          pc = pc_at_compute_tms
          event = ev_needs_kernel
          return
        end if
        call compute_tms_original()
        pc = pc_after_compute_tms
      case (pc_at_compute_tms)
        last_error = 'vdiff is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_compute_tms)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_2_1
      case (pc_driver_piece_3_1)
        call driver_piece_3()
        pc = pc_driver_piece_4_1
      case (pc_if_3)
        if ( do_tms ) then
          pc = pc_before_compute_tms_1
        else
          pc = pc_driver_piece_3_1
        end if
      case (pc_driver_piece_1_1)
        call driver_piece_1()
        pc = pc_if_3
      case (pc_leave_driver_1)
        pc = pc_glue_piece_3_1
      case (pc_enter_driver_1)
        call glue_bind_driver()
        pc = pc_driver_piece_1_1
      case (pc_glue_piece_2_1)
        call glue_piece_2()
        pc = pc_enter_driver_1
      case (pc_if_4)
        if (do_clubb_sgs) then
          pc = pc_glue_piece_1_1
        else
          pc = pc_glue_piece_2_1
        end if
      case default
        last_error = 'vdiff program counter is corrupt'
        event = ev_error
        return
      end select
    end do
  end subroutine advance

end module pycam_vdiff_runner
