! Generated by tools/generate_pi_cam_state_copy.py -- do not edit.
!
! physics_state_copy without its allocation: physics_types.F90:1297-1388
! of the pinned source, statement for statement, less the one call that
! allocates state_out.  A handles module calls this when the driver's local
! copy of the state already exists from an earlier call, so the copy's
! storage stays where a Python walk's views of it point.  Memory movement
! only: every statement is an assignment of the live columns.
module pycam_state_copy
  use shr_kind_mod, only: r8 => shr_kind_r8
  use physics_types, only: physics_state
  implicit none
  private
  public :: pycam_state_copy_into

contains

  subroutine pycam_state_copy_into(state_in, state_out)
    use ppgrid,       only: pver, pverp
    use constituents, only: pcnst
    type(physics_state), intent(in)    :: state_in
    type(physics_state), intent(inout) :: state_out
    !
    ! Arguments
    !

    !
    ! Local variables
    !
    integer i, k, m, ncol

    ncol = state_in%ncol

    state_out%psetcols = state_in%psetcols
    state_out%ngrdcol  = state_in%ngrdcol
    state_out%lchnk    = state_in%lchnk
    state_out%ncol     = state_in%ncol
    state_out%count    = state_in%count

    do i = 1, ncol
       state_out%lat(i)    = state_in%lat(i)
       state_out%lon(i)    = state_in%lon(i)
       state_out%ps(i)     = state_in%ps(i)
       state_out%phis(i)   = state_in%phis(i)
       state_out%te_ini(i) = state_in%te_ini(i)
       state_out%te_cur(i) = state_in%te_cur(i)
       state_out%tw_ini(i) = state_in%tw_ini(i)
       state_out%tw_cur(i) = state_in%tw_cur(i)
    end do

    do k = 1, pver
       do i = 1, ncol
          state_out%t(i,k)         = state_in%t(i,k)
          state_out%u(i,k)         = state_in%u(i,k)
          state_out%v(i,k)         = state_in%v(i,k)
          state_out%s(i,k)         = state_in%s(i,k)
          state_out%omega(i,k)     = state_in%omega(i,k)
          state_out%pmid(i,k)      = state_in%pmid(i,k)
          state_out%pdel(i,k)      = state_in%pdel(i,k)
          state_out%rpdel(i,k)     = state_in%rpdel(i,k)
          state_out%lnpmid(i,k)    = state_in%lnpmid(i,k)
          state_out%exner(i,k)     = state_in%exner(i,k)
          state_out%zm(i,k)        = state_in%zm(i,k)
       end do
    end do

    do k = 1, pverp
       do i = 1, ncol
          state_out%pint(i,k)      = state_in%pint(i,k)
          state_out%lnpint(i,k)    = state_in%lnpint(i,k)
          state_out%zi(i,k)        = state_in% zi(i,k)
       end do
    end do

       do i = 1, ncol
          state_out%psdry(i)  = state_in%psdry(i)
       end do
       do k = 1, pver
          do i = 1, ncol
             state_out%lnpmiddry(i,k) = state_in%lnpmiddry(i,k)
             state_out%pmiddry(i,k)   = state_in%pmiddry(i,k)
             state_out%pdeldry(i,k)   = state_in%pdeldry(i,k)
             state_out%rpdeldry(i,k)  = state_in%rpdeldry(i,k)
          end do
       end do
       do k = 1, pverp
          do i = 1, ncol
             state_out%pintdry(i,k)   = state_in%pintdry(i,k)
             state_out%lnpintdry(i,k) = state_in%lnpintdry(i,k)
          end do
       end do

    do m = 1, pcnst
       do k = 1, pver
          do i = 1, ncol
             state_out%q(i,k,m) = state_in%q(i,k,m)
          end do
       end do
    end do

  end subroutine pycam_state_copy_into

end module pycam_state_copy
