! The segment runner for cam_run2.aerosol_dry_deposition_leaf: the original Fortran, pausable at
! modal_aero_depvel_part.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/aerosol_dry_deposition.yaml.  Do not edit by hand; edit the spec.
!
! The runner is a state machine over the units' pieces: start() runs from the
! top of the action for every chunk of this rank and returns either DONE or,
! when a replaced kernel's call is reached, NEEDS_PYTHON_KERNEL with the
! program counter parked before the call; frame() describes the call's
! arguments where they live; resume() continues past the call; original()
! runs the very call on the paused frame.  Python makes every call; Fortran
! never calls Python.
module pycam_adry_runner
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_char, c_null_ptr, c_loc
  use ppgrid, only: begchunk, endchunk
  use pycam_stage_hosts, only: stage_hosts_ok
  use pycam_adry_glue, only: glue_piece_1, glue_piece_2, glue_bind_driver, glue_enter
  use pycam_adry_driver, only: driver_piece_1, driver_piece_2, driver_piece_3, driver_piece_4, driver_piece_5, driver_piece_6, &
       driver_piece_7, modal_aero_depvel_part_1_frame, modal_aero_depvel_part_2_frame, modal_aero_depvel_part_3_frame, modal_aero_depvel_part_4_frame, modal_aero_depvel_part_1_original, &
       modal_aero_depvel_part_2_original, modal_aero_depvel_part_3_original, modal_aero_depvel_part_4_original, lphase, m
  use modal_aero_data, only: ntot_amode
  implicit none
  private

  integer(c_int), parameter :: ev_done = 0_c_int, ev_needs_kernel = 1_c_int, ev_error = 2_c_int
  integer, parameter :: pc_idle = 0
  integer, parameter :: pc_chunk_begin = 1
  integer, parameter :: pc_chunk_end = 2
  integer, parameter :: pc_glue_piece_2_1 = 3
  integer, parameter :: pc_driver_piece_7_1 = 4
  integer, parameter :: pc_driver_piece_6_1 = 5
  integer, parameter :: pc_before_modal_aero_depvel_part_1 = 6
  integer, parameter :: pc_at_modal_aero_depvel_part_4 = 7
  integer, parameter :: pc_after_modal_aero_depvel_part_4 = 8
  integer, parameter :: pc_driver_piece_5_1 = 9
  integer, parameter :: pc_before_modal_aero_depvel_part_2 = 10
  integer, parameter :: pc_at_modal_aero_depvel_part_3 = 11
  integer, parameter :: pc_after_modal_aero_depvel_part_3 = 12
  integer, parameter :: pc_driver_piece_4_1 = 13
  integer, parameter :: pc_if_1 = 14
  integer, parameter :: pc_do_lphase_1_next = 15
  integer, parameter :: pc_do_lphase_1 = 16
  integer, parameter :: pc_do_lphase_init_1 = 17
  integer, parameter :: pc_do_m_1_next = 18
  integer, parameter :: pc_do_m_1 = 19
  integer, parameter :: pc_do_m_init_1 = 20
  integer, parameter :: pc_driver_piece_3_1 = 21
  integer, parameter :: pc_before_modal_aero_depvel_part_3 = 22
  integer, parameter :: pc_at_modal_aero_depvel_part_2 = 23
  integer, parameter :: pc_after_modal_aero_depvel_part_2 = 24
  integer, parameter :: pc_driver_piece_2_1 = 25
  integer, parameter :: pc_before_modal_aero_depvel_part_4 = 26
  integer, parameter :: pc_at_modal_aero_depvel_part_1 = 27
  integer, parameter :: pc_after_modal_aero_depvel_part_1 = 28
  integer, parameter :: pc_driver_piece_1_1 = 29
  integer, parameter :: pc_leave_driver_1 = 30
  integer, parameter :: pc_enter_driver_1 = 31
  integer, parameter :: pc_glue_piece_1_1 = 32
  integer(c_int), parameter :: kernel_modal_aero_depvel_part = 1_c_int
  integer, parameter :: nkernels = 1
  integer, parameter, public :: frame_slots = 13
  integer, parameter :: context_id = 1

  logical, save :: created = .false.
  integer, save :: pc = pc_idle
  integer, save :: lchnk = 0
  integer(c_int), save :: token = 0_c_int, call_index = 0_c_int
  logical, save :: replace(nkernels) = .false.
  character(len=256), save :: last_error = ' '

contains

  ! ------------------------------------------------------------------ !
  ! The ABI Python drives
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_adry_create_v1(context) bind(C, name='pycam_adry_create_v1') result(status)
    integer(c_int), intent(out) :: context
    context = 0_c_int
    status = 1_c_int
    if (created) then
      last_error = 'adry context already exists'; return
    end if
    if (.not. stage_hosts_ok(int(begchunk, c_int))) then
      last_error = 'adry: the stage hosts are not bound (pycam_stagehost_bind_v1 first)'; return
    end if
    status = 2_c_int
    created = .true.
    pc = pc_idle
    context = int(context_id, c_int)
    status = 0_c_int
  end function pycam_adry_create_v1

  integer(c_int) function pycam_adry_start_v1(context, count, mask, event) bind(C, name='pycam_adry_start_v1') result(status)
    integer(c_int), value, intent(in) :: context, count
    integer(c_int), intent(in) :: mask(count)
    integer(c_int), intent(out) :: event
    integer :: k
    event = ev_error
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no adry context'; return
    end if
    if (pc /= pc_idle) then
      last_error = 'adry is not idle; resume or reset it first'; status = 2_c_int; return
    end if
    if (count < nkernels) then
      last_error = 'replacement mask is too short'; status = 3_c_int; return
    end if
    do k = 1, nkernels
      replace(k) = mask(k) /= 0_c_int
    end do
    call_index = 0_c_int
    lchnk = begchunk
    pc = pc_chunk_begin
    call advance(event)
    status = 0_c_int
  end function pycam_adry_start_v1

  integer(c_int) function pycam_adry_resume_v1(context, kernel, token_in, event) bind(C, name='pycam_adry_resume_v1') result(status)
    integer(c_int), value, intent(in) :: context, kernel, token_in
    integer(c_int), intent(out) :: event
    event = ev_error
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no adry context'; return
    end if
    if (token_in /= token) then
      last_error = 'stale resume: the frame token does not match the pause'; status = 4_c_int; return
    end if
    select case (pc)
    case (pc_at_modal_aero_depvel_part_1)
      if (kernel /= kernel_modal_aero_depvel_part) then
        last_error = 'adry is paused on modal_aero_depvel_part, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_modal_aero_depvel_part_1
    case (pc_at_modal_aero_depvel_part_2)
      if (kernel /= kernel_modal_aero_depvel_part) then
        last_error = 'adry is paused on modal_aero_depvel_part, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_modal_aero_depvel_part_2
    case (pc_at_modal_aero_depvel_part_3)
      if (kernel /= kernel_modal_aero_depvel_part) then
        last_error = 'adry is paused on modal_aero_depvel_part, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_modal_aero_depvel_part_3
    case (pc_at_modal_aero_depvel_part_4)
      if (kernel /= kernel_modal_aero_depvel_part) then
        last_error = 'adry is paused on modal_aero_depvel_part, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_modal_aero_depvel_part_4
    case default
      last_error = 'adry is not paused'; status = 2_c_int; return
    end select
    token = token + 1_c_int
    call advance(event)
    status = 0_c_int
  end function pycam_adry_resume_v1

  integer(c_int) function pycam_adry_frame_v1(context, kernel, index_out, lchnk_out, ncol_out, &
       substep_out, token_out, count, ptrs, ndims, shapes, dtypes, intents) bind(C, name='pycam_adry_frame_v1') result(status)
    integer(c_int), value, intent(in) :: context, count
    integer(c_int), intent(out) :: kernel, index_out, lchnk_out, ncol_out, substep_out, token_out
    type(c_ptr), intent(out) :: ptrs(count)
    integer(c_int), intent(out) :: ndims(count), dtypes(count), intents(count)
    integer(c_int64_t), intent(out) :: shapes(5, count)
    kernel = 0_c_int; index_out = 0_c_int; lchnk_out = 0_c_int; ncol_out = 0_c_int
    substep_out = 0_c_int; token_out = 0_c_int
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no adry context'; return
    end if
    if (count < frame_slots) then
      last_error = 'frame table is too short'; status = 3_c_int; return
    end if
    select case (pc)
    case (pc_at_modal_aero_depvel_part_1)
      call modal_aero_depvel_part_1_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_modal_aero_depvel_part
    case (pc_at_modal_aero_depvel_part_2)
      call modal_aero_depvel_part_2_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_modal_aero_depvel_part
    case (pc_at_modal_aero_depvel_part_3)
      call modal_aero_depvel_part_3_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_modal_aero_depvel_part
    case (pc_at_modal_aero_depvel_part_4)
      call modal_aero_depvel_part_4_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_modal_aero_depvel_part
    case default
      last_error = 'adry is not paused; there is no frame'; status = 2_c_int; return
    end select
    index_out = call_index
    lchnk_out = int(lchnk, c_int)
    substep_out = 1_c_int
    token_out = token
    status = 0_c_int
  end function pycam_adry_frame_v1

  integer(c_int) function pycam_adry_original_v1(context, kernel) bind(C, name='pycam_adry_original_v1') result(status)
    ! Run the original call on the paused frame: the validation gate's
    ! replacement, exercising the pause, the frame and the resume.
    integer(c_int), value, intent(in) :: context, kernel
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no adry context'; return
    end if
    select case (pc)
    case (pc_at_modal_aero_depvel_part_1)
      if (kernel /= kernel_modal_aero_depvel_part) then
        last_error = 'adry is paused on modal_aero_depvel_part, not on the kernel asked for'; status = 3_c_int; return
      end if
      call modal_aero_depvel_part_1_original()
    case (pc_at_modal_aero_depvel_part_2)
      if (kernel /= kernel_modal_aero_depvel_part) then
        last_error = 'adry is paused on modal_aero_depvel_part, not on the kernel asked for'; status = 3_c_int; return
      end if
      call modal_aero_depvel_part_2_original()
    case (pc_at_modal_aero_depvel_part_3)
      if (kernel /= kernel_modal_aero_depvel_part) then
        last_error = 'adry is paused on modal_aero_depvel_part, not on the kernel asked for'; status = 3_c_int; return
      end if
      call modal_aero_depvel_part_3_original()
    case (pc_at_modal_aero_depvel_part_4)
      if (kernel /= kernel_modal_aero_depvel_part) then
        last_error = 'adry is paused on modal_aero_depvel_part, not on the kernel asked for'; status = 3_c_int; return
      end if
      call modal_aero_depvel_part_4_original()
    case default
      last_error = 'adry is not paused; there is nothing to run'; status = 2_c_int; return
    end select
    status = 0_c_int
  end function pycam_adry_original_v1

  integer(c_int) function pycam_adry_error_v1(context, buffer, length) bind(C, name='pycam_adry_error_v1') result(status)
    integer(c_int), value, intent(in) :: context, length
    character(kind=c_char), intent(out) :: buffer(length)
    integer :: n, i
    n = min(length - 1, len_trim(last_error))
    do i = 1, n
      buffer(i) = last_error(i:i)
    end do
    buffer(n + 1) = c_char_'\0'
    status = 0_c_int
    if (context /= context_id) status = 1_c_int
  end function pycam_adry_error_v1

  integer(c_int) function pycam_adry_reset_v1(context) bind(C, name='pycam_adry_reset_v1') result(status)
    integer(c_int), value, intent(in) :: context
    status = 1_c_int
    if (.not. created .or. context /= context_id) return
    pc = pc_idle
    status = 0_c_int
  end function pycam_adry_reset_v1

  integer(c_int) function pycam_adry_destroy_v1(context) bind(C, name='pycam_adry_destroy_v1') result(status)
    integer(c_int), value, intent(in) :: context
    status = 1_c_int
    if (.not. created .or. context /= context_id) return
    created = .false.
    pc = pc_idle
    status = 0_c_int
  end function pycam_adry_destroy_v1

  ! ------------------------------------------------------------------ !
  ! The state machine
  ! ------------------------------------------------------------------ !

  subroutine advance(event)
    integer(c_int), intent(out) :: event
    do
      select case (pc)
      case (pc_chunk_begin)
        if (lchnk > endchunk) then
          pc = pc_idle
          event = ev_done
          return
        end if
        call glue_enter(lchnk)
        pc = pc_glue_piece_1_1
      case (pc_chunk_end)
        lchnk = lchnk + 1
        pc = pc_chunk_begin
      case (pc_glue_piece_2_1)
        call glue_piece_2()
        pc = pc_chunk_end
      case (pc_driver_piece_7_1)
        call driver_piece_7()
        pc = pc_leave_driver_1
      case (pc_driver_piece_6_1)
        call driver_piece_6()
        pc = pc_do_lphase_1_next
      case (pc_before_modal_aero_depvel_part_1)
        if (replace(1)) then
          token = token + 1_c_int
          pc = pc_at_modal_aero_depvel_part_4
          event = ev_needs_kernel
          return
        end if
        call modal_aero_depvel_part_4_original()
        pc = pc_after_modal_aero_depvel_part_4
      case (pc_at_modal_aero_depvel_part_4)
        last_error = 'adry is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_modal_aero_depvel_part_4)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_6_1
      case (pc_driver_piece_5_1)
        call driver_piece_5()
        pc = pc_before_modal_aero_depvel_part_1
      case (pc_before_modal_aero_depvel_part_2)
        if (replace(1)) then
          token = token + 1_c_int
          pc = pc_at_modal_aero_depvel_part_3
          event = ev_needs_kernel
          return
        end if
        call modal_aero_depvel_part_3_original()
        pc = pc_after_modal_aero_depvel_part_3
      case (pc_at_modal_aero_depvel_part_3)
        last_error = 'adry is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_modal_aero_depvel_part_3)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_5_1
      case (pc_driver_piece_4_1)
        call driver_piece_4()
        pc = pc_before_modal_aero_depvel_part_2
      case (pc_if_1)
        if (lphase == 1) then
          pc = pc_driver_piece_4_1
        else
          pc = pc_driver_piece_6_1
        end if
      case (pc_do_lphase_1_next)
        lphase = lphase + (1)
        pc = pc_do_lphase_1
      case (pc_do_lphase_1)
        if (lphase > 2) then
          pc = pc_do_m_1_next
        else
          pc = pc_if_1
        end if
      case (pc_do_lphase_init_1)
        lphase = 1
        pc = pc_do_lphase_1
      case (pc_do_m_1_next)
        m = m + (1)
        pc = pc_do_m_1
      case (pc_do_m_1)
        if (m > ntot_amode) then
          pc = pc_driver_piece_7_1
        else
          pc = pc_do_lphase_init_1
        end if
      case (pc_do_m_init_1)
        m = 1
        pc = pc_do_m_1
      case (pc_driver_piece_3_1)
        call driver_piece_3()
        pc = pc_do_m_init_1
      case (pc_before_modal_aero_depvel_part_3)
        if (replace(1)) then
          token = token + 1_c_int
          pc = pc_at_modal_aero_depvel_part_2
          event = ev_needs_kernel
          return
        end if
        call modal_aero_depvel_part_2_original()
        pc = pc_after_modal_aero_depvel_part_2
      case (pc_at_modal_aero_depvel_part_2)
        last_error = 'adry is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_modal_aero_depvel_part_2)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_3_1
      case (pc_driver_piece_2_1)
        call driver_piece_2()
        pc = pc_before_modal_aero_depvel_part_3
      case (pc_before_modal_aero_depvel_part_4)
        if (replace(1)) then
          token = token + 1_c_int
          pc = pc_at_modal_aero_depvel_part_1
          event = ev_needs_kernel
          return
        end if
        call modal_aero_depvel_part_1_original()
        pc = pc_after_modal_aero_depvel_part_1
      case (pc_at_modal_aero_depvel_part_1)
        last_error = 'adry is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_modal_aero_depvel_part_1)
        call_index = call_index + 1_c_int
        pc = pc_driver_piece_2_1
      case (pc_driver_piece_1_1)
        call driver_piece_1()
        pc = pc_before_modal_aero_depvel_part_4
      case (pc_leave_driver_1)
        pc = pc_glue_piece_2_1
      case (pc_enter_driver_1)
        call glue_bind_driver()
        pc = pc_driver_piece_1_1
      case (pc_glue_piece_1_1)
        call glue_piece_1()
        pc = pc_enter_driver_1
      case default
        last_error = 'adry program counter is corrupt'
        event = ev_error
        return
      end select
    end do
  end subroutine advance

end module pycam_adry_runner
