! tphysbc (physpkg.F90:2472-2476) hoisted for the
! radt segment runner: its locals as module state, its body in pieces the
! runner calls in the source's order, its dummies bound by the caller.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/radiation.yaml.  Do not edit by hand; edit the spec.
module pycam_radt_glue
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_loc, c_null_ptr, c_f_pointer
  use shr_kind_mod, only: r8 => shr_kind_r8
  use pycam_stage_hosts, only: host_state, host_tend, host_pbuf2d, host_cam_in, host_cam_out
  use physics_buffer, only: pbuf_get_chunk
  use time_manager, only: get_nstep, get_step_size
  use spmd_utils, only: masterproc
  use physconst, only: latvap, latice, rh2o
  use physics_types, only: physics_state, physics_tend, physics_state_set_grid, physics_ptend, physics_tend_init, physics_update, physics_type_alloc, physics_ptend_dealloc, physics_state_alloc, physics_state_dealloc, physics_tend_alloc, physics_tend_dealloc
  use phys_grid, only: get_ncols_p
  use phys_gmean, only: gmean_mass
  use ppgrid, only: begchunk, endchunk, pcols, pver, pverp, psubcols
  use constituents, only: pcnst, cnst_name, cnst_get_ind
  use camsrfexch, only: cam_out_t, cam_in_t
  use cam_control_mod, only: ideal_phys, adiabatic
  use phys_control, only: phys_do_flux_avg, phys_getopts, waccmx_is
  use scamMod, only: single_column, scm_crm_mode
  use flux_avg, only: flux_avg_init
  use infnan, only: posinf, assignment(=)
  use mpishorthand
  use perf_mod
  use cam_logfile, only: iulog
  use camsrfexch, only: cam_export
  use modal_aero_calcsize, only: modal_aero_calcsize_init, modal_aero_calcsize_diag, modal_aero_calcsize_reg
  use modal_aero_wateruptake, only: modal_aero_wateruptake_init, modal_aero_wateruptake_dr, modal_aero_wateruptake_reg
  use physics_buffer, only : physics_buffer_desc, pbuf_get_field
  use physics_buffer, only : pbuf_get_index, pbuf_old_tim_idx
  use physics_buffer, only : col_type_subcol, dyn_time_lvls
  use stratiform, only: stratiform_tend
  use microp_driver, only: microp_driver_tend
  use microp_aero, only: microp_aero_run
  use macrop_driver, only: macrop_driver_tend
  use physics_types, only: physics_state, physics_tend, physics_ptend, physics_update, physics_ptend_init, physics_ptend_sum, physics_state_check, physics_ptend_scale
  use cam_diagnostics, only: diag_conv_tend_ini, diag_phys_writeout, diag_conv, diag_export, diag_state_b4_phys_write
  use cam_history, only: outfld
  use physconst, only: cpair, latvap
  use constituents, only: pcnst, qmin, cnst_get_ind
  use convect_deep, only: convect_deep_tend, convect_deep_tend_2, deep_scheme_does_scav_trans
  use time_manager, only: is_first_step, get_nstep
  use convect_shallow, only: convect_shallow_tend
  use check_energy, only: check_energy_chng, check_energy_fix, check_energy_timestep_init
  use check_energy, only: check_tracers_data, check_tracers_init, check_tracers_chng
  use dycore, only: dycore_is
  use aero_model, only: aero_model_wetdep
  use carma_intr, only: carma_wetdep_tend, carma_timestep_tend
  use carma_flags_mod, only: carma_do_detrain, carma_do_cldice, carma_do_cldliq, carma_do_wetdep
  use radiation, only: radiation_tend
  use cloud_diagnostics, only: cloud_diagnostics_calc
  use mo_gas_phase_chemdr,only: map2chm
  use clybry_fam, only: clybry_fam_adj
  use clubb_intr, only: clubb_tend_cam
  use sslt_rebin, only: sslt_rebin_adv
  use tropopause, only: tropopause_output
  use cam_abortutils, only: endrun
  use subcol, only: subcol_gen, subcol_ptend_avg
  use subcol_utils, only: subcol_ptend_copy, is_subcol_on
  use water_tracer_vars, only: trace_water, wtrc_iatype, wtrc_bulk_indices, wtrc_nwset, iwspec, wisotope
  use water_tracers, only: wtrc_check_h2o, wtrc_ratio, wtrc_get_rstd, wtrc_is_tagged, wtrc_mass_fixer
  use water_types, only: pwtype, iwtvap, iwtliq, iwtice
  use comsrf, only: comsrf_fsns => fsns, comsrf_fsnt => fsnt, comsrf_flns => flns, comsrf_flnt => flnt, comsrf_fsds => fsds
  use pycam_rad_handles, only: rad_ptend, rad_net_flx
  use pycam_radt_driver, only: driver_bind
  implicit none
  private
  public :: glue_enter, glue_bind_driver

  integer(c_int64_t), parameter :: zero_shape(1) = (/ 0_c_int64_t /)

  ! the routine's dummies, bound by the caller
  real(r8), save, public :: ztodt
  real(r8), pointer, save, public :: fsns(:) => null()
  real(r8), pointer, save, public :: fsnt(:) => null()
  real(r8), pointer, save, public :: flns(:) => null()
  real(r8), pointer, save, public :: flnt(:) => null()
  type(physics_state), pointer, save, public :: state => null()
  type(physics_tend), pointer, save, public :: tend => null()
  type(physics_buffer_desc), pointer, save, public :: pbuf(:) => null()
  real(r8), pointer, save, public :: fsds(:) => null()
  real(r8), pointer, save, public :: landm(:) => null()
  real(r8), pointer, save, public :: sgh30(:) => null()
  type(cam_out_t), pointer, save, public :: cam_out => null()
  type(cam_in_t), pointer, save, public :: cam_in => null()

  ! locals pointed at storage the stage's Python side reads back
  real(r8), pointer, save, public :: net_flx(:) => null()
  type(physics_ptend), pointer, save, public :: ptend => null()

  ! the routine's locals, held for the chunk in flight
  integer, save, target, public :: lchnk
  integer, save, target, public :: ncol

contains

  subroutine glue_enter(lchnk_in)
    ! tphysbc's dummies for this chunk, its carries as views, and the entry
    ! statements every stage relies on (lchnk, ncol, nstep, ...)
    integer, intent(in) :: lchnk_in
    type(c_ptr) :: address
    integer(c_int) :: ndims, status
    integer(c_int64_t) :: extents(4)
    call glue_view(comsrf_fsns(:, lchnk_in), address)
    call c_f_pointer(address, fsns, (/ pcols /))
    call glue_view(comsrf_fsnt(:, lchnk_in), address)
    call c_f_pointer(address, fsnt, (/ pcols /))
    call glue_view(comsrf_flns(:, lchnk_in), address)
    call c_f_pointer(address, flns, (/ pcols /))
    call glue_view(comsrf_flnt(:, lchnk_in), address)
    call c_f_pointer(address, flnt, (/ pcols /))
    state => host_state(lchnk_in)
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk_in)
    call glue_view(comsrf_fsds(:, lchnk_in), address)
    call c_f_pointer(address, fsds, (/ pcols /))
    cam_out => host_cam_out(lchnk_in)
    cam_in => host_cam_in(lchnk_in)
    net_flx => rad_net_flx(:, lchnk_in)
    ptend => rad_ptend(lchnk_in)
    lchnk = state%lchnk
    ncol = state%ncol
  end subroutine glue_enter

  subroutine glue_bind_driver()
    ! physpkg.F90:2472-2476: the call's actuals bound to the unit's dummies
    call driver_bind(state,ptend, pbuf, cam_out, cam_in, cam_in%landfrac, cam_in%icefrac, cam_in%snowhland, fsns, fsnt, flns, flnt, fsds, net_flx)
  end subroutine glue_bind_driver

  subroutine glue_view(field, address)
    ! a TARGET dummy so c_loc is legal whatever the actual argument's attributes;
    ! a contiguous actual is passed without a copy
    real(r8), intent(inout), target :: field(*)
    type(c_ptr), intent(out) :: address
    address = c_loc(field(1))
  end subroutine glue_view

  subroutine put_slot(index, address, rank, shape, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(in) :: address
    integer(c_int64_t), intent(in) :: shape(:)
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer :: axis
    ptrs(index) = address
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    do axis = 1, rank
      shapes(axis, index) = shape(axis)
    end do
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine put_slot

  subroutine empty_slot(index, rank, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    ! an argument with no storage in this call: a null address and zero extents
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    ptrs(index) = c_null_ptr
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine empty_slot

end module pycam_radt_glue
