! micro_mg_cam_tend's inline arithmetic, as routines the image can be asked
! to run.
!
! GENERATED by tools/generate_pi_cam_micro_kernels.py from the pinned source
! micro_mg_cam.F90.  Do not edit by hand; edit the generator.
!
! Each body below is the original text with names substituted, never
! rewritten: `state_loc%q` becomes `q_loc`, `state%pdel` becomes `pdel`.
! Every expression, every loop nest and every bound is character for
! character what the pinned source computes, which is what lets the
! bit-for-bit gate mean something.  The elemental size-distribution and
! diameter routines the driver calls inline are called inline here too, from
! the same module, with the same property objects.
!
! This module is an addition to the source tree.  micro_mg_cam_tend is not
! changed to call it, so the oracle's own micro_mg_cam.o -- the machine code
! the gate validated -- stays untouched; only a Python-driven timestep runs
! these.

module pycam_micro_kernels

  use shr_kind_mod,   only: r8 => shr_kind_r8
  use ppgrid,         only: pcols, pver, pverp
  use constituents,   only: pcnst
  use micro_mg_utils, only: size_dist_param_basic, size_dist_param_liq, &
       mg_liq_props, mg_ice_props, avg_diameter, rhoi, rhosn, rhow, rhows

  implicit none
  private

  real(r8), parameter :: dcon   = 25.e-6_r8
  real(r8), parameter :: mucon  = 5.3_r8
  real(r8), parameter :: deicon = 50._r8

  public :: micro_initial_water_paths
  public :: micro_precip_diagnostics
  public :: micro_macro_feedback
  public :: micro_in_cloud_quantities
  public :: micro_split_signs
  public :: micro_air_density
  public :: micro_liquid_size
  public :: micro_ice_and_precip_size
  public :: micro_precip_efficiency
  public :: micro_autoconversion_ratio
  public :: micro_effective_outputs
  public :: micro_history_tendencies

contains

  subroutine micro_initial_water_paths( &
         ncol, top_lev, ixcldliq, ixcldice, mincld, gravit, q, ast, pdel, &
         iclwpi, iciwpi)

   integer,  intent(in) :: ncol
   integer,  intent(in) :: top_lev
   integer,  intent(in) :: ixcldliq
   integer,  intent(in) :: ixcldice
   real(r8), intent(in) :: mincld
   real(r8), intent(in) :: gravit
   real(r8), intent(in) :: q(pcols,pver,pcnst)
   real(r8), intent(in) :: ast(pcols,pver)
   real(r8), intent(in) :: pdel(pcols,pver)
   real(r8), intent(inout) :: iclwpi(pcols)
   real(r8), intent(inout) :: iciwpi(pcols)

   integer :: i, k

      iclwpi = 0._r8
      iciwpi = 0._r8

      do i = 1, ncol
         do k = top_lev, pver
            iclwpi(i) = iclwpi(i) + &
                 min(q(i,k,ixcldliq) / max(mincld,ast(i,k)),0.005_r8) &
                 * pdel(i,k) / gravit
            iciwpi(i) = iciwpi(i) + &
                 min(q(i,k,ixcldice) / max(mincld,ast(i,k)),0.005_r8) &
                 * pdel(i,k) / gravit
         end do
      end do

  end subroutine micro_initial_water_paths

  subroutine micro_precip_diagnostics( &
         ncol, top_lev, naai, naai_hom, mnuccdo, qrout, qsout, rflx, sflx, &
         mnuccdohet, mgmrprc, mgmrsnw, mgflxprc, mgflxsnw)

   integer,  intent(in) :: ncol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: naai(pcols,pver)
   real(r8), intent(in) :: naai_hom(pcols,pver)
   real(r8), intent(in) :: mnuccdo(pcols,pver)
   real(r8), intent(in) :: qrout(pcols,pver)
   real(r8), intent(in) :: qsout(pcols,pver)
   real(r8), intent(in) :: rflx(pcols,pverp)
   real(r8), intent(in) :: sflx(pcols,pverp)
   real(r8), intent(inout) :: mnuccdohet(pcols,pver)
   real(r8), intent(inout) :: mgmrprc(pcols,pver)
   real(r8), intent(inout) :: mgmrsnw(pcols,pver)
   real(r8), intent(inout) :: mgflxprc(pcols,pverp)
   real(r8), intent(inout) :: mgflxsnw(pcols,pverp)

   integer :: i, k

      mnuccdohet = 0._r8
      do k=top_lev,pver
         do i=1,ncol
            if (naai(i,k) > 0._r8) then
               mnuccdohet(i,k) = mnuccdo(i,k) - (naai_hom(i,k)/naai(i,k))*mnuccdo(i,k)
            end if
         end do
      end do

      mgflxprc(:ncol,top_lev:pverp) = rflx(:ncol,top_lev:pverp) + sflx(:ncol,top_lev:pverp)
      mgflxsnw(:ncol,top_lev:pverp) = sflx(:ncol,top_lev:pverp)

      mgmrprc(:ncol,top_lev:pver) = qrout(:ncol,top_lev:pver) + qsout(:ncol,top_lev:pver)
      mgmrsnw(:ncol,top_lev:pver) = qsout(:ncol,top_lev:pver)

  end subroutine micro_precip_diagnostics

  subroutine micro_macro_feedback( &
         ncol, top_lev, cpair, vtrmc, tlat, qvlat, qcten, qiten, ncten, &
         niten, alst_mic, cmeliq, cmeiout, ast, prect, preci, wsedl, cc_t, &
         cc_qv, cc_ql, cc_qi, cc_nl, cc_ni, cc_qlst, qme, icecldf, liqcldf, &
         prec_pcw, snow_pcw, prec_sed, snow_sed, prec_str, snow_str)

   integer,  intent(in) :: ncol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: cpair
   real(r8), intent(in) :: vtrmc(pcols,pver)
   real(r8), intent(in) :: tlat(pcols,pver)
   real(r8), intent(in) :: qvlat(pcols,pver)
   real(r8), intent(in) :: qcten(pcols,pver)
   real(r8), intent(in) :: qiten(pcols,pver)
   real(r8), intent(in) :: ncten(pcols,pver)
   real(r8), intent(in) :: niten(pcols,pver)
   real(r8), intent(in) :: alst_mic(pcols,pver)
   real(r8), intent(in) :: cmeliq(pcols,pver)
   real(r8), intent(in) :: cmeiout(pcols,pver)
   real(r8), intent(in) :: ast(pcols,pver)
   real(r8), intent(in) :: prect(pcols)
   real(r8), intent(in) :: preci(pcols)
   real(r8), intent(inout) :: wsedl(pcols,pver)
   real(r8), intent(inout) :: cc_t(pcols,pver)
   real(r8), intent(inout) :: cc_qv(pcols,pver)
   real(r8), intent(inout) :: cc_ql(pcols,pver)
   real(r8), intent(inout) :: cc_qi(pcols,pver)
   real(r8), intent(inout) :: cc_nl(pcols,pver)
   real(r8), intent(inout) :: cc_ni(pcols,pver)
   real(r8), intent(inout) :: cc_qlst(pcols,pver)
   real(r8), intent(inout) :: qme(pcols,pver)
   real(r8), intent(inout) :: icecldf(pcols,pver)
   real(r8), intent(inout) :: liqcldf(pcols,pver)
   real(r8), intent(inout) :: prec_pcw(pcols)
   real(r8), intent(inout) :: snow_pcw(pcols)
   real(r8), intent(inout) :: prec_sed(pcols)
   real(r8), intent(inout) :: snow_sed(pcols)
   real(r8), intent(inout) :: prec_str(pcols)
   real(r8), intent(inout) :: snow_str(pcols)

      wsedl(:ncol,top_lev:pver) = vtrmc(:ncol,top_lev:pver)

      ! Microphysical tendencies for use in the macrophysics at the next time step
      CC_T(:ncol,top_lev:pver)    =  tlat(:ncol,top_lev:pver)/cpair
      CC_qv(:ncol,top_lev:pver)   = qvlat(:ncol,top_lev:pver)
      CC_ql(:ncol,top_lev:pver)   = qcten(:ncol,top_lev:pver)
      CC_qi(:ncol,top_lev:pver)   = qiten(:ncol,top_lev:pver)
      CC_nl(:ncol,top_lev:pver)   = ncten(:ncol,top_lev:pver)
      CC_ni(:ncol,top_lev:pver)   = niten(:ncol,top_lev:pver)
      CC_qlst(:ncol,top_lev:pver) = qcten(:ncol,top_lev:pver)/max(0.01_r8,alst_mic(:ncol,top_lev:pver))

      ! Net micro_mg_cam condensation rate
      qme(:ncol,top_lev:pver) = cmeliq(:ncol,top_lev:pver) + cmeiout(:ncol,top_lev:pver)

      ! For precip, accumulate only total precip in prec_pcw and snow_pcw variables.
      ! Other precip output variables are set to 0
      ! Do not subscript by ncol here, because in physpkg we divide the whole
      ! array and need to avoid an FPE due to uninitialized data.
      prec_pcw = prect
      snow_pcw = preci
      prec_sed = 0._r8
      snow_sed = 0._r8
      prec_str = prec_pcw + prec_sed
      snow_str = snow_pcw + snow_sed

      icecldf(:ncol,top_lev:pver) = ast(:ncol,top_lev:pver)
      liqcldf(:ncol,top_lev:pver) = ast(:ncol,top_lev:pver)

  end subroutine micro_macro_feedback

  subroutine micro_in_cloud_quantities( &
         ncol, top_lev, ixcldliq, ixcldice, ixnumliq, ixnumice, mincld, &
         gravit, q_loc, pmid_loc, t_loc, pdel_loc, icecldf, liqcldf, ast, &
         cld, concld, qsout, icimrst, icwmrst, icinc, icwnc, iciwpst, &
         iclwpst, cldfsnow, icswp)

   integer,  intent(in) :: ncol
   integer,  intent(in) :: top_lev
   integer,  intent(in) :: ixcldliq
   integer,  intent(in) :: ixcldice
   integer,  intent(in) :: ixnumliq
   integer,  intent(in) :: ixnumice
   real(r8), intent(in) :: mincld
   real(r8), intent(in) :: gravit
   real(r8), intent(in) :: q_loc(pcols,pver,pcnst)
   real(r8), intent(in) :: pmid_loc(pcols,pver)
   real(r8), intent(in) :: t_loc(pcols,pver)
   real(r8), intent(in) :: pdel_loc(pcols,pver)
   real(r8), intent(in) :: icecldf(pcols,pver)
   real(r8), intent(in) :: liqcldf(pcols,pver)
   real(r8), intent(in) :: ast(pcols,pver)
   real(r8), intent(in) :: cld(pcols,pver)
   real(r8), intent(in) :: concld(pcols,pver)
   real(r8), intent(in) :: qsout(pcols,pver)
   real(r8), intent(inout) :: icimrst(pcols,pver)
   real(r8), intent(inout) :: icwmrst(pcols,pver)
   real(r8), intent(inout) :: icinc(pcols,pver)
   real(r8), intent(inout) :: icwnc(pcols,pver)
   real(r8), intent(inout) :: iciwpst(pcols,pver)
   real(r8), intent(inout) :: iclwpst(pcols,pver)
   real(r8), intent(inout) :: cldfsnow(pcols,pver)
   real(r8), intent(inout) :: icswp(pcols,pver)

   integer :: i, k

      do k = top_lev, pver
         do i = 1, ncol
            ! Limits for in-cloud mixing ratios consistent with MG microphysics
            ! in-cloud mixing ratio maximum limit of 0.005 kg/kg
            icimrst(i,k)   = min( q_loc(i,k,ixcldice) / max(mincld,icecldf(i,k)),0.005_r8 )
            icwmrst(i,k)   = min( q_loc(i,k,ixcldliq) / max(mincld,liqcldf(i,k)),0.005_r8 )
            icinc(i,k)     = q_loc(i,k,ixnumice) / max(mincld,icecldf(i,k)) * &
                 pmid_loc(i,k) / (287.15_r8*t_loc(i,k))
            icwnc(i,k)     = q_loc(i,k,ixnumliq) / max(mincld,liqcldf(i,k)) * &
                 pmid_loc(i,k) / (287.15_r8*t_loc(i,k))
            ! Calculate micro_mg_cam cloud water paths in each layer
            ! Note: uses stratiform cloud fraction!
            iciwpst(i,k)   = min(q_loc(i,k,ixcldice)/max(mincld,ast(i,k)),0.005_r8) * pdel_loc(i,k) / gravit
            iclwpst(i,k)   = min(q_loc(i,k,ixcldliq)/max(mincld,ast(i,k)),0.005_r8) * pdel_loc(i,k) / gravit

            ! ------------------------------ !
            ! Adjust cloud fraction for snow !
            ! ------------------------------ !
            cldfsnow(i,k) = cld(i,k)
            ! If cloud and only ice ( no convective cloud or ice ), then set to 0.
            if( ( cldfsnow(i,k) .gt. 1.e-4_r8 ) .and. &
               ( concld(i,k)   .lt. 1.e-4_r8 ) .and. &
               ( q_loc(i,k,ixcldliq) .lt. 1.e-10_r8 ) ) then
               cldfsnow(i,k) = 0._r8
            end if
            ! If no cloud and snow, then set to 0.25
            if( ( cldfsnow(i,k) .le. 1.e-4_r8 ) .and. ( qsout(i,k) .gt. 1.e-6_r8 ) ) then
               cldfsnow(i,k) = 0.25_r8
            end if
            ! Calculate in-cloud snow water path
            icswp(i,k) = qsout(i,k) / max( mincld, cldfsnow(i,k) ) * pdel_loc(i,k) / gravit
         end do
      end do

  end subroutine micro_in_cloud_quantities

  subroutine micro_split_signs( &
         ncol, top_lev, cmeiout_grid, meltso, meltso_grid, pcmei_grid, &
         ncmei_grid, pmelts_grid, nmelts_grid)

   integer,  intent(in) :: ncol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: cmeiout_grid(pcols,pver)
   real(r8), intent(in) :: meltso(pcols,pver)
   real(r8), intent(in) :: meltso_grid(pcols,pver)
   real(r8), intent(inout) :: pcmei_grid(pcols,pver)
   real(r8), intent(inout) :: ncmei_grid(pcols,pver)
   real(r8), intent(inout) :: pmelts_grid(pcols,pver)
   real(r8), intent(inout) :: nmelts_grid(pcols,pver)

   integer :: i, k

            pcmei_grid(:,top_lev:) = 0._r8
            ncmei_grid(:,top_lev:) = 0._r8
            pmelts_grid(:,top_lev:) = 0._r8
            nmelts_grid(:,top_lev:) = 0._r8

            !split into positive and negative tendencies - JN
            do i=1,ncol
              do k=top_lev,pver
                if(cmeiout_grid(i,k) .lt. 0._r8) then
                  ncmei_grid(i,k) = cmeiout_grid(i,k) !sublimation (ice-dependent)
                else
                  pcmei_grid(i,k) = cmeiout_grid(i,k) !deposition (vapor-dependent)
                end if
                if(meltso(i,k) .lt. 0._r8) then
                  nmelts_grid(i,k) = meltso_grid(i,k)
                else
                  pmelts_grid(i,k) = meltso_grid(i,k)
                end if
              end do
            end do

  end subroutine micro_split_signs

  subroutine micro_air_density( &
         ncol, top_lev, rair, pmid, t, rho)

   integer,  intent(in) :: ncol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: rair
   real(r8), intent(in) :: pmid(pcols,pver)
   real(r8), intent(in) :: t(pcols,pver)
   real(r8), intent(inout) :: rho(pcols,pver)

      rho(:ncol,top_lev:) = pmid(:ncol,top_lev:) / &
           (rair*t(:ncol,top_lev:))

  end subroutine micro_air_density

  subroutine micro_liquid_size( &
         ngrdcol, top_lev, mincld, qsmall, icwmrst_grid, rho_grid, nc_grid, &
         liqcldf_grid, mu_grid, lambdac_grid, rel_fn_grid, ncic_grid, &
         rel_grid)

   integer,  intent(in) :: ngrdcol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: mincld
   real(r8), intent(in) :: qsmall
   real(r8), intent(in) :: icwmrst_grid(pcols,pver)
   real(r8), intent(in) :: rho_grid(pcols,pver)
   real(r8), intent(in) :: nc_grid(pcols,pver)
   real(r8), intent(in) :: liqcldf_grid(pcols,pver)
   real(r8), intent(inout) :: mu_grid(pcols,pver)
   real(r8), intent(inout) :: lambdac_grid(pcols,pver)
   real(r8), intent(inout) :: rel_fn_grid(pcols,pver)
   real(r8), intent(inout) :: ncic_grid(pcols,pver)
   real(r8), intent(inout) :: rel_grid(pcols,pver)

      mu_grid = 0._r8
      lambdac_grid = 0._r8
      rel_fn_grid = 10._r8

      ncic_grid = 1.e8_r8

      call size_dist_param_liq(mg_liq_props, icwmrst_grid(:ngrdcol,top_lev:), &
           ncic_grid(:ngrdcol,top_lev:), rho_grid(:ngrdcol,top_lev:), &
           mu_grid(:ngrdcol,top_lev:), lambdac_grid(:ngrdcol,top_lev:))

      where (icwmrst_grid(:ngrdcol,top_lev:) > qsmall)
         rel_fn_grid(:ngrdcol,top_lev:) = &
              (mu_grid(:ngrdcol,top_lev:) + 3._r8)/ &
              lambdac_grid(:ngrdcol,top_lev:)/2._r8 * 1.e6_r8
      end where

      ! Effective radius for cloud liquid, and size parameters
      ! mu_grid and lambdac_grid.
      mu_grid = 0._r8
      lambdac_grid = 0._r8
      rel_grid = 10._r8

      ! Calculate ncic on the grid
      ncic_grid(:ngrdcol,top_lev:) = nc_grid(:ngrdcol,top_lev:) / &
           max(mincld,liqcldf_grid(:ngrdcol,top_lev:))

      call size_dist_param_liq(mg_liq_props, icwmrst_grid(:ngrdcol,top_lev:), &
           ncic_grid(:ngrdcol,top_lev:), rho_grid(:ngrdcol,top_lev:), &
           mu_grid(:ngrdcol,top_lev:), lambdac_grid(:ngrdcol,top_lev:))

      where (icwmrst_grid(:ngrdcol,top_lev:) >= qsmall)
         rel_grid(:ngrdcol,top_lev:) = &
              (mu_grid(:ngrdcol,top_lev:) + 3._r8) / &
              lambdac_grid(:ngrdcol,top_lev:)/2._r8 * 1.e6_r8
      elsewhere
         ! Deal with the fact that size_dist_param_liq sets mu_grid to -100
         ! wherever there is no cloud.
         mu_grid(:ngrdcol,top_lev:) = 0._r8
      end where

  end subroutine micro_liquid_size

  subroutine micro_ice_and_precip_size( &
         ngrdcol, top_lev, mincld, qsmall, qrout_grid, nrout_grid, &
         qsout_grid, nsout_grid, rho_grid, ni_grid, icecldf_grid, &
         icimrst_grid, ast_grid, drout2_grid, reff_rain_grid, des_grid, &
         dsout2_grid, reff_snow_grid, rei_grid, niic_grid, dei_grid, mu_grid, &
         lambdac_grid, mgreffrain_grid, mgreffsnow_grid)

   integer,  intent(in) :: ngrdcol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: mincld
   real(r8), intent(in) :: qsmall
   real(r8), intent(in) :: qrout_grid(pcols,pver)
   real(r8), intent(in) :: nrout_grid(pcols,pver)
   real(r8), intent(in) :: qsout_grid(pcols,pver)
   real(r8), intent(in) :: nsout_grid(pcols,pver)
   real(r8), intent(in) :: rho_grid(pcols,pver)
   real(r8), intent(in) :: ni_grid(pcols,pver)
   real(r8), intent(in) :: icecldf_grid(pcols,pver)
   real(r8), intent(in) :: icimrst_grid(pcols,pver)
   real(r8), intent(in) :: ast_grid(pcols,pver)
   real(r8), intent(inout) :: drout2_grid(pcols,pver)
   real(r8), intent(inout) :: reff_rain_grid(pcols,pver)
   real(r8), intent(inout) :: des_grid(pcols,pver)
   real(r8), intent(inout) :: dsout2_grid(pcols,pver)
   real(r8), intent(inout) :: reff_snow_grid(pcols,pver)
   real(r8), intent(inout) :: rei_grid(pcols,pver)
   real(r8), intent(inout) :: niic_grid(pcols,pver)
   real(r8), intent(inout) :: dei_grid(pcols,pver)
   real(r8), intent(inout) :: mu_grid(pcols,pver)
   real(r8), intent(inout) :: lambdac_grid(pcols,pver)
   real(r8), intent(inout) :: mgreffrain_grid(pcols,pver)
   real(r8), intent(inout) :: mgreffsnow_grid(pcols,pver)

   integer :: i, k

      drout2_grid = 0._r8
      reff_rain_grid = 0._r8
      des_grid = 0._r8
      dsout2_grid = 0._r8
      reff_snow_grid = 0._r8

         ! Diagnostic precipitation

         where (qrout_grid(:ngrdcol,top_lev:) >= 1.e-7_r8)
            drout2_grid(:ngrdcol,top_lev:) = avg_diameter( &
                 qrout_grid(:ngrdcol,top_lev:), &
                 nrout_grid(:ngrdcol,top_lev:) * rho_grid(:ngrdcol,top_lev:), &
                 rho_grid(:ngrdcol,top_lev:), rhow)

            reff_rain_grid(:ngrdcol,top_lev:) = drout2_grid(:ngrdcol,top_lev:) * &
                 1.5_r8 * 1.e6_r8
         end where

         where (qsout_grid(:ngrdcol,top_lev:) >= 1.e-7_r8)
            dsout2_grid(:ngrdcol,top_lev:) = avg_diameter( &
                 qsout_grid(:ngrdcol,top_lev:), &
                 nsout_grid(:ngrdcol,top_lev:) * rho_grid(:ngrdcol,top_lev:), &
                 rho_grid(:ngrdcol,top_lev:), rhosn)

            des_grid(:ngrdcol,top_lev:) = dsout2_grid(:ngrdcol,top_lev:) &
                 * 3._r8 * rhosn/rhows

            reff_snow_grid(:ngrdcol,top_lev:) = &
                 dsout2_grid(:ngrdcol,top_lev:) * 1.5_r8 * 1.e6_r8
         end where


      ! Effective radius and diameter for cloud ice.
      rei_grid = 25._r8

      niic_grid(:ngrdcol,top_lev:) = ni_grid(:ngrdcol,top_lev:) / &
           max(mincld,icecldf_grid(:ngrdcol,top_lev:))

      call size_dist_param_basic(mg_ice_props, icimrst_grid(:ngrdcol,top_lev:), &
           niic_grid(:ngrdcol,top_lev:), rei_grid(:ngrdcol,top_lev:))

      where (icimrst_grid(:ngrdcol,top_lev:) >= qsmall)
         rei_grid(:ngrdcol,top_lev:) = 1.5_r8/rei_grid(:ngrdcol,top_lev:) &
              * 1.e6_r8
      elsewhere
         rei_grid(:ngrdcol,top_lev:) = 25._r8
      end where

      dei_grid = rei_grid * rhoi/rhows * 2._r8

      ! Limiters for low cloud fraction.
      do k = top_lev, pver
         do i = 1, ngrdcol
            ! Convert snow effective diameter to microns
            des_grid(i,k) = des_grid(i,k) * 1.e6_r8
            if ( ast_grid(i,k) < 1.e-4_r8 ) then
               mu_grid(i,k) = mucon
               lambdac_grid(i,k) = (mucon + 1._r8)/dcon
               dei_grid(i,k) = deicon
            end if
         end do
      end do

      mgreffrain_grid(:ngrdcol,top_lev:pver) = reff_rain_grid(:ngrdcol,top_lev:pver)
      mgreffsnow_grid(:ngrdcol,top_lev:pver) = reff_snow_grid(:ngrdcol,top_lev:pver)

  end subroutine micro_ice_and_precip_size

  subroutine micro_precip_efficiency( &
         ngrdcol, top_lev, gravit, rhoh2o, iclwpst_grid, cld_grid, &
         cmeliq_grid, pdel_grid, prec_str_grid, acgcme_grid, acprecl_grid, &
         acnum_grid, tgliqwp_grid, tgcmeliq_grid, pe_grid, tpr_grid, &
         pefrac_grid)

   integer,  intent(in) :: ngrdcol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: gravit
   real(r8), intent(in) :: rhoh2o
   real(r8), intent(in) :: iclwpst_grid(pcols,pver)
   real(r8), intent(in) :: cld_grid(pcols,pver)
   real(r8), intent(in) :: cmeliq_grid(pcols,pver)
   real(r8), intent(in) :: pdel_grid(pcols,pver)
   real(r8), intent(in) :: prec_str_grid(pcols)
   real(r8), intent(inout) :: acgcme_grid(pcols)
   real(r8), intent(inout) :: acprecl_grid(pcols)
   integer,  intent(inout) :: acnum_grid(pcols)
   real(r8), intent(inout) :: tgliqwp_grid(pcols)
   real(r8), intent(inout) :: tgcmeliq_grid(pcols)
   real(r8), intent(inout) :: pe_grid(pcols)
   real(r8), intent(inout) :: tpr_grid(pcols)
   real(r8), intent(inout) :: pefrac_grid(pcols)

   integer  :: i, k
   real(r8) :: minlwp

      tgliqwp_grid(:ngrdcol) = 0._r8
      tgcmeliq_grid(:ngrdcol) = 0._r8
      do k = top_lev, pver
         do i = 1, ngrdcol
            tgliqwp_grid(i)  = tgliqwp_grid(i) + iclwpst_grid(i,k)*cld_grid(i,k)

            if (cmeliq_grid(i,k) > 1.e-12_r8) then
               !convert cmeliq to right units:  kgh2o/kgair/s  *  kgair/m2  / kgh2o/m3  = m/s
               tgcmeliq_grid(i) = tgcmeliq_grid(i) + cmeliq_grid(i,k) * &
                    (pdel_grid(i,k) / gravit) / rhoh2o
            end if
         end do
      end do

      ! note: 1e-6 kgho2/kgair/s * 1000. pa / (9.81 m/s2) / 1000 kgh2o/m3 = 1e-7 m/s
      ! this is 1ppmv of h2o in 10hpa
      ! alternatively: 0.1 mm/day * 1.e-4 m/mm * 1/86400 day/s = 1.e-9

      !-----------------------------------------------------------------------
      ! precipitation efficiency calculation  (accumulate cme and precip)

      minlwp = 0.01_r8        !minimum lwp threshold (kg/m3)

      ! zero out precip efficiency and total averaged precip
      pe_grid(:ngrdcol)     = 0._r8
      tpr_grid(:ngrdcol)    = 0._r8
      pefrac_grid(:ngrdcol) = 0._r8

      ! accumulate precip and condensation
      do i = 1, ngrdcol

         acgcme_grid(i)  = acgcme_grid(i) + tgcmeliq_grid(i)
         acprecl_grid(i) = acprecl_grid(i) + prec_str_grid(i)
         acnum_grid(i)   = acnum_grid(i) + 1

         ! if LWP is zero, then 'end of cloud': calculate precip efficiency
         if (tgliqwp_grid(i) < minlwp) then
            if (acprecl_grid(i) > 5.e-8_r8) then
               tpr_grid(i) = max(acprecl_grid(i)/acnum_grid(i), 1.e-15_r8)
               if (acgcme_grid(i) > 1.e-10_r8) then
                  pe_grid(i) = min(max(acprecl_grid(i)/acgcme_grid(i), 1.e-15_r8), 1.e5_r8)
                  pefrac_grid(i) = 1._r8
               end if
            end if

            ! reset counters
   !        if (pe_grid(i) /= 0._r8 .and. (pe_grid(i) < 1.e-8_r8 .or. pe_grid(i) > 1.e3_r8)) then
   !           write (iulog,*) 'PE_grid:ANOMALY  pe_grid, acprecl_grid, acgcme_grid, tpr_grid, acnum_grid ', &
   !                           pe_grid(i),acprecl_grid(i), acgcme_grid(i), tpr_grid(i), acnum_grid(i)
   !        endif

            acprecl_grid(i) = 0._r8
            acgcme_grid(i)  = 0._r8
            acnum_grid(i)   = 0
         end if               ! end LWP zero conditional

         ! if never find any rain....(after 10^3 timesteps...)
         if (acnum_grid(i) > 1000) then
            acnum_grid(i)   = 0
            acprecl_grid(i) = 0._r8
            acgcme_grid(i)  = 0._r8
         end if

      end do

  end subroutine micro_precip_efficiency

  subroutine micro_autoconversion_ratio( &
         ngrdcol, top_lev, gravit, prao_grid, prco_grid, nc_grid, pdel_grid, &
         vprao_grid, vprco_grid, racau_grid, cdnumc_grid)

   integer,  intent(in) :: ngrdcol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: gravit
   real(r8), intent(in) :: prao_grid(pcols,pver)
   real(r8), intent(in) :: prco_grid(pcols,pver)
   real(r8), intent(in) :: nc_grid(pcols,pver)
   real(r8), intent(in) :: pdel_grid(pcols,pver)
   real(r8), intent(inout) :: vprao_grid(pcols)
   real(r8), intent(inout) :: vprco_grid(pcols)
   real(r8), intent(inout) :: racau_grid(pcols)
   real(r8), intent(inout) :: cdnumc_grid(pcols)

   integer :: k
   integer :: cnt_grid(pcols)

      vprao_grid = 0._r8
      cnt_grid = 0
      do k = top_lev, pver
         vprao_grid(:ngrdcol) = vprao_grid(:ngrdcol) + prao_grid(:ngrdcol,k)
         where (prao_grid(:ngrdcol,k) /= 0._r8) cnt_grid(:ngrdcol) = cnt_grid(:ngrdcol) + 1
      end do

      where (cnt_grid > 0) vprao_grid = vprao_grid/cnt_grid

      vprco_grid = 0._r8
      cnt_grid = 0
      do k = top_lev, pver
         vprco_grid(:ngrdcol) = vprco_grid(:ngrdcol) + prco_grid(:ngrdcol,k)
         where (prco_grid(:ngrdcol,k) /= 0._r8) cnt_grid(:ngrdcol) = cnt_grid(:ngrdcol) + 1
      end do

      where (cnt_grid > 0)
         vprco_grid = vprco_grid/cnt_grid
         racau_grid = vprao_grid/vprco_grid
      elsewhere
         racau_grid = 0._r8
      end where

      racau_grid = min(racau_grid, 1.e10_r8)

      ! --------------------- !
      ! History Output Fields !
      ! --------------------- !

      ! Column droplet concentration
      cdnumc_grid(:ngrdcol) = sum(nc_grid(:ngrdcol,top_lev:pver) * &
           pdel_grid(:ngrdcol,top_lev:pver)/gravit, dim=2)

  end subroutine micro_autoconversion_ratio

  subroutine micro_effective_outputs( &
         ngrdcol, top_lev, liqcldf_grid, icecldf_grid, icwmrst_grid, &
         icimrst_grid, rel_grid, rei_grid, icwnc_grid, icinc_grid, &
         nevapr_grid, evpsnow_st_grid, efcout_grid, efiout_grid, ncout_grid, &
         niout_grid, freql_grid, freqi_grid, icwmrst_grid_out, &
         icimrst_grid_out, evprain_st_grid, fcti_grid, fctl_grid, ctrel_grid, &
         ctrei_grid, ctnl_grid, ctni_grid)

   integer,  intent(in) :: ngrdcol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: liqcldf_grid(pcols,pver)
   real(r8), intent(in) :: icecldf_grid(pcols,pver)
   real(r8), intent(in) :: icwmrst_grid(pcols,pver)
   real(r8), intent(in) :: icimrst_grid(pcols,pver)
   real(r8), intent(in) :: rel_grid(pcols,pver)
   real(r8), intent(in) :: rei_grid(pcols,pver)
   real(r8), intent(in) :: icwnc_grid(pcols,pver)
   real(r8), intent(in) :: icinc_grid(pcols,pver)
   real(r8), intent(in) :: nevapr_grid(pcols,pver)
   real(r8), intent(inout) :: evpsnow_st_grid(pcols,pver)
   real(r8), intent(inout) :: efcout_grid(pcols,pver)
   real(r8), intent(inout) :: efiout_grid(pcols,pver)
   real(r8), intent(inout) :: ncout_grid(pcols,pver)
   real(r8), intent(inout) :: niout_grid(pcols,pver)
   real(r8), intent(inout) :: freql_grid(pcols,pver)
   real(r8), intent(inout) :: freqi_grid(pcols,pver)
   real(r8), intent(inout) :: icwmrst_grid_out(pcols,pver)
   real(r8), intent(inout) :: icimrst_grid_out(pcols,pver)
   real(r8), intent(inout) :: evprain_st_grid(pcols,pver)
   real(r8), intent(inout) :: fcti_grid(pcols)
   real(r8), intent(inout) :: fctl_grid(pcols)
   real(r8), intent(inout) :: ctrel_grid(pcols)
   real(r8), intent(inout) :: ctrei_grid(pcols)
   real(r8), intent(inout) :: ctnl_grid(pcols)
   real(r8), intent(inout) :: ctni_grid(pcols)

   integer :: i, k

      efcout_grid      = 0._r8
      efiout_grid      = 0._r8
      ncout_grid       = 0._r8
      niout_grid       = 0._r8
      freql_grid       = 0._r8
      freqi_grid       = 0._r8
      icwmrst_grid_out = 0._r8
      icimrst_grid_out = 0._r8

      do k = top_lev, pver
         do i = 1, ngrdcol
            if ( liqcldf_grid(i,k) > 0.01_r8 .and. icwmrst_grid(i,k) > 5.e-5_r8 ) then
               efcout_grid(i,k) = rel_grid(i,k) * liqcldf_grid(i,k)
               ncout_grid(i,k)  = icwnc_grid(i,k) * liqcldf_grid(i,k)
               freql_grid(i,k)  = liqcldf_grid(i,k)
               icwmrst_grid_out(i,k) = icwmrst_grid(i,k)
            end if
            if ( icecldf_grid(i,k) > 0.01_r8 .and. icimrst_grid(i,k) > 1.e-6_r8 ) then
               efiout_grid(i,k) = rei_grid(i,k) * icecldf_grid(i,k)
               niout_grid(i,k)  = icinc_grid(i,k) * icecldf_grid(i,k)
               freqi_grid(i,k)  = icecldf_grid(i,k)
               icimrst_grid_out(i,k) = icimrst_grid(i,k)
            end if
         end do
      end do

      ! Cloud top effective radius and number.
      fcti_grid  = 0._r8
      fctl_grid  = 0._r8
      ctrel_grid = 0._r8
      ctrei_grid = 0._r8
      ctnl_grid  = 0._r8
      ctni_grid  = 0._r8
      do i = 1, ngrdcol
         do k = top_lev, pver
            if ( liqcldf_grid(i,k) > 0.01_r8 .and. icwmrst_grid(i,k) > 1.e-7_r8 ) then
               ctrel_grid(i) = rel_grid(i,k) * liqcldf_grid(i,k)
               ctnl_grid(i)  = icwnc_grid(i,k) * liqcldf_grid(i,k)
               fctl_grid(i)  = liqcldf_grid(i,k)
               exit
            end if
            if ( icecldf_grid(i,k) > 0.01_r8 .and. icimrst_grid(i,k) > 1.e-7_r8 ) then
               ctrei_grid(i) = rei_grid(i,k) * icecldf_grid(i,k)
               ctni_grid(i)  = icinc_grid(i,k) * icecldf_grid(i,k)
               fcti_grid(i)  = icecldf_grid(i,k)
               exit
            end if
         end do
      end do

      ! Evaporation of stratiform precipitation fields for UNICON
      evprain_st_grid(:ngrdcol,:pver) = nevapr_grid(:ngrdcol,:pver) - evpsnow_st_grid(:ngrdcol,:pver)
      do k = top_lev, pver
         do i = 1, ngrdcol
            evprain_st_grid(i,k) = max(evprain_st_grid(i,k), 0._r8)
            evpsnow_st_grid(i,k) = max(evpsnow_st_grid(i,k), 0._r8)
         end do
      end do

  end subroutine micro_effective_outputs

  subroutine micro_history_tendencies( &
         ngrdcol, top_lev, qcreso_grid, melto_grid, mnuccco_grid, &
         mnuccto_grid, bergo_grid, homoo_grid, msacwio_grid, prao_grid, &
         prco_grid, psacwso_grid, bergso_grid, cmeiout_grid, qireso_grid, &
         prcio_grid, praio_grid, mpdw2v, mpdw2i, mpdw2p, mpdi2v, mpdi2w, &
         mpdi2p)

   integer,  intent(in) :: ngrdcol
   integer,  intent(in) :: top_lev
   real(r8), intent(in) :: qcreso_grid(pcols,pver)
   real(r8), intent(in) :: melto_grid(pcols,pver)
   real(r8), intent(in) :: mnuccco_grid(pcols,pver)
   real(r8), intent(in) :: mnuccto_grid(pcols,pver)
   real(r8), intent(in) :: bergo_grid(pcols,pver)
   real(r8), intent(in) :: homoo_grid(pcols,pver)
   real(r8), intent(in) :: msacwio_grid(pcols,pver)
   real(r8), intent(in) :: prao_grid(pcols,pver)
   real(r8), intent(in) :: prco_grid(pcols,pver)
   real(r8), intent(in) :: psacwso_grid(pcols,pver)
   real(r8), intent(in) :: bergso_grid(pcols,pver)
   real(r8), intent(in) :: cmeiout_grid(pcols,pver)
   real(r8), intent(in) :: qireso_grid(pcols,pver)
   real(r8), intent(in) :: prcio_grid(pcols,pver)
   real(r8), intent(in) :: praio_grid(pcols,pver)
   real(r8), intent(inout) :: mpdw2v(pcols,pver)
   real(r8), intent(inout) :: mpdw2i(pcols,pver)
   real(r8), intent(inout) :: mpdw2p(pcols,pver)
   real(r8), intent(inout) :: mpdi2v(pcols,pver)
   real(r8), intent(inout) :: mpdi2w(pcols,pver)
   real(r8), intent(inout) :: mpdi2p(pcols,pver)

   mpdw2v = 0._r8
   mpdw2i = 0._r8
   mpdw2p = 0._r8
   mpdi2v = 0._r8
   mpdi2w = 0._r8
   mpdi2p = 0._r8

      mpdw2v(:ngrdcol,top_lev:pver) =  qcreso_grid(:ngrdcol,top_lev:pver)

      mpdw2i(:ngrdcol,top_lev:pver) =  melto_grid(:ngrdcol,top_lev:pver) - mnuccco_grid(:ngrdcol,top_lev:pver)&
           - mnuccto_grid(:ngrdcol,top_lev:pver) -  bergo_grid(:ngrdcol,top_lev:pver) - homoo_grid(:ngrdcol,top_lev:pver)&
           - msacwio_grid(:ngrdcol,top_lev:pver)

      mpdw2p(:ngrdcol,top_lev:pver) = -prao_grid(:ngrdcol,top_lev:pver) - prco_grid(:ngrdcol,top_lev:pver)&
           - psacwso_grid(:ngrdcol,top_lev:pver) - bergso_grid(:ngrdcol,top_lev:pver)

      mpdi2v(:ngrdcol,top_lev:pver) =  cmeiout_grid(:ngrdcol,top_lev:pver) + qireso_grid(:ngrdcol,top_lev:pver)

      mpdi2w(:ngrdcol,top_lev:pver) = -melto_grid(:ngrdcol,top_lev:pver) + mnuccco_grid(:ngrdcol,top_lev:pver) &
           + mnuccto_grid(:ngrdcol,top_lev:pver) +  bergo_grid(:ngrdcol,top_lev:pver) + homoo_grid(:ngrdcol,top_lev:pver)&
           + msacwio_grid(:ngrdcol,top_lev:pver)

      mpdi2p(:ngrdcol,top_lev:pver) = -prcio_grid(:ngrdcol,top_lev:pver) - praio_grid(:ngrdcol,top_lev:pver)

  end subroutine micro_history_tendencies

end module pycam_micro_kernels
