! The calls the cloud macro/microphysics stage's glue makes into CAM.
!
! GENERATED by tools/generate_pi_cam_mm_handles.py.  Do not edit by hand;
! edit the generator.
!
! tphysbc stage 7 is replaced whole by a Python process, so everything it
! does between and around the two drivers is reached from here: the aerosol
! activation, the drivers themselves (whole, for the first gate), tendency
! scaling and application against phys_tend, the energy checks, the tracer
! mass fixer.  The tendency objects the stage owns live here; Python gets
! views.  This module is an addition: it calls the oracle's routines and
! replaces none.

module pycam_mm_handles

  use, intrinsic :: iso_c_binding, only: c_char, c_double, c_int, c_int64_t, &
       c_loc, c_null_ptr, c_ptr
  use shr_kind_mod,   only: r8 => shr_kind_r8
  use ppgrid,         only: pcols, pver, pverp, begchunk, endchunk
  use constituents,   only: pcnst
  use physics_types,  only: physics_state, physics_ptend, physics_tend, &
       physics_update, physics_ptend_sum, physics_ptend_scale, physics_ptend_dealloc
  use physics_buffer, only: physics_buffer_desc, pbuf_get_chunk
  use check_energy,   only: check_energy_chng
  use microp_aero,    only: microp_aero_run
  use macrop_driver,  only: macrop_driver_tend
  use microp_driver,  only: microp_driver_tend
  use water_tracers,  only: wtrc_mass_fixer
  use water_tracer_vars, only: wtrc_nwset
  use time_manager,   only: get_nstep, get_step_size
  use pycam_macro_handles, only: macro_ptend, macro_det_s, macro_det_ice
  use pycam_micro_handles, only: micro_ptend

  implicit none
  private

  public :: pycam_mm_bind_hosts, python_owns_mm

  logical, save :: python_owns_mm = .false.

  ! the stage's own tendency objects, held per chunk
  type(physics_ptend), allocatable, target, save :: mm_ptend(:)
  type(physics_ptend), allocatable, target, save :: mm_ptend_aero(:)
  ! what macrop_driver_tend returns beside its ptend
  real(r8), allocatable, target, save :: mm_det_s(:,:), mm_det_ice(:,:)

  ! the hosts, bound from the control layer
  type(physics_state), pointer, save :: host_state(:) => null()
  type(physics_tend),  pointer, save :: host_tend(:) => null()
  type(physics_buffer_desc), pointer, save :: host_pbuf2d(:,:) => null()

  integer(c_int), parameter, public :: view_ptend_s = 21
  integer(c_int), parameter, public :: view_ptend_q = 22
  integer(c_int), parameter, public :: view_ptend_aero_s = 23
  integer(c_int), parameter, public :: view_ptend_aero_q = 24
  integer(c_int), parameter, public :: view_det_s = 31
  integer(c_int), parameter, public :: view_det_ice = 32

contains

  logical function chunk_ok(lchnk)
    integer(c_int), intent(in) :: lchnk
    chunk_ok = allocated(mm_ptend) .and. lchnk >= begchunk .and. lchnk <= endchunk
  end function chunk_ok

  subroutine pycam_mm_bind_hosts(state, tend, pbuf2d)
    type(physics_state), pointer, intent(in) :: state(:)
    type(physics_tend),  pointer, intent(in) :: tend(:)
    type(physics_buffer_desc), pointer, intent(in) :: pbuf2d(:,:)
    host_state => state
    host_tend => tend
    host_pbuf2d => pbuf2d
    if (.not. allocated(mm_ptend)) allocate(mm_ptend(begchunk:endchunk))
    if (.not. allocated(mm_ptend_aero)) allocate(mm_ptend_aero(begchunk:endchunk))
    if (.not. allocated(mm_det_s)) then
      allocate(mm_det_s(pcols,begchunk:endchunk), mm_det_ice(pcols,begchunk:endchunk))
      mm_det_s = 0._r8
      mm_det_ice = 0._r8
    end if
  end subroutine pycam_mm_bind_hosts

  subroutine view1(field, ptr, ndims, extents)
    real(r8), intent(in), target :: field(:)
    type(c_ptr), intent(out) :: ptr
    integer(c_int), intent(out) :: ndims
    integer(c_int64_t), intent(out) :: extents(5)
    ptr = c_loc(field(1)); ndims = 1_c_int
    extents(1) = int(size(field, 1), c_int64_t)
  end subroutine view1

  subroutine view2(field, ptr, ndims, extents)
    real(r8), intent(in), target :: field(:,:)
    type(c_ptr), intent(out) :: ptr
    integer(c_int), intent(out) :: ndims
    integer(c_int64_t), intent(out) :: extents(5)
    ptr = c_loc(field(1,1)); ndims = 2_c_int
    extents(1) = int(size(field, 1), c_int64_t)
    extents(2) = int(size(field, 2), c_int64_t)
  end subroutine view2

  subroutine view3(field, ptr, ndims, extents)
    real(r8), intent(in), target :: field(:,:,:)
    type(c_ptr), intent(out) :: ptr
    integer(c_int), intent(out) :: ndims
    integer(c_int64_t), intent(out) :: extents(5)
    ptr = c_loc(field(1,1,1)); ndims = 3_c_int
    extents(1) = int(size(field, 1), c_int64_t)
    extents(2) = int(size(field, 2), c_int64_t)
    extents(3) = int(size(field, 3), c_int64_t)
  end subroutine view3

  ! ------------------------------------------------------------------ !
  ! Ownership, the clock, views
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_mm_set_owner_v1(owns) &
       bind(C, name='pycam_mm_set_owner_v1') result(status)
    integer(c_int), value, intent(in) :: owns
    python_owns_mm = owns /= 0_c_int
    status = 0_c_int
  end function pycam_mm_set_owner_v1

  integer(c_int) function pycam_mm_nstep_v1() bind(C, name='pycam_mm_nstep_v1') result(status)
    status = int(get_nstep(), c_int)
  end function pycam_mm_nstep_v1

  integer(c_int) function pycam_mm_dt_v1() bind(C, name='pycam_mm_dt_v1') result(status)
    status = int(get_step_size(), c_int)
  end function pycam_mm_dt_v1

  integer(c_int) function pycam_mm_view_v1(lchnk, code, ptr, ndims, extents) &
       bind(C, name='pycam_mm_view_v1') result(status)
    integer(c_int), value, intent(in) :: lchnk, code
    type(c_ptr), intent(out) :: ptr
    integer(c_int), intent(out) :: ndims
    integer(c_int64_t), intent(out) :: extents(5)
    ptr = c_null_ptr; ndims = 0_c_int; extents = 0_c_int64_t
    status = 1_c_int
    if (.not. chunk_ok(lchnk)) return
    status = 2_c_int
    select case (code)
    case (view_ptend_s)
      if (.not. allocated(mm_ptend(lchnk)%s)) return
      call view2(mm_ptend(lchnk)%s, ptr, ndims, extents)
    case (view_ptend_q)
      if (.not. allocated(mm_ptend(lchnk)%q)) return
      call view3(mm_ptend(lchnk)%q, ptr, ndims, extents)
    case (view_ptend_aero_s)
      if (.not. allocated(mm_ptend_aero(lchnk)%s)) return
      call view2(mm_ptend_aero(lchnk)%s, ptr, ndims, extents)
    case (view_ptend_aero_q)
      if (.not. allocated(mm_ptend_aero(lchnk)%q)) return
      call view3(mm_ptend_aero(lchnk)%q, ptr, ndims, extents)
    case (view_det_s)
      call view1(mm_det_s(:,lchnk), ptr, ndims, extents)
    case (view_det_ice)
      call view1(mm_det_ice(:,lchnk), ptr, ndims, extents)
    case default
      status = 3_c_int
      return
    end select
    status = 0_c_int
  end function pycam_mm_view_v1

  ! ------------------------------------------------------------------ !
  ! The stage's calls, in the driver's form
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_mm_microp_aero_run_v1(lchnk, cld_macmic_ztodt) &
       bind(C, name='pycam_mm_microp_aero_run_v1') result(status)
    ! physpkg.F90:2319: call microp_aero_run(state, ptend_aero, cld_macmic_ztodt, pbuf)
    integer(c_int), value, intent(in) :: lchnk
    real(c_double), value, intent(in) :: cld_macmic_ztodt
    type(physics_buffer_desc), pointer :: pbuf(:)
    status = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_pbuf2d)) return
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk)
    call microp_aero_run(host_state(lchnk), mm_ptend_aero(lchnk), cld_macmic_ztodt, pbuf)
    status = 0_c_int
  end function pycam_mm_microp_aero_run_v1

  integer(c_int) function pycam_mm_macrop_driver_tend_v1(lchnk, cld_macmic_ztodt, &
       landfrac, ocnfrac, snowhland, dlf, dlf2, wtdlf, cmfmc, cmfmc2, ts, sst, zdu) &
       bind(C, name='pycam_mm_macrop_driver_tend_v1') result(status)
    ! physpkg.F90:2244-2250, the whole driver: Gate M-1's form.  det_s and
    ! det_ice come out into the held arrays the energy check reads.
    integer(c_int), value, intent(in) :: lchnk
    real(c_double), value, intent(in) :: cld_macmic_ztodt
    real(c_double), intent(in) :: landfrac(pcols), ocnfrac(pcols), snowhland(pcols)
    real(c_double), intent(in) :: dlf(pcols,pver), dlf2(pcols,pver), wtdlf(pcols,pver,wtrc_nwset)
    real(c_double), intent(in) :: cmfmc(pcols,pverp), cmfmc2(pcols,pverp)
    real(c_double), intent(in) :: ts(pcols), sst(pcols), zdu(pcols,pver)
    type(physics_buffer_desc), pointer :: pbuf(:)
    status = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_pbuf2d)) return
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk)
    call macrop_driver_tend( &
         host_state(lchnk), mm_ptend(lchnk), cld_macmic_ztodt, &
         landfrac, ocnfrac, snowhland, &
         dlf, dlf2, wtdlf, &
         cmfmc, cmfmc2, &
         ts, sst, zdu, &
         pbuf, mm_det_s(:,lchnk), mm_det_ice(:,lchnk))
    status = 0_c_int
  end function pycam_mm_macrop_driver_tend_v1

  integer(c_int) function pycam_mm_take_macro_v1(lchnk) &
       bind(C, name='pycam_mm_take_macro_v1') result(status)
    ! The macrophysics sub-walk in the driver's place: what the split stage's
    ! post-leaf did (0039-macro-tend-boundary.patch), statement for statement
    ! -- the walk's tendency object and detrainment become the stage's.
    ! Three copies; the tendency assignment reallocates mm_ptend's
    ! components exactly as tphysbc's `ptend = macro_ptend(lchnk)` did.
    integer(c_int), value, intent(in) :: lchnk
    status = 1_c_int
    if (.not. chunk_ok(lchnk)) return
    status = 2_c_int
    if (macro_ptend(lchnk)%psetcols < 1) return
    mm_ptend(lchnk)   = macro_ptend(lchnk)
    mm_det_s(:,lchnk)   = macro_det_s(:,lchnk)
    mm_det_ice(:,lchnk) = macro_det_ice(:,lchnk)
    ! tphysbc's ptend is one object, freed by physics_update before the
    ! next driver call initialises it; the walk's copy dies here likewise,
    ! or physics_ptend_init refuses it next step
    call physics_ptend_dealloc(macro_ptend(lchnk))
    status = 0_c_int
  end function pycam_mm_take_macro_v1

  integer(c_int) function pycam_mm_take_micro_v1(lchnk) &
       bind(C, name='pycam_mm_take_micro_v1') result(status)
    ! The microphysics sub-walk in microp_driver_tend's place: the driver's
    ! ptend is intent(out), so the walk's tendency object becomes the
    ! stage's -- one derived-type assignment, as for the macrophysics.
    integer(c_int), value, intent(in) :: lchnk
    status = 1_c_int
    if (.not. chunk_ok(lchnk)) return
    status = 2_c_int
    if (micro_ptend(lchnk)%psetcols < 1) return
    mm_ptend(lchnk) = micro_ptend(lchnk)
    call physics_ptend_dealloc(micro_ptend(lchnk))
    status = 0_c_int
  end function pycam_mm_take_micro_v1

  integer(c_int) function pycam_mm_microp_driver_tend_v1(lchnk, cld_macmic_ztodt) &
       bind(C, name='pycam_mm_microp_driver_tend_v1') result(status)
    ! physpkg.F90:2351: call microp_driver_tend(state, ptend, cld_macmic_ztodt, pbuf)
    integer(c_int), value, intent(in) :: lchnk
    real(c_double), value, intent(in) :: cld_macmic_ztodt
    type(physics_buffer_desc), pointer :: pbuf(:)
    status = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_pbuf2d)) return
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk)
    call microp_driver_tend(host_state(lchnk), mm_ptend(lchnk), cld_macmic_ztodt, pbuf)
    status = 0_c_int
  end function pycam_mm_microp_driver_tend_v1

  integer(c_int) function pycam_mm_ptend_scale_v1(lchnk, which, cld_macmic_num_steps, ncol) &
       bind(C, name='pycam_mm_ptend_scale_v1') result(status)
    ! physpkg.F90:2262 / 2361: physics_ptend_scale(ptend, 1._r8/cld_macmic_num_steps, ncol)
    integer(c_int), value, intent(in) :: lchnk, which, cld_macmic_num_steps, ncol
    status = 1_c_int
    if (.not. chunk_ok(lchnk)) return
    select case (which)
    case (1)
      call physics_ptend_scale(mm_ptend(lchnk), 1._r8/cld_macmic_num_steps, ncol)
    case (2)
      call physics_ptend_scale(mm_ptend_aero(lchnk), 1._r8/cld_macmic_num_steps, ncol)
    case default
      return
    end select
    status = 0_c_int
  end function pycam_mm_ptend_scale_v1

  integer(c_int) function pycam_mm_update_v1(lchnk, which, ztodt) &
       bind(C, name='pycam_mm_update_v1') result(status)
    ! physpkg.F90:2263 / 2363: physics_update(state, ptend, ztodt, tend)
    integer(c_int), value, intent(in) :: lchnk, which
    real(c_double), value, intent(in) :: ztodt
    status = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_tend)) return
    select case (which)
    case (1)
      call physics_update(host_state(lchnk), mm_ptend(lchnk), ztodt, host_tend(lchnk))
    case (2)
      call physics_update(host_state(lchnk), mm_ptend_aero(lchnk), ztodt, host_tend(lchnk))
    case default
      return
    end select
    status = 0_c_int
  end function pycam_mm_update_v1

  integer(c_int) function pycam_mm_check_energy_v1(lchnk, name, name_len, nstep, ztodt, &
       cld_macmic_num_steps, flx_vap, flx_cnd, flx_ice, flx_sen, scaled) &
       bind(C, name='pycam_mm_check_energy_v1') result(status)
    ! physpkg.F90:2264-2266 and 2364-2366.  `scaled` /= 0 is the form after
    ! the drivers, whose three flux arguments are divided by the substep
    ! count inside the call; the expression is formed here.
    integer(c_int), value, intent(in) :: lchnk, name_len, nstep, cld_macmic_num_steps, scaled
    character(kind=c_char), intent(in) :: name(name_len)
    real(c_double), value, intent(in) :: ztodt
    real(c_double), intent(in) :: flx_vap(pcols), flx_cnd(pcols), flx_ice(pcols), flx_sen(pcols)
    character(len=name_len) :: label
    integer :: i
    status = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_tend)) return
    do i = 1, name_len
      label(i:i) = name(i)
    end do
    if (scaled /= 0_c_int) then
      call check_energy_chng(host_state(lchnk), host_tend(lchnk), label, nstep, ztodt, &
           flx_vap, flx_cnd/cld_macmic_num_steps, flx_ice/cld_macmic_num_steps, &
           flx_sen/cld_macmic_num_steps)
    else
      call check_energy_chng(host_state(lchnk), host_tend(lchnk), label, nstep, ztodt, &
           flx_vap, flx_cnd, flx_ice, flx_sen)
    end if
    status = 0_c_int
  end function pycam_mm_check_energy_v1

  integer(c_int) function pycam_mm_ptend_sum_aero_v1(lchnk, ncol) &
       bind(C, name='pycam_mm_ptend_sum_aero_v1') result(status)
    ! physpkg.F90:2355-2356: physics_ptend_sum(ptend_aero, ptend, ncol); dealloc(ptend_aero)
    integer(c_int), value, intent(in) :: lchnk, ncol
    status = 1_c_int
    if (.not. chunk_ok(lchnk)) return
    call physics_ptend_sum(mm_ptend_aero(lchnk), mm_ptend(lchnk), ncol)
    call physics_ptend_dealloc(mm_ptend_aero(lchnk))
    status = 0_c_int
  end function pycam_mm_ptend_sum_aero_v1

  integer(c_int) function pycam_mm_wtrc_mass_fixer_v1(lchnk) &
       bind(C, name='pycam_mm_wtrc_mass_fixer_v1') result(status)
    ! physpkg.F90:2391-2393
    integer(c_int), value, intent(in) :: lchnk
    status = 1_c_int
    if (.not. chunk_ok(lchnk)) return
    call wtrc_mass_fixer(host_state(lchnk))
    status = 0_c_int
  end function pycam_mm_wtrc_mass_fixer_v1

end module pycam_mm_handles
