! vertical_diffusion_tend (vertical_diffusion.F90:816-1384) hoisted for the
! vdiff segment runner: its locals as module state, its body in pieces the
! runner calls in the source's order, its dummies bound by the caller.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/vertical_diffusion.yaml.  Do not edit by hand; edit the spec.
module pycam_vdiff_driver
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_loc, c_null_ptr, c_f_pointer
  use shr_kind_mod, only: r8 => shr_kind_r8
  use shr_kind_mod, only: i4=> shr_kind_i4
  use ppgrid, only : pcols, pver, pverp
  use constituents, only : pcnst, qmin, cnst_get_ind
  use diffusion_solver, only : vdiff_selector
  use cam_abortutils, only : endrun
  use error_messages, only : handle_errmsg
  use physconst, only : cpair , gravit , rair , zvir , latvap , latice , karman , mwdry , avogad , boltz , tms_orocnst, tms_z0fac
  use cam_history, only : fieldname_len
  use perf_mod
  use cam_logfile, only : iulog
  use ref_pres, only : do_molec_diff
  use phys_control, only : phys_getopts, waccmx_is
  use time_manager, only : is_first_step
  use physics_buffer, only : physics_buffer_desc, pbuf_get_field, pbuf_set_field
  use physics_types, only : physics_state, physics_ptend, physics_ptend_init
  use cam_history, only : outfld
  use trb_mtn_stress, only : compute_tms
  use eddy_diff, only : compute_eddy_diff
  use hb_diff, only : compute_hb_diff
  use wv_saturation, only : qsat
  use molec_diff, only : compute_molec_diff, vd_lu_qdecomp
  use constituents, only : qmincg, qmin
  use diffusion_solver, only : compute_vdiff, any, operator(.not.)
  use physconst, only : cpairv, rairv
  use time_manager, only : get_nstep
  use constituents, only : cnst_get_type_byind, cnst_name, cnst_fixed_ubc, cnst_fixed_ubflx
  use physconst, only : pi
  use pbl_utils, only : virtem, calc_obklen
  use vertical_diffusion, only: eddy_scheme, do_pseudocon_diff, shallow_scheme, fieldlist_wet, fieldlist_dry, fieldlist_molec, ntop, nbot, tke_idx, kvh_idx, kvm_idx, kvt_idx, turbtype_idx, smaw_idx, tauresx_idx, tauresy_idx, vdiffnam, ixcldice, ixcldliq, ixnumice, ixnumliq, qrl_idx, wsedl_idx, pblh_idx, tpert_idx, qpert_idx, bprod_idx, ipbl_idx, kpblh_idx, wstarPBL_idx, tkes_idx, went_idx, qtl_flx_idx, qti_flx_idx, kv_top_pressure, kv_top_scale, kv_freetrop_scale, diff_cnsrv_mass_check, do_tms, prog_modal_aero, pmam_ncnst, pmam_cnst_idx
  implicit none
  private
  public :: driver_piece_1, driver_piece_2, driver_piece_3, driver_piece_4, driver_piece_5, driver_piece_6, driver_piece_7, driver_piece_8, driver_piece_9, driver_piece_10, driver_piece_11, driver_piece_12, driver_piece_13, compute_tms_frame, compute_eddy_diff_frame, compute_vdiff_1_frame, compute_vdiff_2_frame, compute_tms_original, compute_eddy_diff_original, compute_vdiff_1_original, compute_vdiff_2_original, driver_bind

  integer(c_int64_t), parameter :: zero_shape(1) = (/ 0_c_int64_t /)

  ! the routine's dummies, bound by the caller
  real(r8), save, public :: ztodt
  type(physics_state), pointer, save, public :: state => null()
  real(r8), pointer, save, public :: taux(:) => null()
  real(r8), pointer, save, public :: tauy(:) => null()
  real(r8), pointer, save, public :: shflx(:) => null()
  real(r8), pointer, save, public :: cflx(:,:) => null()
  real(r8), pointer, save, public :: ustar(:) => null()
  real(r8), pointer, save, public :: obklen(:) => null()
  type(physics_ptend), pointer, save, public :: ptend => null()
  real(r8), pointer, save, public :: cldn(:,:) => null()
  real(r8), pointer, save, public :: ocnfrac(:) => null()
  real(r8), pointer, save, public :: landfrac(:) => null()
  real(r8), pointer, save, public :: sgh(:) => null()
  type(physics_buffer_desc), pointer, save, public :: pbuf(:) => null()

  ! the routine's locals, held for the chunk in flight
  real(r8), pointer, save, public :: bprod(:,:) => null()
  real(r8), save, target, public :: cgh(pcols,pverp)
  real(r8), save, target, public :: cgs(pcols,pverp)
  real(r8), save, target, public :: dtk(pcols,pver)
  character(128), save, target, public :: errstring
  real(r8), save, target, public :: ftem(pcols,pver)
  real(r8), save, target, public :: ftem_aftpbl(pcols,pver)
  real(r8), save, target, public :: ftem_prepbl(pcols,pver)
  integer, save, target, public :: i
  integer(i4), pointer, save, public :: ipbl(:) => null()
  integer, save, target, public :: k
  real(r8), save, target, public :: kbfs(pcols)
  real(r8), save, target, public :: khfs(pcols)
  integer(i4), pointer, save, public :: kpblh(:) => null()
  real(r8), save, target, public :: kqfs(pcols)
  real(r8), save, target, public :: ksrftms(pcols)
  real(r8), save, target, public :: kvh(pcols,pverp)
  real(r8), pointer, save, public :: kvh_in(:,:) => null()
  logical, save, target, public :: kvinit
  real(r8), save, target, public :: kvm(pcols,pverp)
  real(r8), pointer, save, public :: kvm_in(:,:) => null()
  real(r8), save, target, public :: kvq(pcols,pverp)
  real(r8), pointer, save, public :: kvt(:,:) => null()
  integer, save, target, public :: l
  integer, save, target, public :: lchnk
  logical, save, target, public :: lq(pcnst)
  integer, save, target, public :: m
  integer, save, target, public :: ncol
  integer, save, target, public :: nstep
  real(r8), pointer, save, public :: pblh(:) => null()
  real(r8), save, target, public :: pdelx
  real(r8), save, target, public :: q_tmp(pcols,pver,pcnst)
  real(r8), save, target, public :: qi_aft_pbl(pcols,pver)
  real(r8), save, target, public :: qi_pro(pcols,pver)
  real(r8), save, target, public :: ql_aft_pbl(pcols,pver)
  real(r8), save, target, public :: ql_pro(pcols,pver)
  real(r8), pointer, save, public :: qpert(:) => null()
  real(r8), save, target, public :: qpertpbl(pcols)
  real(r8), pointer, save, public :: qrl(:,:) => null()
  real(r8), save, target, public :: qt(pcols,pver)
  real(r8), save, target, public :: qt_prepbl(pcols,pver)
  real(r8), save, target, public :: qtflx(pcols,pverp)
  real(r8), save, target, public :: qtflx_cg(pcols,pverp)
  real(r8), pointer, save, public :: qti_flx(:,:) => null()
  real(r8), pointer, save, public :: qtl_flx(:,:) => null()
  real(r8), save, target, public :: qtten(pcols,pver)
  real(r8), save, target, public :: qv_aft_pbl(pcols,pver)
  real(r8), save, target, public :: qv_pro(pcols,pver)
  real(r8), save, target, public :: rairi(pcols,pver+1)
  real(r8), save, target, public :: rhoair
  real(r8), save, target, public :: rhten(pcols,pver)
  real(r8), save, target, public :: ri(pcols,pver)
  real(r8), save, target, public :: rrho(pcols)
  real(r8), save, target, public :: rztodt
  real(r8), save, target, public :: s_aft_pbl(pcols,pver)
  real(r8), save, target, public :: s_pro(pcols,pver)
  real(r8), save, target, public :: s_tmp(pcols,pver)
  real(r8), save, target, public :: sfi(pcols,pverp)
  real(r8), save, target, public :: sflx
  real(r8), save, target, public :: sl(pcols,pver)
  real(r8), save, target, public :: sl_prepbl(pcols,pver)
  real(r8), save, target, public :: slflx(pcols,pverp)
  real(r8), save, target, public :: slflx_cg(pcols,pverp)
  real(r8), save, target, public :: slten(pcols,pver)
  real(r8), save, target, public :: slv(pcols,pver)
  real(r8), save, target, public :: slv_prepbl(pcols,pver)
  real(r8), pointer, save, public :: smaw(:,:) => null()
  real(r8), save, target, public :: sprod(pcols,pverp)
  real(r8), save, target, public :: sum1
  real(r8), save, target, public :: sum2
  real(r8), save, target, public :: sum3
  real(r8), save, target, public :: t_aftpbl(pcols,pver)
  real(r8), save, target, public :: t_pro(pcols,pver)
  real(r8), pointer, save, public :: tauresx(:) => null()
  real(r8), pointer, save, public :: tauresy(:) => null()
  real(r8), save, target, public :: tautmsx(pcols)
  real(r8), save, target, public :: tautmsy(pcols)
  real(r8), save, target, public :: tautotx(pcols)
  real(r8), save, target, public :: tautoty(pcols)
  real(r8), save, target, public :: tem2(pcols,pver)
  real(r8), save, target, public :: th(pcols,pver)
  real(r8), save, target, public :: thvs(pcols)
  real(r8), pointer, save, public :: tke(:,:) => null()
  real(r8), pointer, save, public :: tkes(:) => null()
  real(r8), save, target, public :: tmp1(pcols)
  real(r8), save, target, public :: topflx(pcols)
  real(r8), pointer, save, public :: tpert(:) => null()
  real(r8), save, target, public :: tpertpbl(pcols)
  real(r8), save, target, public :: tten(pcols,pver)
  integer(i4), pointer, save, public :: turbtype(:,:) => null()
  real(r8), save, target, public :: u_aft_pbl(pcols,pver)
  real(r8), save, target, public :: u_tmp(pcols,pver)
  real(r8), save, target, public :: uflx(pcols,pverp)
  real(r8), save, target, public :: uflx_cg(pcols,pverp)
  real(r8), save, target, public :: v_aft_pbl(pcols,pver)
  real(r8), save, target, public :: v_tmp(pcols,pver)
  real(r8), save, target, public :: vflx(pcols,pverp)
  real(r8), save, target, public :: vflx_cg(pcols,pverp)
  real(r8), pointer, save, public :: went(:) => null()
  real(r8), save, target, public :: wpert(pcols)
  real(r8), pointer, save, public :: wsedl(:,:) => null()
  real(r8), pointer, save, public :: wstarpbl(:) => null()

  ! vertical_diffusion.F90:80-81: the module's own declaration, verbatim
    integer, parameter   :: nturb = 5                    ! Number of iterations for solution ( when 'diag_TKE' scheme is selected )
    logical, parameter   :: wstarent = .true.            ! Use wstar (.true.) or TKE (.false.) entrainment closure

contains

  subroutine driver_bind(a_ztodt, a_state, a_taux, a_tauy, a_shflx, a_cflx, a_ustar, a_obklen, a_ptend, a_cldn, a_ocnfrac, a_landfrac, a_sgh, a_pbuf)
    ! the dummies of vertical_diffusion_tend, as the caller's statement passes them
    real(r8), intent(in) :: a_ztodt
    type(physics_state), target, intent(inout) :: a_state
    real(r8), target, intent(inout) :: a_taux(:)
    real(r8), target, intent(inout) :: a_tauy(:)
    real(r8), target, intent(inout) :: a_shflx(:)
    real(r8), target, intent(inout) :: a_cflx(:,:)
    real(r8), target, intent(inout) :: a_ustar(:)
    real(r8), target, intent(inout) :: a_obklen(:)
    type(physics_ptend), target, intent(inout) :: a_ptend
    real(r8), target, intent(inout) :: a_cldn(:,:)
    real(r8), target, intent(inout) :: a_ocnfrac(:)
    real(r8), target, intent(inout) :: a_landfrac(:)
    real(r8), target, intent(inout) :: a_sgh(:)
    type(physics_buffer_desc), target, intent(inout) :: a_pbuf(:)
    ztodt = a_ztodt
    state => a_state
    taux => a_taux
    tauy => a_tauy
    shflx => a_shflx
    cflx => a_cflx
    ustar => a_ustar
    obklen => a_obklen
    ptend => a_ptend
    cldn => a_cldn
    ocnfrac => a_ocnfrac
    landfrac => a_landfrac
    sgh => a_sgh
    pbuf => a_pbuf
  end subroutine driver_bind

  subroutine driver_piece_1()
    ! vertical_diffusion.F90:816-834, verbatim

        rztodt = 1._r8 / ztodt
        lchnk  = state%lchnk
        ncol   = state%ncol

        call pbuf_get_field(pbuf, tauresx_idx,  tauresx)
        call pbuf_get_field(pbuf, tauresy_idx,  tauresy)
        call pbuf_get_field(pbuf, tpert_idx,    tpert)
        call pbuf_get_field(pbuf, qpert_idx,    qpert)
        call pbuf_get_field(pbuf, pblh_idx,     pblh)
        call pbuf_get_field(pbuf, turbtype_idx, turbtype)

        ! ---------------------------------------- !
        ! Computation of turbulent mountain stress !
        ! ---------------------------------------- !

        ! Consistent with the computation of 'normal' drag coefficient, we are using
        ! the raw input (u,v) to compute 'ksrftms', not the provisionally-marched 'u,v'
        ! within the iteration loop of the PBL scheme.


  end subroutine driver_piece_1

  subroutine driver_piece_2()
    ! vertical_diffusion.F90:840-847, verbatim

          ! Here, both 'taux, tautmsx' are explicit surface stresses.
          ! Note that this 'tautotx, tautoty' are different from the total stress
          ! that has been actually added into the atmosphere. This is because both
          ! taux and tautmsx are fully implicitly treated within compute_vdiff.
          ! However, 'tautotx, tautoty' are not used in the actual numerical
          ! computation in this module.
            tautotx(:ncol) = taux(:ncol) + tautmsx(:ncol)
            tautoty(:ncol) = tauy(:ncol) + tautmsy(:ncol)

  end subroutine driver_piece_2

  subroutine driver_piece_3()
    ! vertical_diffusion.F90:849-851, verbatim

            ksrftms(:ncol) = 0._r8
            tautotx(:ncol) = taux(:ncol)
            tautoty(:ncol) = tauy(:ncol)

  end subroutine driver_piece_3

  subroutine driver_piece_4()
    ! vertical_diffusion.F90:853-861, verbatim


        !----------------------------------------------------------------------- !
        !   Computation of eddy diffusivities - Select appropriate PBL scheme    !
        !----------------------------------------------------------------------- !
        call pbuf_get_field(pbuf, kvm_idx,  kvm_in)
        call pbuf_get_field(pbuf, kvh_idx,  kvh_in)
        call pbuf_get_field(pbuf, smaw_idx, smaw)
        call pbuf_get_field(pbuf, tke_idx,  tke)


  end subroutine driver_piece_4

  subroutine driver_piece_5()
    ! vertical_diffusion.F90:864-894, verbatim


           ! ---------------------------------------------------------------- !
           ! At first time step, have eddy_diff.F90:caleddy() use kvh=kvm=kvf !
           ! This has to be done in compute_eddy_diff after kvf is calculated !
           ! ---------------------------------------------------------------- !

           if( is_first_step() ) then
               kvinit = .true.
           else
               kvinit = .false.
           endif

           ! ---------------------------------------------- !
           ! Get LW radiative heating out of physics buffer !
           ! ---------------------------------------------- !
           call pbuf_get_field(pbuf, qrl_idx,   qrl)

           call pbuf_get_field(pbuf, wsedl_idx, wsedl)

           ! These fields are put into the pbuf for UNICON only.
           if (trim(shallow_scheme) == 'UNICON') then
              call pbuf_get_field(pbuf, bprod_idx,    bprod)
              call pbuf_get_field(pbuf, ipbl_idx,     ipbl)
              call pbuf_get_field(pbuf, kpblh_idx,    kpblh)
              call pbuf_get_field(pbuf, wstarPBL_idx, wstarPBL)
              call pbuf_get_field(pbuf, tkes_idx,     tkes)
              call pbuf_get_field(pbuf, went_idx,     went)
           else
              allocate(bprod(pcols,pverp), ipbl(pcols), kpblh(pcols), wstarPBL(pcols), tkes(pcols), went(pcols))
           end if


  end subroutine driver_piece_5

  subroutine driver_piece_6()
    ! vertical_diffusion.F90:908-965, verbatim


           ! The diag_TKE scheme does not calculate the Monin-Obukhov length, which is used in dry deposition calculations.
           ! Use the routines from pbl_utils to accomplish this. Assumes ustar and rrho have been set.
           th(:ncol,pver) = state%t(:ncol,pver) * state%exner(:ncol,pver)
           thvs(:ncol) = virtem(th(:ncol,pver),state%q(:ncol,pver,1))
           call calc_obklen(th(:ncol,pver), thvs(:ncol), cflx(:ncol,1), shflx(:ncol), rrho(:ncol), ustar(:ncol), &
                            khfs(:ncol),    kqfs(:ncol), kbfs(:ncol),   obklen(:ncol))

           ! ----------------------------------------------- !
           ! Store TKE in pbuf for use by shallow convection !
           ! ----------------------------------------------- !

           tpertPBL(:ncol) = tpert(:ncol)
           qpertPBL(:ncol) = qpert(:ncol)


           ! The diffusivities from diag_TKE can be much larger than from HB in the free
           ! troposphere and upper atmosphere. These seem to be larger than observations,
           ! and in WACCM the gw_drag code is already applying an eddy diffusivity in the
           ! upper atmosphere. Optionally, adjust the diffusivities in the free troposphere
           ! or the upper atmosphere.
           !
           ! NOTE: Further investigation should be done as to why the diffusivities are
           ! larger in diag_TKE.
           if ((kv_freetrop_scale /= 1._r8) .or. ((kv_top_scale /= 1._r8) .and. (kv_top_pressure > 0._r8))) then
             do i = 1, ncol
               do k = 1, pverp

                 ! Outside of the boundary layer?
                 if (state%zi(i,k) > pblh(i)) then

                   ! In the upper atmosphere?
                   if (state%pint(i,k) <= kv_top_pressure) then
                     kvh(i,k) = kvh(i,k) * kv_top_scale
                     kvm(i,k) = kvm(i,k) * kv_top_scale
                     kvq(i,k) = kvq(i,k) * kv_top_scale
                   else
                     kvh(i,k) = kvh(i,k) * kv_freetrop_scale
                     kvm(i,k) = kvm(i,k) * kv_freetrop_scale
                     kvq(i,k) = kvq(i,k) * kv_freetrop_scale
                   end if
                 else
                   exit
                 end if
               end do
             end do
           end if

           ! Write out fields that are only used by this scheme

           call outfld( 'BPROD   ', bprod, pcols, lchnk )
           call outfld( 'SPROD   ', sprod, pcols, lchnk )
           call outfld( 'SFI     ', sfi,   pcols, lchnk )

           if (trim(shallow_scheme) /= 'UNICON') then
              deallocate(bprod, ipbl, kpblh, wstarPBL, tkes, went)
           end if


  end subroutine driver_piece_6

  subroutine driver_piece_7()
    ! vertical_diffusion.F90:987-1063, verbatim


        call outfld( 'ustar',   ustar(:), pcols, lchnk )
        call outfld( 'obklen', obklen(:), pcols, lchnk )

        ! kvh (in pbuf) is used by other physics parameterizations, and as an initial guess in compute_eddy_diff
        ! on the next timestep.  It is not updated by the compute_vdiff call below.
        call pbuf_set_field(pbuf, kvh_idx, kvh)

        ! kvm (in pbuf) is only used as an initial guess in compute_eddy_diff on the next timestep.
        ! The contributions for molecular diffusion made to kvm by the call to compute_vdiff below
        ! are not included in the pbuf as these are not needed in the initial guess by compute_eddy_diff.
        call pbuf_set_field(pbuf, kvm_idx, kvm)

        call outfld( 'WGUSTD' , wpert, pcols, lchnk )

        !------------------------------------ !
        !    Application of diffusivities     !
        !------------------------------------ !

        ! Set arrays from input state.
        q_tmp(:ncol,:,:) = state%q(:ncol,:,:)
        s_tmp(:ncol,:) = state%s(:ncol,:)
        u_tmp(:ncol,:) = state%u(:ncol,:)
        v_tmp(:ncol,:) = state%v(:ncol,:)

        !------------------------------------------------------ !
        ! Write profile output before applying diffusion scheme !
        !------------------------------------------------------ !

        sl_prePBL(:ncol,:pver)  = s_tmp(:ncol,:) -   latvap * q_tmp(:ncol,:,ixcldliq) &
                                                 - ( latvap + latice) * q_tmp(:ncol,:,ixcldice)
        qt_prePBL(:ncol,:pver)  = q_tmp(:ncol,:,1) + q_tmp(:ncol,:,ixcldliq) &
                                                   + q_tmp(:ncol,:,ixcldice)
        slv_prePBL(:ncol,:pver) = sl_prePBL(:ncol,:pver) * ( 1._r8 + zvir*qt_prePBL(:ncol,:pver) )

        call qsat(state%t(:ncol,:), state%pmid(:ncol,:), &
             tem2(:ncol,:), ftem(:ncol,:))
        ftem_prePBL(:ncol,:) = state%q(:ncol,:,1)/ftem(:ncol,:)*100._r8

        call outfld( 'qt_pre_PBL   ', qt_prePBL,                 pcols, lchnk )
        call outfld( 'sl_pre_PBL   ', sl_prePBL,                 pcols, lchnk )
        call outfld( 'slv_pre_PBL  ', slv_prePBL,                pcols, lchnk )
        call outfld( 'u_pre_PBL    ', state%u,                   pcols, lchnk )
        call outfld( 'v_pre_PBL    ', state%v,                   pcols, lchnk )
        call outfld( 'qv_pre_PBL   ', state%q(:ncol,:,1),        pcols, lchnk )
        call outfld( 'ql_pre_PBL   ', state%q(:ncol,:,ixcldliq), pcols, lchnk )
        call outfld( 'qi_pre_PBL   ', state%q(:ncol,:,ixcldice), pcols, lchnk )
        call outfld( 't_pre_PBL    ', state%t,                   pcols, lchnk )
        call outfld( 'rh_pre_PBL   ', ftem_prePBL,               pcols, lchnk )

        ! --------------------------------------------------------------------------------- !
        ! Call the diffusivity solver and solve diffusion equation                          !
        ! The final two arguments are optional function references to                       !
        ! constituent-independent and constituent-dependent moleculuar diffusivity routines !
        ! --------------------------------------------------------------------------------- !

        !------------------------------------------------------------------------
        !  Check to see if constituent dependent gas constant needed (WACCM-X)
        !------------------------------------------------------------------------
        if ( waccmx_is('ionosphere') .or. waccmx_is('neutral') ) then
          rairi(:ncol,1) = rairv(:ncol,1,lchnk)
          do k = 2, pver
            do i = 1, ncol
              rairi(i,k) = 0.5_r8 * (rairv(i,k,lchnk)+rairv(i,k-1,lchnk))
            end do
          end do
        else
          rairi(:ncol,:pver+1) = rair
        endif

        ! Modification : We may need to output 'tautotx_im,tautoty_im' from below 'compute_vdiff' and
        !                separately print out as diagnostic output, because these are different from
        !                the explicit 'tautotx, tautoty' computed above.
        ! Note that the output 'tauresx,tauresy' from below subroutines are fully implicit ones.

        call pbuf_get_field(pbuf, kvt_idx, kvt)


  end subroutine driver_piece_7

  subroutine driver_piece_8()
    ! vertical_diffusion.F90:1065-1065, verbatim



  end subroutine driver_piece_8

  subroutine driver_piece_9()
    ! vertical_diffusion.F90:1077-1080, verbatim


            call handle_errmsg(errstring, subname="compute_vdiff", &
                 extra_msg="Error in fieldlist_wet call from vertical_diffusion.")


  end subroutine driver_piece_9

  subroutine driver_piece_10()
    ! vertical_diffusion.F90:1082-1082, verbatim



  end subroutine driver_piece_10

  subroutine driver_piece_11()
    ! vertical_diffusion.F90:1084-1089, verbatim


            if( do_molec_diff ) then
                errstring = "Design flaw: dry vdiff not currently supported with molecular diffusion"
                call endrun(errstring)
            end if


  end subroutine driver_piece_11

  subroutine driver_piece_12()
    ! vertical_diffusion.F90:1101-1104, verbatim


            call handle_errmsg(errstring, subname="compute_vdiff", &
                 extra_msg="Error in fieldlist_dry call from vertical_diffusion.")


  end subroutine driver_piece_12

  subroutine driver_piece_13()
    ! vertical_diffusion.F90:1106-1384, verbatim


        if (prog_modal_aero) then

           ! Modal aerosol species not diffused, so just add the explicit surface fluxes to the
           ! lowest layer

        tmp1(:ncol) = ztodt * gravit * state%rpdel(:ncol,pver)
           do m = 1, pmam_ncnst
              l = pmam_cnst_idx(m)
              q_tmp(:ncol,pver,l) = q_tmp(:ncol,pver,l) + tmp1(:ncol) * cflx(:ncol,l)
           enddo
        end if

        ! -------------------------------------------------------- !
        ! Diagnostics and output writing after applying PBL scheme !
        ! -------------------------------------------------------- !

        sl(:ncol,:pver)  = s_tmp(:ncol,:) -   latvap           * q_tmp(:ncol,:,ixcldliq) &
                                          - ( latvap + latice) * q_tmp(:ncol,:,ixcldice)
        qt(:ncol,:pver)  = q_tmp(:ncol,:,1) + q_tmp(:ncol,:,ixcldliq) &
                                        + q_tmp(:ncol,:,ixcldice)
        slv(:ncol,:pver) = sl(:ncol,:pver) * ( 1._r8 + zvir*qt(:ncol,:pver) )

        slflx(:ncol,1) = 0._r8
        qtflx(:ncol,1) = 0._r8
        uflx(:ncol,1)  = 0._r8
        vflx(:ncol,1)  = 0._r8

        slflx_cg(:ncol,1) = 0._r8
        qtflx_cg(:ncol,1) = 0._r8
        uflx_cg(:ncol,1)  = 0._r8
        vflx_cg(:ncol,1)  = 0._r8

        do k = 2, pver
           do i = 1, ncol
              rhoair     = state%pint(i,k) / ( rair * ( ( 0.5_r8*(slv(i,k)+slv(i,k-1)) - gravit*state%zi(i,k))/cpair ) )
              slflx(i,k) = kvh(i,k) * &
                              ( - rhoair*(sl(i,k-1)-sl(i,k))/(state%zm(i,k-1)-state%zm(i,k)) &
                                + cgh(i,k) )
              qtflx(i,k) = kvh(i,k) * &
                              ( - rhoair*(qt(i,k-1)-qt(i,k))/(state%zm(i,k-1)-state%zm(i,k)) &
                                + rhoair*(cflx(i,1)+cflx(i,ixcldliq)+cflx(i,ixcldice))*cgs(i,k) )
              uflx(i,k)  = kvm(i,k) * &
                              ( - rhoair*(u_tmp(i,k-1)-u_tmp(i,k))/(state%zm(i,k-1)-state%zm(i,k)))
              vflx(i,k)  = kvm(i,k) * &
                              ( - rhoair*(v_tmp(i,k-1)-v_tmp(i,k))/(state%zm(i,k-1)-state%zm(i,k)))
              slflx_cg(i,k) = kvh(i,k) * cgh(i,k)
              qtflx_cg(i,k) = kvh(i,k) * rhoair * ( cflx(i,1) + cflx(i,ixcldliq) + cflx(i,ixcldice) ) * cgs(i,k)
              uflx_cg(i,k)  = 0._r8
              vflx_cg(i,k)  = 0._r8
           end do
        end do

      ! Modification : I should check whether slflx(:ncol,pverp) is correctly computed.
      !                Note also that 'tautotx' is explicit total stress, different from
      !                the ones that have been actually added into the atmosphere.

        slflx(:ncol,pverp) = shflx(:ncol)
        qtflx(:ncol,pverp) = cflx(:ncol,1)
        uflx(:ncol,pverp)  = tautotx(:ncol)
        vflx(:ncol,pverp)  = tautoty(:ncol)

        slflx_cg(:ncol,pverp) = 0._r8
        qtflx_cg(:ncol,pverp) = 0._r8
        uflx_cg(:ncol,pverp)  = 0._r8
        vflx_cg(:ncol,pverp)  = 0._r8

        if (trim(shallow_scheme) == 'UNICON') then
           call pbuf_get_field(pbuf, qtl_flx_idx,  qtl_flx)
           call pbuf_get_field(pbuf, qti_flx_idx,  qti_flx)
           qtl_flx(:ncol,1) = 0._r8
           qti_flx(:ncol,1) = 0._r8
           do k = 2, pver
              do i = 1, ncol
                 ! For use in the cloud macrophysics
                 ! Note that density is not addd here. Also, only consider local transport term.
                 qtl_flx(i,k) = - kvh(i,k)*(q_tmp(i,k-1,1)-q_tmp(i,k,1)+q_tmp(i,k-1,ixcldliq)-q_tmp(i,k,ixcldliq))/&
                                           (state%zm(i,k-1)-state%zm(i,k))
                 qti_flx(i,k) = - kvh(i,k)*(q_tmp(i,k-1,1)-q_tmp(i,k,1)+q_tmp(i,k-1,ixcldice)-q_tmp(i,k,ixcldice))/&
                                           (state%zm(i,k-1)-state%zm(i,k))
              end do
           end do
           do i = 1, ncol
              rhoair = state%pint(i,pverp)/(rair*((slv(i,pver)-gravit*state%zi(i,pverp))/cpair))
              qtl_flx(i,pverp) = cflx(i,1)/rhoair
              qti_flx(i,pverp) = cflx(i,1)/rhoair
           end do
        end if

        ! --------------------------------------------------------------- !
        ! Convert the new profiles into vertical diffusion tendencies.    !
        ! Convert KE dissipative heat change into "temperature" tendency. !
        ! --------------------------------------------------------------- !

        ! All variables are modified by vertical diffusion

        lq(:) = .TRUE.
        call physics_ptend_init(ptend,state%psetcols, "vertical diffusion", &
             ls=.true., lu=.true., lv=.true., lq=lq)

        ptend%s(:ncol,:)       = ( s_tmp(:ncol,:) - state%s(:ncol,:) ) * rztodt
        ptend%u(:ncol,:)       = ( u_tmp(:ncol,:) - state%u(:ncol,:) ) * rztodt
        ptend%v(:ncol,:)       = ( v_tmp(:ncol,:) - state%v(:ncol,:) ) * rztodt
        ptend%q(:ncol,:pver,:) = ( q_tmp(:ncol,:pver,:) - state%q(:ncol,:pver,:) ) * rztodt
        slten(:ncol,:)         = ( sl(:ncol,:) - sl_prePBL(:ncol,:) ) * rztodt
        qtten(:ncol,:)         = ( qt(:ncol,:) - qt_prePBL(:ncol,:) ) * rztodt

        ! ----------------------------------------------------------- !
        ! In order to perform 'pseudo-conservative varible diffusion' !
        ! perform the following two stages:                           !
        !                                                             !
        ! I.  Re-set (1) 'qvten' by 'qtten', and 'qlten = qiten = 0'  !
        !            (2) 'sten'  by 'slten', and                      !
        !            (3) 'qlten = qiten = 0'                          !
        !                                                             !
        ! II. Apply 'positive_moisture'                               !
        !                                                             !
        ! ----------------------------------------------------------- !

        if( eddy_scheme .eq. 'diag_TKE' .and. do_pseudocon_diff ) then

             ptend%q(:ncol,:pver,1) = qtten(:ncol,:pver)
             ptend%s(:ncol,:pver)   = slten(:ncol,:pver)
             ptend%q(:ncol,:pver,ixcldliq) = 0._r8
             ptend%q(:ncol,:pver,ixcldice) = 0._r8
             ptend%q(:ncol,:pver,ixnumliq) = 0._r8
             ptend%q(:ncol,:pver,ixnumice) = 0._r8

             do i = 1, ncol
                do k = 1, pver
                   qv_pro(i,k) = state%q(i,k,1)        + ptend%q(i,k,1)             * ztodt
                   ql_pro(i,k) = state%q(i,k,ixcldliq) + ptend%q(i,k,ixcldliq)      * ztodt
                   qi_pro(i,k) = state%q(i,k,ixcldice) + ptend%q(i,k,ixcldice)      * ztodt
                   s_pro(i,k)  = state%s(i,k)          + ptend%s(i,k)               * ztodt
                   t_pro(i,k)  = state%t(i,k)          + (1._r8/cpair)*ptend%s(i,k) * ztodt
                end do
             end do

             call positive_moisture( cpair, latvap, latvap+latice, ncol, pver, ztodt, qmin(1), qmin(ixcldliq), qmin(ixcldice),    &
                                     state%pdel(:ncol,pver:1:-1), qv_pro(:ncol,pver:1:-1), ql_pro(:ncol,pver:1:-1), &
                                     qi_pro(:ncol,pver:1:-1), t_pro(:ncol,pver:1:-1), s_pro(:ncol,pver:1:-1),       &
                                     ptend%q(:ncol,pver:1:-1,1), ptend%q(:ncol,pver:1:-1,ixcldliq),                 &
                                     ptend%q(:ncol,pver:1:-1,ixcldice), ptend%s(:ncol,pver:1:-1) )

        end if

        ! ----------------------------------------------------------------- !
        ! Re-calculate diagnostic output variables after vertical diffusion !
        ! ----------------------------------------------------------------- !

        qv_aft_PBL(:ncol,:pver)  =   state%q(:ncol,:pver,1)         + ptend%q(:ncol,:pver,1)        * ztodt
        ql_aft_PBL(:ncol,:pver)  =   state%q(:ncol,:pver,ixcldliq)  + ptend%q(:ncol,:pver,ixcldliq) * ztodt
        qi_aft_PBL(:ncol,:pver)  =   state%q(:ncol,:pver,ixcldice)  + ptend%q(:ncol,:pver,ixcldice) * ztodt
        s_aft_PBL(:ncol,:pver)   =   state%s(:ncol,:pver)           + ptend%s(:ncol,:pver)          * ztodt
        t_aftPBL(:ncol,:pver)    = ( s_aft_PBL(:ncol,:pver) - gravit*state%zm(:ncol,:pver) ) / cpair

        u_aft_PBL(:ncol,:pver)   =  state%u(:ncol,:pver)          + ptend%u(:ncol,:pver)            * ztodt
        v_aft_PBL(:ncol,:pver)   =  state%v(:ncol,:pver)          + ptend%v(:ncol,:pver)            * ztodt

        call qsat(t_aftPBL(:ncol,:pver), state%pmid(:ncol,:pver), &
             tem2(:ncol,:pver), ftem(:ncol,:pver))
        ftem_aftPBL(:ncol,:pver) = qv_aft_PBL(:ncol,:pver) / ftem(:ncol,:pver) * 100._r8

        tten(:ncol,:pver)        = ( t_aftPBL(:ncol,:pver)    - state%t(:ncol,:pver) )              * rztodt
        rhten(:ncol,:pver)       = ( ftem_aftPBL(:ncol,:pver) - ftem_prePBL(:ncol,:pver) )          * rztodt

        ! -------------------------------------------------------------- !
        ! mass conservation check.........
        ! -------------------------------------------------------------- !
        if (diff_cnsrv_mass_check) then

           ! Conservation check
           nstep = get_nstep()

           do m = 1, pcnst
              fixed_ubc: if ((.not.cnst_fixed_ubc(m)).and.(.not.cnst_fixed_ubflx(m))) then
                 col_loop: do i = 1, ncol
                    sum1 = 0._r8
                    sum2 = 0._r8
                    sum3 = 0._r8
                    do k = 1, pver
                       if(cnst_get_type_byind(m).eq.'wet') then
                          pdelx = state%pdel(i,k)
                       else
                          pdelx = state%pdeldry(i,k)
                       endif
                       sum1 = sum1 + state%q(i,k,m)*pdelx/gravit                          ! total column
                       sum2 = sum2 +(state%q(i,k,m)+ptend%q(i,k,m)*ztodt)*pdelx/ gravit   ! total column after tendancy is applied
                       sum3 = sum3 +(               ptend%q(i,k,m)*ztodt)*pdelx/ gravit   ! rate of change in column
                    enddo
                    sum1 = sum1 + (cflx(i,m) * ztodt) ! add in surface flux (kg/m2)
                    sflx = (cflx(i,m) * ztodt)
                    if (sum1>1.e-36_r8) then
                       if( abs((sum2-sum1)/sum1) .gt. 1.e-12_r8  ) then
                          write(iulog,'(a,a8,a,I4,2f8.3,5e25.16)') &
                               'MASSCHECK vert diff : nstep,lon,lat,mass1,mass2,sum3,sflx,rel-diff : ', &
                               trim(cnst_name(m)), ' : ', nstep, state%lon(i)*180._r8/pi, state%lat(i)*180._r8/pi, &
                               sum1, sum2, sum3, sflx, abs(sum2-sum1)/sum1
                          call endrun('vertical_diffusion_tend : mass not conserved' )
                       endif
                    endif
                 enddo col_loop
              endif fixed_ubc
           enddo
        endif

        ! -------------------------------------------------------------- !
        ! Writing state variables after PBL scheme for detailed analysis !
        ! -------------------------------------------------------------- !

        call outfld( 'sl_aft_PBL'   , sl,                        pcols, lchnk )
        call outfld( 'qt_aft_PBL'   , qt,                        pcols, lchnk )
        call outfld( 'slv_aft_PBL'  , slv,                       pcols, lchnk )
        call outfld( 'u_aft_PBL'    , u_aft_PBL,                 pcols, lchnk )
        call outfld( 'v_aft_PBL'    , v_aft_PBL,                 pcols, lchnk )
        call outfld( 'qv_aft_PBL'   , qv_aft_PBL,                pcols, lchnk )
        call outfld( 'ql_aft_PBL'   , ql_aft_PBL,                pcols, lchnk )
        call outfld( 'qi_aft_PBL'   , qi_aft_PBL,                pcols, lchnk )
        call outfld( 't_aft_PBL '   , t_aftPBL,                  pcols, lchnk )
        call outfld( 'rh_aft_PBL'   , ftem_aftPBL,               pcols, lchnk )
        call outfld( 'slflx_PBL'    , slflx,                     pcols, lchnk )
        call outfld( 'qtflx_PBL'    , qtflx,                     pcols, lchnk )
        call outfld( 'uflx_PBL'     , uflx,                      pcols, lchnk )
        call outfld( 'vflx_PBL'     , vflx,                      pcols, lchnk )
        call outfld( 'slflx_cg_PBL' , slflx_cg,                  pcols, lchnk )
        call outfld( 'qtflx_cg_PBL' , qtflx_cg,                  pcols, lchnk )
        call outfld( 'uflx_cg_PBL'  , uflx_cg,                   pcols, lchnk )
        call outfld( 'vflx_cg_PBL'  , vflx_cg,                   pcols, lchnk )
        call outfld( 'slten_PBL'    , slten,                     pcols, lchnk )
        call outfld( 'qtten_PBL'    , qtten,                     pcols, lchnk )
        call outfld( 'uten_PBL'     , ptend%u(:ncol,:),          pcols, lchnk )
        call outfld( 'vten_PBL'     , ptend%v(:ncol,:),          pcols, lchnk )
        call outfld( 'qvten_PBL'    , ptend%q(:ncol,:,1),        pcols, lchnk )
        call outfld( 'qlten_PBL'    , ptend%q(:ncol,:,ixcldliq), pcols, lchnk )
        call outfld( 'qiten_PBL'    , ptend%q(:ncol,:,ixcldice), pcols, lchnk )
        call outfld( 'tten_PBL'     , tten,                      pcols, lchnk )
        call outfld( 'rhten_PBL'    , rhten,                     pcols, lchnk )

        ! ------------------------------------------- !
        ! Writing the other standard output variables !
        ! ------------------------------------------- !

        call outfld( 'QT'           , qt,                        pcols, lchnk )
        call outfld( 'SL'           , sl,                        pcols, lchnk )
        call outfld( 'SLV'          , slv,                       pcols, lchnk )
        call outfld( 'SLFLX'        , slflx,                     pcols, lchnk )
        call outfld( 'QTFLX'        , qtflx,                     pcols, lchnk )
        call outfld( 'UFLX'         , uflx,                      pcols, lchnk )
        call outfld( 'VFLX'         , vflx,                      pcols, lchnk )
        call outfld( 'TKE'          , tke,                       pcols, lchnk )

        call outfld( 'PBLH'         , pblh,                      pcols, lchnk )
        call outfld( 'TPERT'        , tpert,                     pcols, lchnk )
        call outfld( 'QPERT'        , qpert,                     pcols, lchnk )
        call outfld( 'USTAR'        , ustar,                     pcols, lchnk )
        call outfld( 'KVH'          , kvh,                       pcols, lchnk )
        call outfld( 'KVT'          , kvt,                       pcols, lchnk )
        call outfld( 'KVM'          , kvm,                       pcols, lchnk )
        call outfld( 'CGS'          , cgs,                       pcols, lchnk )
        dtk(:ncol,:) = dtk(:ncol,:) / cpair              ! Normalize heating for history
        call outfld( 'DTVKE'        , dtk,                       pcols, lchnk )
        dtk(:ncol,:) = ptend%s(:ncol,:) / cpair          ! Normalize heating for history using dtk
        call outfld( 'DTV'          , dtk,                       pcols, lchnk )
        call outfld( 'DUV'          , ptend%u,                   pcols, lchnk )
        call outfld( 'DVV'          , ptend%v,                   pcols, lchnk )
        do m = 1, pcnst
           call outfld( vdiffnam(m) , ptend%q(1,1,m),            pcols, lchnk )
        end do
        if( do_tms ) then
          ! Here, 'tautmsx,tautmsy' are implicit 'tms' that have been actually
          ! added into the atmosphere.
            call outfld( 'TAUTMSX'  , tautmsx,                   pcols, lchnk )
            call outfld( 'TAUTMSY'  , tautmsy,                   pcols, lchnk )
        end if
        if( do_molec_diff ) then
            call outfld( 'TTPXMLC'  , topflx,                    pcols, lchnk )
        end if

        return

  end subroutine driver_piece_13

  subroutine compute_tms_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
    ! the paused `call compute_tms( pcols , pver , ncol , state%u , state%v , state%t , ...` in the callee's argument order
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer(c_int), intent(out) :: ncol_out
    integer(c_int32_t), save, target :: sc_1
    integer(c_int32_t), save, target :: sc_2
    integer(c_int32_t), save, target :: sc_3
    ncol_out = int(ncol, c_int)
    sc_1 = int(pcols, c_int32_t)
    call put_slot(1, c_loc(sc_1), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_2 = int(pver, c_int32_t)
    call put_slot(2, c_loc(sc_2), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_3 = int(ncol, c_int32_t)
    call put_slot(3, c_loc(sc_3), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(4, c_loc(state%u(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(5, c_loc(state%v(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(6, c_loc(state%t(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(7, c_loc(state%pmid(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(8, c_loc(state%exner(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(9, c_loc(state%zm(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(10, c_loc(sgh(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(11, c_loc(ksrftms(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(12, c_loc(tautmsx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(13, c_loc(tautmsy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(14, c_loc(landfrac(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
  end subroutine compute_tms_frame

  subroutine compute_tms_original()
    ! the original call, vertical_diffusion.F90:836-839, verbatim
            call compute_tms( pcols      , pver     , ncol    ,              &
                              state%u    , state%v  , state%t , state%pmid , &
                              state%exner, state%zm , sgh     , ksrftms    , &
                              tautmsx    , tautmsy  , landfrac )
  end subroutine compute_tms_original

  subroutine compute_eddy_diff_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
    ! the paused `call compute_eddy_diff( lchnk , pcols , pver , ncol , state%t , state%...` in the callee's argument order
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer(c_int), intent(out) :: ncol_out
    integer(c_int32_t), save, target :: sc_1
    integer(c_int32_t), save, target :: sc_2
    integer(c_int32_t), save, target :: sc_3
    integer(c_int32_t), save, target :: sc_4
    real(c_double), save, target :: sc_5
    integer(c_int32_t), save, target :: sc_6
    integer(c_int32_t), save, target :: sc_7
    integer(c_int32_t), save, target :: sc_8
    ncol_out = int(ncol, c_int)
    sc_1 = int(lchnk, c_int32_t)
    call put_slot(1, c_loc(sc_1), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_2 = int(pcols, c_int32_t)
    call put_slot(2, c_loc(sc_2), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_3 = int(pver, c_int32_t)
    call put_slot(3, c_loc(sc_3), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_4 = int(ncol, c_int32_t)
    call put_slot(4, c_loc(sc_4), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(5, c_loc(state%t(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(6, c_loc(state%q(1,1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_5 = real(ztodt, c_double)
    call put_slot(7, c_loc(sc_5), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(8, c_loc(state%q(1,1,ixcldliq)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(9, c_loc(state%q(1,1,ixcldice)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(10, c_loc(state%s(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(11, c_loc(state%pdel(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(12, c_loc(state%rpdel(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(13, c_loc(cldn(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    if (associated(qrl)) then
      call put_slot(14, c_loc(qrl(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(14, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(wsedl)) then
      call put_slot(15, c_loc(wsedl(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(15, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(16, c_loc(state%zm(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(17, c_loc(state%zi(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(18, c_loc(state%pmid(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(19, c_loc(state%pint(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(20, c_loc(state%u(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(21, c_loc(state%v(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(22, c_loc(taux(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(23, c_loc(tauy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(24, c_loc(shflx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(25, c_loc(cflx(1,1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_6 = int(merge(1, 0, wstarent), c_int32_t)
    call put_slot(26, c_loc(sc_6), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_7 = int(nturb, c_int32_t)
    call put_slot(27, c_loc(sc_7), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(28, c_loc(rrho(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(29, c_loc(ustar(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    if (associated(pblh)) then
      call put_slot(30, c_loc(pblh(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(30, 1, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(kvm_in)) then
      call put_slot(31, c_loc(kvm_in(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(31, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(kvh_in)) then
      call put_slot(32, c_loc(kvh_in(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(32, 2, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(33, c_loc(kvm(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(34, c_loc(kvh(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(35, c_loc(kvq(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(36, c_loc(cgh(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(37, c_loc(cgs(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    if (associated(tpert)) then
      call put_slot(38, c_loc(tpert(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(38, 1, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(qpert)) then
      call put_slot(39, c_loc(qpert(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(39, 1, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(40, c_loc(wpert(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    if (associated(tke)) then
      call put_slot(41, c_loc(tke(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(41, 2, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(bprod)) then
      call put_slot(42, c_loc(bprod(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(42, 2, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(43, c_loc(sprod(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(44, c_loc(sfi(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    sc_8 = int(merge(1, 0, kvinit), c_int32_t)
    call put_slot(45, c_loc(sc_8), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    if (associated(tauresx)) then
      call put_slot(46, c_loc(tauresx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(46, 1, 1, 2, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(tauresy)) then
      call put_slot(47, c_loc(tauresy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(47, 1, 1, 2, ptrs, ndims, shapes, dtypes, intents)
    end if
    call put_slot(48, c_loc(ksrftms(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    if (associated(ipbl)) then
      call put_slot(49, c_loc(ipbl(1)), 1, (/ int((pcols), c_int64_t) /), 2, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(49, 1, 2, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(kpblh)) then
      call put_slot(50, c_loc(kpblh(1)), 1, (/ int((pcols), c_int64_t) /), 2, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(50, 1, 2, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(wstarPBL)) then
      call put_slot(51, c_loc(wstarPBL(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(51, 1, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(tkes)) then
      call put_slot(52, c_loc(tkes(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(52, 1, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(went)) then
      call put_slot(53, c_loc(went(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(53, 1, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(turbtype)) then
      call put_slot(54, c_loc(turbtype(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 2, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(54, 2, 2, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(smaw)) then
      call put_slot(55, c_loc(smaw(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(55, 2, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
  end subroutine compute_eddy_diff_frame

  subroutine compute_eddy_diff_original()
    ! the original call, vertical_diffusion.F90:895-907, verbatim
           call compute_eddy_diff( lchnk    ,                                                                    &
                                   pcols    , pver        , ncol       , state%t    , state%q(:,:,1) , ztodt   , &
                                   state%q(:,:,ixcldliq)  , state%q(:,:,ixcldice)   ,                            &
                                   state%s  , state%pdel  , state%rpdel, cldn       , qrl            , wsedl   , &
                                   state%zm , state%zi    , state%pmid , state%pint , state%u        , state%v , &
                                   taux     , tauy        , shflx      , cflx(:,1)  , wstarent       , nturb   , &
                                   rrho     , ustar       , pblh       , kvm_in     , kvh_in         , kvm     , &
                                   kvh      , kvq         , cgh        ,                                         &
                                   cgs      , tpert       , qpert      , wpert      , tke            , bprod   , &
                                   sprod    , sfi         , kvinit     ,                                         &
                                   tauresx  , tauresy     , ksrftms    ,                                         &
                                   ipbl     , kpblh       , wstarPBL   , tkes       , went           , turbtype, &
                                   smaw )
  end subroutine compute_eddy_diff_original

  subroutine compute_vdiff_1_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
    ! the paused `call compute_vdiff( state%lchnk , pcols , pver , pcnst , ncol , state%...` in the callee's argument order
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer(c_int), intent(out) :: ncol_out
    integer(c_int32_t), save, target :: sc_1
    integer(c_int32_t), save, target :: sc_2
    integer(c_int32_t), save, target :: sc_3
    integer(c_int32_t), save, target :: sc_4
    integer(c_int32_t), save, target :: sc_5
    real(c_double), save, target :: sc_6
    integer(c_int32_t), save, target :: sc_7
    integer(c_int32_t), save, target :: sc_8
    integer(c_int32_t), save, target :: sc_9
    integer(c_int32_t), save, target :: sc_10
    type(c_ptr) :: address
    ncol_out = int(ncol, c_int)
    sc_1 = int(state%lchnk, c_int32_t)
    call put_slot(1, c_loc(sc_1), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_2 = int(pcols, c_int32_t)
    call put_slot(2, c_loc(sc_2), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_3 = int(pver, c_int32_t)
    call put_slot(3, c_loc(sc_3), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_4 = int(pcnst, c_int32_t)
    call put_slot(4, c_loc(sc_4), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_5 = int(ncol, c_int32_t)
    call put_slot(5, c_loc(sc_5), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(6, c_loc(state%pmid(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(7, c_loc(state%pint(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(8, c_loc(state%pdel(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(9, c_loc(state%rpdel(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(10, c_loc(state%t(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_6 = real(ztodt, c_double)
    call put_slot(11, c_loc(sc_6), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(12, c_loc(taux(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(13, c_loc(tauy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(14, c_loc(shflx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(15, c_loc(cflx(1,1)), 2, (/ int((pcols), c_int64_t), int((pcnst), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_7 = int(ntop, c_int32_t)
    call put_slot(16, c_loc(sc_7), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_8 = int(nbot, c_int32_t)
    call put_slot(17, c_loc(sc_8), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(18, c_loc(kvh(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(19, c_loc(kvm(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(20, c_loc(kvq(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(21, c_loc(cgs(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(22, c_loc(cgh(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(23, c_loc(state%zi(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(24, c_loc(ksrftms(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call slot_address_r8(qmincg(1), address)
    call put_slot(25, address, 1, (/ int((pcnst), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call empty_slot(26, 0, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call empty_slot(27, 0, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(28, c_loc(u_tmp(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(29, c_loc(v_tmp(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(30, c_loc(q_tmp(1,1,1)), 3, (/ int((pcols), c_int64_t), int((pver), c_int64_t), int((pcnst), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(31, c_loc(s_tmp(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(32, c_loc(tautmsx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(33, c_loc(tautmsy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(34, c_loc(dtk(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(35, c_loc(topflx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    if (associated(tauresx)) then
      call put_slot(36, c_loc(tauresx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(36, 1, 1, 2, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(tauresy)) then
      call put_slot(37, c_loc(tauresy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(37, 1, 1, 2, ptrs, ndims, shapes, dtypes, intents)
    end if
    sc_9 = int(1, c_int32_t)
    call put_slot(38, c_loc(sc_9), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call slot_address_r8_2(cpairv(:,:,state%lchnk), address)
    call put_slot(39, address, 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(40, c_loc(rairi(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_10 = int(merge(1, 0, do_molec_diff), c_int32_t)
    call put_slot(41, c_loc(sc_10), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    if (associated(kvt)) then
      call put_slot(42, c_loc(kvt(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(42, 2, 1, 1, ptrs, ndims, shapes, dtypes, intents)
    end if
  end subroutine compute_vdiff_1_frame

  subroutine compute_vdiff_1_original()
    ! the original call, vertical_diffusion.F90:1066-1076, verbatim
            call compute_vdiff( state%lchnk   ,                                                                     &
                                pcols         , pver               , pcnst        , ncol          , state%pmid    , &
                                state%pint    , state%pdel         , &
                                state%rpdel        , state%t      , ztodt         , taux          , &
                                tauy          , shflx              , cflx         , ntop          , nbot          , &
                                kvh           , kvm                , kvq          , cgs           , cgh           , &
                                state%zi      , ksrftms            , qmincg       , fieldlist_wet , fieldlist_molec,&
                                u_tmp         , v_tmp              , q_tmp        , s_tmp         ,                 &
                                tautmsx       , tautmsy            , dtk          , topflx        , errstring     , &
                                tauresx       , tauresy            , 1            , cpairv(:,:,state%lchnk), rairi, &
                                do_molec_diff , compute_molec_diff , vd_lu_qdecomp, kvt )
  end subroutine compute_vdiff_1_original

  subroutine compute_vdiff_2_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
    ! the paused `call compute_vdiff( state%lchnk , pcols , pver , pcnst , ncol , state%...` in the callee's argument order
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer(c_int), intent(out) :: ncol_out
    integer(c_int32_t), save, target :: sc_1
    integer(c_int32_t), save, target :: sc_2
    integer(c_int32_t), save, target :: sc_3
    integer(c_int32_t), save, target :: sc_4
    integer(c_int32_t), save, target :: sc_5
    real(c_double), save, target :: sc_6
    integer(c_int32_t), save, target :: sc_7
    integer(c_int32_t), save, target :: sc_8
    integer(c_int32_t), save, target :: sc_9
    integer(c_int32_t), save, target :: sc_10
    type(c_ptr) :: address
    ncol_out = int(ncol, c_int)
    sc_1 = int(state%lchnk, c_int32_t)
    call put_slot(1, c_loc(sc_1), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_2 = int(pcols, c_int32_t)
    call put_slot(2, c_loc(sc_2), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_3 = int(pver, c_int32_t)
    call put_slot(3, c_loc(sc_3), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_4 = int(pcnst, c_int32_t)
    call put_slot(4, c_loc(sc_4), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_5 = int(ncol, c_int32_t)
    call put_slot(5, c_loc(sc_5), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(6, c_loc(state%pmiddry(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(7, c_loc(state%pintdry(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(8, c_loc(state%pdeldry(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(9, c_loc(state%rpdeldry(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(10, c_loc(state%t(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_6 = real(ztodt, c_double)
    call put_slot(11, c_loc(sc_6), 0, zero_shape, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(12, c_loc(taux(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(13, c_loc(tauy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(14, c_loc(shflx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(15, c_loc(cflx(1,1)), 2, (/ int((pcols), c_int64_t), int((pcnst), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_7 = int(ntop, c_int32_t)
    call put_slot(16, c_loc(sc_7), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_8 = int(nbot, c_int32_t)
    call put_slot(17, c_loc(sc_8), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(18, c_loc(kvh(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(19, c_loc(kvm(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(20, c_loc(kvq(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(21, c_loc(cgs(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(22, c_loc(cgh(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(23, c_loc(state%zi(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(24, c_loc(ksrftms(1)), 1, (/ int((pcols), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call slot_address_r8(qmincg(1), address)
    call put_slot(25, address, 1, (/ int((pcnst), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call empty_slot(26, 0, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call empty_slot(27, 0, 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(28, c_loc(u_tmp(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(29, c_loc(v_tmp(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(30, c_loc(q_tmp(1,1,1)), 3, (/ int((pcols), c_int64_t), int((pver), c_int64_t), int((pcnst), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(31, c_loc(s_tmp(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(32, c_loc(tautmsx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(33, c_loc(tautmsy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(34, c_loc(dtk(1,1)), 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(35, c_loc(topflx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 1, ptrs, ndims, shapes, dtypes, intents)
    if (associated(tauresx)) then
      call put_slot(36, c_loc(tauresx(1)), 1, (/ int((pcols), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(36, 1, 1, 2, ptrs, ndims, shapes, dtypes, intents)
    end if
    if (associated(tauresy)) then
      call put_slot(37, c_loc(tauresy(1)), 1, (/ int((pcols), c_int64_t) /), 1, 2, ptrs, ndims, shapes, dtypes, intents)
    else
      call empty_slot(37, 1, 1, 2, ptrs, ndims, shapes, dtypes, intents)
    end if
    sc_9 = int(1, c_int32_t)
    call put_slot(38, c_loc(sc_9), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call slot_address_r8_2(cpairv(:,:,state%lchnk), address)
    call put_slot(39, address, 2, (/ int((pcols), c_int64_t), int((pver), c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    call put_slot(40, c_loc(rairi(1,1)), 2, (/ int((pcols), c_int64_t), int((pver)+1, c_int64_t) /), 1, 0, ptrs, ndims, shapes, dtypes, intents)
    sc_10 = int(merge(1, 0, do_molec_diff), c_int32_t)
    call put_slot(41, c_loc(sc_10), 0, zero_shape, 2, 0, ptrs, ndims, shapes, dtypes, intents)
    call empty_slot(42, 2, 1, 1, ptrs, ndims, shapes, dtypes, intents)
  end subroutine compute_vdiff_2_frame

  subroutine compute_vdiff_2_original()
    ! the original call, vertical_diffusion.F90:1090-1100, verbatim
            call compute_vdiff( state%lchnk   ,                                                                     &
                                pcols         , pver               , pcnst        , ncol          , state%pmiddry , &
                                state%pintdry , state%pdeldry      , &
                                state%rpdeldry     , state%t      , ztodt         , taux          , &
                                tauy          , shflx              , cflx         , ntop          , nbot          , &
                                kvh           , kvm                , kvq          , cgs           , cgh           , &
                                state%zi      , ksrftms            , qmincg       , fieldlist_dry , fieldlist_molec,&
                                u_tmp         , v_tmp              , q_tmp        , s_tmp         ,                 &
                                tautmsx       , tautmsy            , dtk          , topflx        , errstring     , &
                                tauresx       , tauresy            , 1            , cpairv(:,:,state%lchnk), rairi, &
                                do_molec_diff , compute_molec_diff , vd_lu_qdecomp )
  end subroutine compute_vdiff_2_original

  ! vertical_diffusion.F90:1391-1465: a private procedure of the module, verbatim
    subroutine positive_moisture( cp, xlv, xls, ncol, mkx, dt, qvmin, qlmin, qimin, &
                                  dp, qv, ql, qi, t, s, qvten, qlten, qiten, sten )
    ! ------------------------------------------------------------------------------- !
    ! If any 'ql < qlmin, qi < qimin, qv < qvmin' are developed in any layer,         !
    ! force them to be larger than minimum value by (1) condensating water vapor      !
    ! into liquid or ice, and (2) by transporting water vapor from the very lower     !
    ! layer. '2._r8' is multiplied to the minimum values for safety.                  !
    ! Update final state variables and tendencies associated with this correction.    !
    ! If any condensation happens, update (s,t) too.                                  !
    ! Note that (qv,ql,qi,t,s) are final state variables after applying corresponding !
    ! input tendencies.                                                               !
    ! Be careful the order of k : '1': near-surface layer, 'mkx' : top layer          !
    ! ------------------------------------------------------------------------------- !
      implicit none
      integer,  intent(in)     :: ncol, mkx
      real(r8), intent(in)     :: cp, xlv, xls
      real(r8), intent(in)     :: dt, qvmin, qlmin, qimin
      real(r8), intent(in)     :: dp(ncol,mkx)
      real(r8), intent(inout)  :: qv(ncol,mkx), ql(ncol,mkx), qi(ncol,mkx), t(ncol,mkx), s(ncol,mkx)
      real(r8), intent(inout)  :: qvten(ncol,mkx), qlten(ncol,mkx), qiten(ncol,mkx), sten(ncol,mkx)
      integer   i, k
      real(r8)  dql, dqi, dqv, sum, aa, dum

    ! Modification : I should check whether this is exactly same as the one used in
    !                shallow convection and cloud macrophysics.

      do i = 1, ncol
         do k = mkx, 1, -1    ! From the top to the 1st (lowest) layer from the surface
            dql        = max(0._r8,1._r8*qlmin-ql(i,k))
            dqi        = max(0._r8,1._r8*qimin-qi(i,k))
            qlten(i,k) = qlten(i,k) +  dql/dt
            qiten(i,k) = qiten(i,k) +  dqi/dt
            qvten(i,k) = qvten(i,k) - (dql+dqi)/dt
            sten(i,k)  = sten(i,k)  + xlv * (dql/dt) + xls * (dqi/dt)
            ql(i,k)    = ql(i,k) +  dql
            qi(i,k)    = qi(i,k) +  dqi
            qv(i,k)    = qv(i,k) -  dql - dqi
            s(i,k)     = s(i,k)  +  xlv * dql + xls * dqi
            t(i,k)     = t(i,k)  + (xlv * dql + xls * dqi)/cp
            dqv        = max(0._r8,1._r8*qvmin-qv(i,k))
            qvten(i,k) = qvten(i,k) + dqv/dt
            qv(i,k)    = qv(i,k)    + dqv
            if( k .ne. 1 ) then
                qv(i,k-1)    = qv(i,k-1)    - dqv*dp(i,k)/dp(i,k-1)
                qvten(i,k-1) = qvten(i,k-1) - dqv*dp(i,k)/dp(i,k-1)/dt
            endif
            qv(i,k) = max(qv(i,k),qvmin)
            ql(i,k) = max(ql(i,k),qlmin)
            qi(i,k) = max(qi(i,k),qimin)
         end do
         ! Extra moisture used to satisfy 'qv(i,1)=qvmin' is proportionally
         ! extracted from all the layers that has 'qv > 2*qvmin'. This fully
         ! preserves column moisture.
         if( dqv .gt. 1.e-20_r8 ) then
             sum = 0._r8
             do k = 1, mkx
                if( qv(i,k) .gt. 2._r8*qvmin ) sum = sum + qv(i,k)*dp(i,k)
             enddo
             aa = dqv*dp(i,1)/max(1.e-20_r8,sum)
             if( aa .lt. 0.5_r8 ) then
                 do k = 1, mkx
                    if( qv(i,k) .gt. 2._r8*qvmin ) then
                        dum        = aa*qv(i,k)
                        qv(i,k)    = qv(i,k) - dum
                        qvten(i,k) = qvten(i,k) - dum/dt
                    endif
                 enddo
             else
                 write(iulog,*) 'Full positive_moisture is impossible in vertical_diffusion'
             endif
         endif
      end do
      return

    end subroutine positive_moisture

  subroutine slot_address_r8(field, address)
    ! a TARGET dummy so c_loc is legal whatever the actual argument's attributes
    ! (a module array of the driver's own module, say); a contiguous actual is
    ! passed without a copy, and an element stands for the rest of its array
    real(r8), intent(inout), target :: field(*)
    type(c_ptr), intent(out) :: address
    address = c_loc(field(1))
  end subroutine slot_address_r8

  subroutine slot_address_i4(field, address)
    integer(c_int32_t), intent(inout), target :: field(*)
    type(c_ptr), intent(out) :: address
    address = c_loc(field(1))
  end subroutine slot_address_i4

  subroutine slot_address_r8_2(field, address)
    ! a section's address through an assumed-shape TARGET dummy; a contiguous
    ! section is passed without a copy
    real(r8), intent(inout), target :: field(:,:)
    type(c_ptr), intent(out) :: address
    address = c_loc(field(1,1))
  end subroutine slot_address_r8_2

  subroutine put_slot(index, address, rank, shape, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(in) :: address
    integer(c_int64_t), intent(in) :: shape(:)
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    integer :: axis
    ptrs(index) = address
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    do axis = 1, rank
      shapes(axis, index) = shape(axis)
    end do
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine put_slot

  subroutine empty_slot(index, rank, dtype, intent, ptrs, ndims, shapes, dtypes, intents)
    ! an argument with no storage in this call: a null address and zero extents
    integer, intent(in) :: index, rank, dtype, intent
    type(c_ptr), intent(inout) :: ptrs(:)
    integer(c_int), intent(inout) :: ndims(:), dtypes(:), intents(:)
    integer(c_int64_t), intent(inout) :: shapes(:,:)
    ptrs(index) = c_null_ptr
    ndims(index) = int(rank, c_int)
    shapes(:, index) = 0_c_int64_t
    dtypes(index) = int(dtype, c_int)
    intents(index) = int(intent, c_int)
  end subroutine empty_slot

end module pycam_vdiff_driver
