! Hooks: kernels reached inside compiled routines, their callers' references
! redirected at link time to these procedures.  Each counts its calls, calls the
! original when unarmed, and when armed hands Python the frame by yielding the
! stage's fiber.  Fortran never calls Python.
!
! GENERATED by tools/generate_pi_cam_hooks.py from native/pi_cam/hooks.yaml and
! the kernels' function contracts.  Do not edit by hand.
module pycam_hooks
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_loc, c_f_pointer, c_null_ptr, c_char, c_null_char
  implicit none
  private
  public :: pycam_hooks_arm_v1, pycam_hooks_counts_v1, pycam_hooks_paused_v1, pycam_hooks_frame_v1, &
            pycam_hooks_original_v1, pycam_hooks_reset_v1, pycam_hooks_count_v1, pycam_hooks_name_v1

  integer, parameter :: nhooks = 3
  integer(c_int), parameter :: ev_needs_kernel = 1_c_int
  integer, parameter :: max_slots = 29
  integer, parameter :: max_rank = 5
  character(len=*), parameter :: name_1 = 'cldfrc_fice'
  character(len=*), parameter :: name_2 = 'fluxbelowinv'
  character(len=*), parameter :: name_3 = 'instratus_condensate'

  logical, save :: armed(nhooks) = .false.
  integer(c_int64_t), save :: calls(nhooks) = 0_c_int64_t
  integer(c_int64_t), save :: paused(nhooks) = 0_c_int64_t
  integer(c_int64_t), save :: missed(nhooks) = 0_c_int64_t
  integer, save :: paused_hook = 0
  type(c_ptr), save :: frame_ptrs(max_slots)
  integer(c_int), save :: frame_ndims(max_slots) = 0_c_int, frame_dtypes(max_slots) = 0_c_int, frame_intents(max_slots) = 0_c_int
  integer(c_int64_t), save :: frame_shapes(max_rank, max_slots) = 0_c_int64_t
  integer(c_int), save :: frame_nslots = 0_c_int, frame_ncol = 0_c_int

  interface
    integer(c_int) function pycam_fiber_running_v1() bind(C, name='pycam_fiber_running_v1')
      import :: c_int
    end function pycam_fiber_running_v1
    subroutine pycam_fiber_yield_v1(event) bind(C, name='pycam_fiber_yield_v1')
      import :: c_int
      integer(c_int), value :: event
    end subroutine pycam_fiber_yield_v1
    subroutine fluxbelowinv_by_symbol(cbmf, ps0, mkx, kinv, dt, xsrc, xmean, xtopin, xbotin, xflx) bind(C, name='uwshcu_mp_fluxbelowinv_original_')
      import :: c_double, c_int, c_int64_t
      real(c_double), intent(in) :: cbmf
      real(c_double), intent(in) :: ps0(*)
      integer(c_int), intent(in) :: mkx
      integer(c_int), intent(in) :: kinv
      real(c_double), intent(in) :: dt
      real(c_double), intent(in) :: xsrc
      real(c_double), intent(in) :: xmean
      real(c_double), intent(in) :: xtopin
      real(c_double), intent(in) :: xbotin
      real(c_double), intent(out) :: xflx(*)
    end subroutine fluxbelowinv_by_symbol
    subroutine instratus_condensate_by_symbol(lchnk, ncol, k, p_in, t0_in, qv0_in, ql0_in, qi0_in, ni0_in, a_dc_in, ql_dc_in, qi_dc_in, a_sc_in, ql_sc_in, qi_sc_in, landfrac, snowh, rhmini_in, rhminl_in, rhminl_adj_land_in, rhminh_in, t_out, qv_out, ql_out, qi_out, al_st_out, ai_st_out, ql_st_out, qi_st_out) bind(C, name='cldwat2m_macro_mp_instratus_condensate_original_')
      import :: c_double, c_int, c_int64_t
      integer(c_int), intent(in) :: lchnk
      integer(c_int), intent(in) :: ncol
      integer(c_int), intent(in) :: k
      real(c_double), intent(in) :: p_in(*)
      real(c_double), intent(in) :: t0_in(*)
      real(c_double), intent(in) :: qv0_in(*)
      real(c_double), intent(in) :: ql0_in(*)
      real(c_double), intent(in) :: qi0_in(*)
      real(c_double), intent(in) :: ni0_in(*)
      real(c_double), intent(in) :: a_dc_in(*)
      real(c_double), intent(in) :: ql_dc_in(*)
      real(c_double), intent(in) :: qi_dc_in(*)
      real(c_double), intent(in) :: a_sc_in(*)
      real(c_double), intent(in) :: ql_sc_in(*)
      real(c_double), intent(in) :: qi_sc_in(*)
      real(c_double), intent(in) :: landfrac(*)
      real(c_double), intent(in) :: snowh(*)
      real(c_double), intent(in) :: rhmini_in(*)
      real(c_double), intent(in) :: rhminl_in(*)
      real(c_double), intent(in) :: rhminl_adj_land_in(*)
      real(c_double), intent(in) :: rhminh_in(*)
      real(c_double), intent(out) :: t_out(*)
      real(c_double), intent(out) :: qv_out(*)
      real(c_double), intent(out) :: ql_out(*)
      real(c_double), intent(out) :: qi_out(*)
      real(c_double), intent(out) :: al_st_out(*)
      real(c_double), intent(out) :: ai_st_out(*)
      real(c_double), intent(out) :: ql_st_out(*)
      real(c_double), intent(out) :: qi_st_out(*)
    end subroutine instratus_condensate_by_symbol
  end interface

contains

  subroutine hook_cldfrc_fice(ncol, t, fice, fsnow) bind(C, name='pycam_hook_cldfrc_fice_')
    ! cloud_fraction::cldfrc_fice, as its redirected callers call it; rename-references
    integer(c_int), intent(in), target :: ncol
    real(c_double), intent(in), target :: t(*)
    real(c_double), intent(out), target :: fice(*)
    real(c_double), intent(out), target :: fsnow(*)
    integer :: slot
    calls(1) = calls(1) + 1_c_int64_t
    if (.not. armed(1)) then
      call original_cldfrc_fice(ncol, t, fice, fsnow)
      return
    end if
    if (pycam_fiber_running_v1() == 0_c_int) then
      ! armed, yet not on the owning runner's fiber: the original answers, and the miss is counted
      missed(1) = missed(1) + 1_c_int64_t
      call original_cldfrc_fice(ncol, t, fice, fsnow)
      return
    end if
    paused(1) = paused(1) + 1_c_int64_t
    slot = 0
    frame_shapes = 0_c_int64_t
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ncol)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 2_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(t(1))
    frame_ndims(slot) = 2_c_int
    frame_shapes(1:2, slot) = (/ int(16, c_int64_t), int(30, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(fice(1))
    frame_ndims(slot) = 2_c_int
    frame_shapes(1:2, slot) = (/ int(16, c_int64_t), int(30, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(fsnow(1))
    frame_ndims(slot) = 2_c_int
    frame_shapes(1:2, slot) = (/ int(16, c_int64_t), int(30, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    frame_nslots = 4_c_int
    frame_ncol = int(ncol, c_int)
    paused_hook = 1
    call pycam_fiber_yield_v1(ev_needs_kernel)
    ! resumed: Python wrote the outputs (or ran the original on this frame); the call is done
    paused_hook = 0
  end subroutine hook_cldfrc_fice

  subroutine original_cldfrc_fice(ncol, t, fice, fsnow)
    use cloud_fraction, only: cldfrc_fice
    integer(c_int), intent(in) :: ncol
    real(c_double), intent(in) :: t(*)
    real(c_double), intent(out) :: fice(*)
    real(c_double), intent(out) :: fsnow(*)
    call cldfrc_fice(ncol, t, fice, fsnow)
  end subroutine original_cldfrc_fice

  subroutine hook_fluxbelowinv(cbmf, ps0, mkx, kinv, dt, xsrc, xmean, xtopin, xbotin, xflx) bind(C, name='uwshcu_mp_fluxbelowinv_')
    ! uwshcu::fluxbelowinv, as its redirected callers call it; weaken-definition
    real(c_double), intent(in), target :: cbmf
    real(c_double), intent(in), target :: ps0(*)
    integer(c_int), intent(in), target :: mkx
    integer(c_int), intent(in), target :: kinv
    real(c_double), intent(in), target :: dt
    real(c_double), intent(in), target :: xsrc
    real(c_double), intent(in), target :: xmean
    real(c_double), intent(in), target :: xtopin
    real(c_double), intent(in), target :: xbotin
    real(c_double), intent(out), target :: xflx(*)
    integer :: slot
    calls(2) = calls(2) + 1_c_int64_t
    if (.not. armed(2)) then
      call original_fluxbelowinv(cbmf, ps0, mkx, kinv, dt, xsrc, xmean, xtopin, xbotin, xflx)
      return
    end if
    if (pycam_fiber_running_v1() == 0_c_int) then
      ! armed, yet not on the owning runner's fiber: the original answers, and the miss is counted
      missed(2) = missed(2) + 1_c_int64_t
      call original_fluxbelowinv(cbmf, ps0, mkx, kinv, dt, xsrc, xmean, xtopin, xbotin, xflx)
      return
    end if
    paused(2) = paused(2) + 1_c_int64_t
    slot = 0
    frame_shapes = 0_c_int64_t
    slot = slot + 1
    frame_ptrs(slot) = c_loc(cbmf)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ps0(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(31, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(mkx)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 2_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(kinv)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 2_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(dt)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(xsrc)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(xmean)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(xtopin)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(xbotin)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(xflx(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(31, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    frame_nslots = 10_c_int
    frame_ncol = 0_c_int
    paused_hook = 2
    call pycam_fiber_yield_v1(ev_needs_kernel)
    ! resumed: Python wrote the outputs (or ran the original on this frame); the call is done
    paused_hook = 0
  end subroutine hook_fluxbelowinv

  subroutine original_fluxbelowinv(cbmf, ps0, mkx, kinv, dt, xsrc, xmean, xtopin, xbotin, xflx)
    real(c_double), intent(in) :: cbmf
    real(c_double), intent(in) :: ps0(*)
    integer(c_int), intent(in) :: mkx
    integer(c_int), intent(in) :: kinv
    real(c_double), intent(in) :: dt
    real(c_double), intent(in) :: xsrc
    real(c_double), intent(in) :: xmean
    real(c_double), intent(in) :: xtopin
    real(c_double), intent(in) :: xbotin
    real(c_double), intent(out) :: xflx(*)
    call fluxbelowinv_by_symbol(cbmf, ps0, mkx, kinv, dt, xsrc, xmean, xtopin, xbotin, xflx)
  end subroutine original_fluxbelowinv

  subroutine hook_instratus_condensate(lchnk, ncol, k, p_in, t0_in, qv0_in, ql0_in, qi0_in, ni0_in, a_dc_in, ql_dc_in, qi_dc_in, a_sc_in, ql_sc_in, qi_sc_in, landfrac, snowh, rhmini_in, rhminl_in, rhminl_adj_land_in, rhminh_in, t_out, qv_out, ql_out, qi_out, al_st_out, ai_st_out, ql_st_out, qi_st_out) bind(C, name='cldwat2m_macro_mp_instratus_condensate_')
    ! cldwat2m_macro::instratus_condensate, as its redirected callers call it; weaken-definition
    integer(c_int), intent(in), target :: lchnk
    integer(c_int), intent(in), target :: ncol
    integer(c_int), intent(in), target :: k
    real(c_double), intent(in), target :: p_in(*)
    real(c_double), intent(in), target :: t0_in(*)
    real(c_double), intent(in), target :: qv0_in(*)
    real(c_double), intent(in), target :: ql0_in(*)
    real(c_double), intent(in), target :: qi0_in(*)
    real(c_double), intent(in), target :: ni0_in(*)
    real(c_double), intent(in), target :: a_dc_in(*)
    real(c_double), intent(in), target :: ql_dc_in(*)
    real(c_double), intent(in), target :: qi_dc_in(*)
    real(c_double), intent(in), target :: a_sc_in(*)
    real(c_double), intent(in), target :: ql_sc_in(*)
    real(c_double), intent(in), target :: qi_sc_in(*)
    real(c_double), intent(in), target :: landfrac(*)
    real(c_double), intent(in), target :: snowh(*)
    real(c_double), intent(in), target :: rhmini_in(*)
    real(c_double), intent(in), target :: rhminl_in(*)
    real(c_double), intent(in), target :: rhminl_adj_land_in(*)
    real(c_double), intent(in), target :: rhminh_in(*)
    real(c_double), intent(out), target :: t_out(*)
    real(c_double), intent(out), target :: qv_out(*)
    real(c_double), intent(out), target :: ql_out(*)
    real(c_double), intent(out), target :: qi_out(*)
    real(c_double), intent(out), target :: al_st_out(*)
    real(c_double), intent(out), target :: ai_st_out(*)
    real(c_double), intent(out), target :: ql_st_out(*)
    real(c_double), intent(out), target :: qi_st_out(*)
    integer :: slot
    calls(3) = calls(3) + 1_c_int64_t
    if (.not. armed(3)) then
      call original_instratus_condensate(lchnk, ncol, k, p_in, t0_in, qv0_in, ql0_in, qi0_in, ni0_in, a_dc_in, ql_dc_in, qi_dc_in, a_sc_in, ql_sc_in, qi_sc_in, landfrac, snowh, rhmini_in, rhminl_in, rhminl_adj_land_in, rhminh_in, t_out, qv_out, ql_out, qi_out, al_st_out, ai_st_out, ql_st_out, qi_st_out)
      return
    end if
    if (pycam_fiber_running_v1() == 0_c_int) then
      ! armed, yet not on the owning runner's fiber: the original answers, and the miss is counted
      missed(3) = missed(3) + 1_c_int64_t
      call original_instratus_condensate(lchnk, ncol, k, p_in, t0_in, qv0_in, ql0_in, qi0_in, ni0_in, a_dc_in, ql_dc_in, qi_dc_in, a_sc_in, ql_sc_in, qi_sc_in, landfrac, snowh, rhmini_in, rhminl_in, rhminl_adj_land_in, rhminh_in, t_out, qv_out, ql_out, qi_out, al_st_out, ai_st_out, ql_st_out, qi_st_out)
      return
    end if
    paused(3) = paused(3) + 1_c_int64_t
    slot = 0
    frame_shapes = 0_c_int64_t
    slot = slot + 1
    frame_ptrs(slot) = c_loc(lchnk)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 2_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ncol)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 2_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(k)
    frame_ndims(slot) = 0_c_int
    frame_dtypes(slot) = 2_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(p_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(t0_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(qv0_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ql0_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(qi0_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ni0_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(a_dc_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ql_dc_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(qi_dc_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(a_sc_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ql_sc_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(qi_sc_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(landfrac(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(snowh(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(rhmini_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(rhminl_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(rhminl_adj_land_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(rhminh_in(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 0_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(t_out(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(qv_out(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ql_out(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(qi_out(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(al_st_out(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ai_st_out(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(ql_st_out(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    slot = slot + 1
    frame_ptrs(slot) = c_loc(qi_st_out(1))
    frame_ndims(slot) = 1_c_int
    frame_shapes(1:1, slot) = (/ int(16, c_int64_t) /)
    frame_dtypes(slot) = 1_c_int
    frame_intents(slot) = 1_c_int
    frame_nslots = 29_c_int
    frame_ncol = int(ncol, c_int)
    paused_hook = 3
    call pycam_fiber_yield_v1(ev_needs_kernel)
    ! resumed: Python wrote the outputs (or ran the original on this frame); the call is done
    paused_hook = 0
  end subroutine hook_instratus_condensate

  subroutine original_instratus_condensate(lchnk, ncol, k, p_in, t0_in, qv0_in, ql0_in, qi0_in, ni0_in, a_dc_in, ql_dc_in, qi_dc_in, a_sc_in, ql_sc_in, qi_sc_in, landfrac, snowh, rhmini_in, rhminl_in, rhminl_adj_land_in, rhminh_in, t_out, qv_out, ql_out, qi_out, al_st_out, ai_st_out, ql_st_out, qi_st_out)
    integer(c_int), intent(in) :: lchnk
    integer(c_int), intent(in) :: ncol
    integer(c_int), intent(in) :: k
    real(c_double), intent(in) :: p_in(*)
    real(c_double), intent(in) :: t0_in(*)
    real(c_double), intent(in) :: qv0_in(*)
    real(c_double), intent(in) :: ql0_in(*)
    real(c_double), intent(in) :: qi0_in(*)
    real(c_double), intent(in) :: ni0_in(*)
    real(c_double), intent(in) :: a_dc_in(*)
    real(c_double), intent(in) :: ql_dc_in(*)
    real(c_double), intent(in) :: qi_dc_in(*)
    real(c_double), intent(in) :: a_sc_in(*)
    real(c_double), intent(in) :: ql_sc_in(*)
    real(c_double), intent(in) :: qi_sc_in(*)
    real(c_double), intent(in) :: landfrac(*)
    real(c_double), intent(in) :: snowh(*)
    real(c_double), intent(in) :: rhmini_in(*)
    real(c_double), intent(in) :: rhminl_in(*)
    real(c_double), intent(in) :: rhminl_adj_land_in(*)
    real(c_double), intent(in) :: rhminh_in(*)
    real(c_double), intent(out) :: t_out(*)
    real(c_double), intent(out) :: qv_out(*)
    real(c_double), intent(out) :: ql_out(*)
    real(c_double), intent(out) :: qi_out(*)
    real(c_double), intent(out) :: al_st_out(*)
    real(c_double), intent(out) :: ai_st_out(*)
    real(c_double), intent(out) :: ql_st_out(*)
    real(c_double), intent(out) :: qi_st_out(*)
    call instratus_condensate_by_symbol(lchnk, ncol, k, p_in, t0_in, qv0_in, ql0_in, qi0_in, ni0_in, a_dc_in, ql_dc_in, qi_dc_in, a_sc_in, ql_sc_in, qi_sc_in, landfrac, snowh, rhmini_in, rhminl_in, rhminl_adj_land_in, rhminh_in, t_out, qv_out, ql_out, qi_out, al_st_out, ai_st_out, ql_st_out, qi_st_out)
  end subroutine original_instratus_condensate

  ! ------------------------------------------------------------------ !
  ! The ABI the runners and Python drive
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_hooks_count_v1() bind(C, name='pycam_hooks_count_v1') result(count)
    count = int(nhooks, c_int)
  end function pycam_hooks_count_v1

  integer(c_int) function pycam_hooks_name_v1(hook, buffer, length) bind(C, name='pycam_hooks_name_v1') result(status)
    integer(c_int), value, intent(in) :: hook, length
    character(kind=c_char), intent(out) :: buffer(*)
    character(len=64) :: name
    integer :: i
    status = 1_c_int
    if (hook < 1 .or. hook > nhooks) return
    select case (hook)
    case (1)
      name = name_1
    case (2)
      name = name_2
    case (3)
      name = name_3
    end select
    do i = 1, min(int(length) - 1, len_trim(name))
      buffer(i) = name(i:i)
    end do
    buffer(min(int(length), len_trim(name) + 1)) = c_null_char
    status = 0_c_int
  end function pycam_hooks_name_v1

  integer(c_int) function pycam_hooks_arm_v1(hook, flag) bind(C, name='pycam_hooks_arm_v1') result(status)
    ! arm (flag /= 0) or disarm one hook: the owning stage does this around its run
    integer(c_int), value, intent(in) :: hook, flag
    status = 1_c_int
    if (hook < 1 .or. hook > nhooks) return
    armed(hook) = flag /= 0_c_int
    status = 0_c_int
  end function pycam_hooks_arm_v1

  integer(c_int) function pycam_hooks_counts_v1(hook, calls_out, paused_out) bind(C, name='pycam_hooks_counts_v1') result(status)
    integer(c_int), value, intent(in) :: hook
    integer(c_int64_t), intent(out) :: calls_out, paused_out
    calls_out = 0_c_int64_t; paused_out = 0_c_int64_t
    status = 1_c_int
    if (hook < 1 .or. hook > nhooks) return
    calls_out = calls(hook); paused_out = paused(hook)
    status = 0_c_int
  end function pycam_hooks_counts_v1

  integer(c_int) function pycam_hooks_missed_v1(hook, missed_out) bind(C, name='pycam_hooks_missed_v1') result(status)
    ! calls that found the hook armed while no fiber was running: the original answered them
    integer(c_int), value, intent(in) :: hook
    integer(c_int64_t), intent(out) :: missed_out
    missed_out = 0_c_int64_t
    status = 1_c_int
    if (hook < 1 .or. hook > nhooks) return
    missed_out = missed(hook)
    status = 0_c_int
  end function pycam_hooks_missed_v1

  integer(c_int) function pycam_hooks_paused_v1() bind(C, name='pycam_hooks_paused_v1') result(hook)
    ! the hook suspended on the fiber now, or 0
    hook = int(paused_hook, c_int)
  end function pycam_hooks_paused_v1

  integer(c_int) function pycam_hooks_frame_v1(count, ptrs, ndims, shapes, dtypes, intents, ncol_out) &
       bind(C, name='pycam_hooks_frame_v1') result(status)
    ! the paused call's arguments in the callee's order, where they live
    integer(c_int), value, intent(in) :: count
    type(c_ptr), intent(out) :: ptrs(count)
    integer(c_int), intent(out) :: ndims(count), dtypes(count), intents(count), ncol_out
    integer(c_int64_t), intent(out) :: shapes(max_rank, count)
    integer :: slot
    status = 1_c_int
    ncol_out = 0_c_int
    if (paused_hook == 0) return
    if (count < frame_nslots) then
      status = 3_c_int; return
    end if
    do slot = 1, count
      ptrs(slot) = c_null_ptr; ndims(slot) = 0_c_int; dtypes(slot) = 0_c_int; intents(slot) = 0_c_int
      shapes(:, slot) = 0_c_int64_t
    end do
    do slot = 1, frame_nslots
      ptrs(slot) = frame_ptrs(slot); ndims(slot) = frame_ndims(slot)
      dtypes(slot) = frame_dtypes(slot); intents(slot) = frame_intents(slot)
      shapes(:, slot) = frame_shapes(:, slot)
    end do
    ncol_out = frame_ncol
    status = 0_c_int
  end function pycam_hooks_frame_v1

  integer(c_int) function pycam_hooks_original_v1() bind(C, name='pycam_hooks_original_v1') result(status)
    ! run the original on the paused frame, from the main context
    integer(c_int), pointer :: s1_i
    real(c_double), pointer :: p2_f2(:,:)
    real(c_double), pointer :: p3_f2(:,:)
    real(c_double), pointer :: p4_f2(:,:)
    real(c_double), pointer :: s1_f
    real(c_double), pointer :: p2_f1(:)
    integer(c_int), pointer :: s3_i
    integer(c_int), pointer :: s4_i
    real(c_double), pointer :: s5_f
    real(c_double), pointer :: s6_f
    real(c_double), pointer :: s7_f
    real(c_double), pointer :: s8_f
    real(c_double), pointer :: s9_f
    real(c_double), pointer :: p10_f1(:)
    integer(c_int), pointer :: s2_i
    real(c_double), pointer :: p4_f1(:)
    real(c_double), pointer :: p5_f1(:)
    real(c_double), pointer :: p6_f1(:)
    real(c_double), pointer :: p7_f1(:)
    real(c_double), pointer :: p8_f1(:)
    real(c_double), pointer :: p9_f1(:)
    real(c_double), pointer :: p11_f1(:)
    real(c_double), pointer :: p12_f1(:)
    real(c_double), pointer :: p13_f1(:)
    real(c_double), pointer :: p14_f1(:)
    real(c_double), pointer :: p15_f1(:)
    real(c_double), pointer :: p16_f1(:)
    real(c_double), pointer :: p17_f1(:)
    real(c_double), pointer :: p18_f1(:)
    real(c_double), pointer :: p19_f1(:)
    real(c_double), pointer :: p20_f1(:)
    real(c_double), pointer :: p21_f1(:)
    real(c_double), pointer :: p22_f1(:)
    real(c_double), pointer :: p23_f1(:)
    real(c_double), pointer :: p24_f1(:)
    real(c_double), pointer :: p25_f1(:)
    real(c_double), pointer :: p26_f1(:)
    real(c_double), pointer :: p27_f1(:)
    real(c_double), pointer :: p28_f1(:)
    real(c_double), pointer :: p29_f1(:)
    status = 1_c_int
    if (paused_hook == 0) return
    select case (paused_hook)
    case (1)
      call c_f_pointer(frame_ptrs(1), s1_i)
      call c_f_pointer(frame_ptrs(2), p2_f2, (/ 16, 30 /))
      call c_f_pointer(frame_ptrs(3), p3_f2, (/ 16, 30 /))
      call c_f_pointer(frame_ptrs(4), p4_f2, (/ 16, 30 /))
      call original_cldfrc_fice(s1_i, p2_f2, p3_f2, p4_f2)
    case (2)
      call c_f_pointer(frame_ptrs(1), s1_f)
      call c_f_pointer(frame_ptrs(2), p2_f1, (/ 31 /))
      call c_f_pointer(frame_ptrs(3), s3_i)
      call c_f_pointer(frame_ptrs(4), s4_i)
      call c_f_pointer(frame_ptrs(5), s5_f)
      call c_f_pointer(frame_ptrs(6), s6_f)
      call c_f_pointer(frame_ptrs(7), s7_f)
      call c_f_pointer(frame_ptrs(8), s8_f)
      call c_f_pointer(frame_ptrs(9), s9_f)
      call c_f_pointer(frame_ptrs(10), p10_f1, (/ 31 /))
      call original_fluxbelowinv(s1_f, p2_f1, s3_i, s4_i, s5_f, s6_f, s7_f, s8_f, s9_f, p10_f1)
    case (3)
      call c_f_pointer(frame_ptrs(1), s1_i)
      call c_f_pointer(frame_ptrs(2), s2_i)
      call c_f_pointer(frame_ptrs(3), s3_i)
      call c_f_pointer(frame_ptrs(4), p4_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(5), p5_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(6), p6_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(7), p7_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(8), p8_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(9), p9_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(10), p10_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(11), p11_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(12), p12_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(13), p13_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(14), p14_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(15), p15_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(16), p16_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(17), p17_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(18), p18_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(19), p19_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(20), p20_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(21), p21_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(22), p22_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(23), p23_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(24), p24_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(25), p25_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(26), p26_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(27), p27_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(28), p28_f1, (/ 16 /))
      call c_f_pointer(frame_ptrs(29), p29_f1, (/ 16 /))
      call original_instratus_condensate(s1_i, s2_i, s3_i, p4_f1, p5_f1, p6_f1, p7_f1, p8_f1, p9_f1, p10_f1, p11_f1, p12_f1, p13_f1, p14_f1, p15_f1, p16_f1, p17_f1, p18_f1, p19_f1, p20_f1, p21_f1, p22_f1, p23_f1, p24_f1, p25_f1, p26_f1, p27_f1, p28_f1, p29_f1)
    end select
    status = 0_c_int
  end function pycam_hooks_original_v1

  subroutine pycam_hooks_reset_v1() bind(C, name='pycam_hooks_reset_v1')
    armed = .false.
    paused_hook = 0
  end subroutine pycam_hooks_reset_v1

end module pycam_hooks
