! The segment runner for cam_run1.deep_convection: the original Fortran, pausable at
! zm_convr, zm_conv_evap, momtran.
!
! GENERATED by tools/generate_pi_cam_pausable_runners.py from
! native/pi_cam/pausable/deep_convection.yaml.  Do not edit by hand; edit the spec.
!
! The runner is a state machine over the units' pieces: start() runs from the
! top of the action for every chunk of this rank and returns either DONE or,
! when a replaced kernel's call is reached, NEEDS_PYTHON_KERNEL with the
! program counter parked before the call; frame() describes the call's
! arguments where they live; resume() continues past the call; original()
! runs the very call on the paused frame.  Python makes every call; Fortran
! never calls Python.
module pycam_zmdeep_runner
  use, intrinsic :: iso_c_binding, only: c_int, c_int32_t, c_int64_t, c_double, c_ptr, c_char, c_null_ptr, c_loc
  use ppgrid, only: begchunk, endchunk
  use pycam_stage_hosts, only: stage_hosts_ok
  use pycam_zmdeep_glue, only: glue_piece_1, glue_piece_2, glue_piece_3, glue_bind_deep, glue_enter, glue_leave, &
       glue_resolve_indices, glue_configure, use_subcol_microp
  use pycam_zmdeep_deep, only: deep_piece_1, deep_piece_2, deep_piece_3, deep_bind_zm, deep_resolve_indices, deep_configure, &
       deep_scheme
  use pycam_zmdeep_zm, only: zm_piece_1, zm_piece_2, zm_piece_3, zm_piece_4, zm_piece_5, zm_piece_6, &
       zm_convr_frame, zm_conv_evap_frame, momtran_frame, zm_convr_original, zm_conv_evap_original, momtran_original, &
       zm_resolve_indices
  use phys_control, only: cam_physpkg_is
  implicit none
  private

  integer(c_int), parameter :: ev_done = 0_c_int, ev_needs_kernel = 1_c_int, ev_error = 2_c_int
  integer, parameter :: pc_idle = 0
  integer, parameter :: pc_chunk_begin = 1
  integer, parameter :: pc_chunk_end = 2
  integer, parameter :: pc_glue_piece_3_1 = 3
  integer, parameter :: pc_deep_piece_3_1 = 4
  integer, parameter :: pc_zm_piece_6_1 = 5
  integer, parameter :: pc_zm_piece_5_1 = 6
  integer, parameter :: pc_before_momtran_1 = 7
  integer, parameter :: pc_at_momtran = 8
  integer, parameter :: pc_after_momtran = 9
  integer, parameter :: pc_zm_piece_4_1 = 10
  integer, parameter :: pc_if_1 = 11
  integer, parameter :: pc_zm_piece_3_1 = 12
  integer, parameter :: pc_before_zm_conv_evap_1 = 13
  integer, parameter :: pc_at_zm_conv_evap = 14
  integer, parameter :: pc_after_zm_conv_evap = 15
  integer, parameter :: pc_zm_piece_2_1 = 16
  integer, parameter :: pc_before_zm_convr_1 = 17
  integer, parameter :: pc_at_zm_convr = 18
  integer, parameter :: pc_after_zm_convr = 19
  integer, parameter :: pc_zm_piece_1_1 = 20
  integer, parameter :: pc_leave_zm_1 = 21
  integer, parameter :: pc_enter_zm_1 = 22
  integer, parameter :: pc_deep_piece_2_1 = 23
  integer, parameter :: pc_select_1 = 24
  integer, parameter :: pc_deep_piece_1_1 = 25
  integer, parameter :: pc_leave_deep_1 = 26
  integer, parameter :: pc_enter_deep_1 = 27
  integer, parameter :: pc_glue_piece_2_1 = 28
  integer, parameter :: pc_glue_piece_1_1 = 29
  integer(c_int), parameter :: kernel_zm_convr = 1_c_int
  integer(c_int), parameter :: kernel_zm_conv_evap = 2_c_int
  integer(c_int), parameter :: kernel_momtran = 3_c_int
  integer, parameter :: nkernels = 3
  integer, parameter, public :: frame_slots = 70
  integer, parameter :: context_id = 1

  logical, save :: created = .false.
  integer, save :: pc = pc_idle
  integer, save :: lchnk = 0
  integer(c_int), save :: token = 0_c_int, call_index = 0_c_int
  logical, save :: replace(nkernels) = .false.
  character(len=256), save :: last_error = ' '

contains

  ! ------------------------------------------------------------------ !
  ! The ABI Python drives
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_zmdeep_create_v1(context) bind(C, name='pycam_zmdeep_create_v1') result(status)
    integer(c_int), intent(out) :: context
    context = 0_c_int
    status = 1_c_int
    if (created) then
      last_error = 'zmdeep context already exists'; return
    end if
    if (.not. stage_hosts_ok(int(begchunk, c_int))) then
      last_error = 'zmdeep: the stage hosts are not bound (pycam_stagehost_bind_v1 first)'; return
    end if
    call glue_configure()
    call deep_configure()
    call glue_resolve_indices()
    call deep_resolve_indices()
    call zm_resolve_indices()
    status = 2_c_int
    created = .true.
    pc = pc_idle
    context = int(context_id, c_int)
    status = 0_c_int
  end function pycam_zmdeep_create_v1

  integer(c_int) function pycam_zmdeep_start_v1(context, count, mask, event) bind(C, name='pycam_zmdeep_start_v1') result(status)
    integer(c_int), value, intent(in) :: context, count
    integer(c_int), intent(in) :: mask(count)
    integer(c_int), intent(out) :: event
    integer :: k
    event = ev_error
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no zmdeep context'; return
    end if
    if (pc /= pc_idle) then
      last_error = 'zmdeep is not idle; resume or reset it first'; status = 2_c_int; return
    end if
    if (count < nkernels) then
      last_error = 'replacement mask is too short'; status = 3_c_int; return
    end if
    do k = 1, nkernels
      replace(k) = mask(k) /= 0_c_int
    end do
    call_index = 0_c_int
    lchnk = begchunk
    pc = pc_chunk_begin
    call advance(event)
    status = 0_c_int
  end function pycam_zmdeep_start_v1

  integer(c_int) function pycam_zmdeep_resume_v1(context, kernel, token_in, event) bind(C, name='pycam_zmdeep_resume_v1') result(status)
    integer(c_int), value, intent(in) :: context, kernel, token_in
    integer(c_int), intent(out) :: event
    event = ev_error
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no zmdeep context'; return
    end if
    if (token_in /= token) then
      last_error = 'stale resume: the frame token does not match the pause'; status = 4_c_int; return
    end if
    select case (pc)
    case (pc_at_zm_convr)
      if (kernel /= kernel_zm_convr) then
        last_error = 'zmdeep is paused on zm_convr, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_zm_convr
    case (pc_at_zm_conv_evap)
      if (kernel /= kernel_zm_conv_evap) then
        last_error = 'zmdeep is paused on zm_conv_evap, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_zm_conv_evap
    case (pc_at_momtran)
      if (kernel /= kernel_momtran) then
        last_error = 'zmdeep is paused on momtran, not on the kernel resumed'; status = 3_c_int; return
      end if
      pc = pc_after_momtran
    case default
      last_error = 'zmdeep is not paused'; status = 2_c_int; return
    end select
    token = token + 1_c_int
    call advance(event)
    status = 0_c_int
  end function pycam_zmdeep_resume_v1

  integer(c_int) function pycam_zmdeep_frame_v1(context, kernel, index_out, lchnk_out, ncol_out, &
       substep_out, token_out, count, ptrs, ndims, shapes, dtypes, intents) bind(C, name='pycam_zmdeep_frame_v1') result(status)
    integer(c_int), value, intent(in) :: context, count
    integer(c_int), intent(out) :: kernel, index_out, lchnk_out, ncol_out, substep_out, token_out
    type(c_ptr), intent(out) :: ptrs(count)
    integer(c_int), intent(out) :: ndims(count), dtypes(count), intents(count)
    integer(c_int64_t), intent(out) :: shapes(3, count)
    kernel = 0_c_int; index_out = 0_c_int; lchnk_out = 0_c_int; ncol_out = 0_c_int
    substep_out = 0_c_int; token_out = 0_c_int
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no zmdeep context'; return
    end if
    if (count < frame_slots) then
      last_error = 'frame table is too short'; status = 3_c_int; return
    end if
    select case (pc)
    case (pc_at_zm_convr)
      call zm_convr_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_zm_convr
    case (pc_at_zm_conv_evap)
      call zm_conv_evap_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_zm_conv_evap
    case (pc_at_momtran)
      call momtran_frame(ptrs, ndims, shapes, dtypes, intents, ncol_out)
      kernel = kernel_momtran
    case default
      last_error = 'zmdeep is not paused; there is no frame'; status = 2_c_int; return
    end select
    index_out = call_index
    lchnk_out = int(lchnk, c_int)
    substep_out = 1_c_int
    token_out = token
    status = 0_c_int
  end function pycam_zmdeep_frame_v1

  integer(c_int) function pycam_zmdeep_original_v1(context, kernel) bind(C, name='pycam_zmdeep_original_v1') result(status)
    ! Run the original call on the paused frame: the validation gate's
    ! replacement, exercising the pause, the frame and the resume.
    integer(c_int), value, intent(in) :: context, kernel
    status = 1_c_int
    if (.not. created .or. context /= context_id) then
      last_error = 'no zmdeep context'; return
    end if
    select case (pc)
    case (pc_at_zm_convr)
      if (kernel /= kernel_zm_convr) then
        last_error = 'zmdeep is paused on zm_convr, not on the kernel asked for'; status = 3_c_int; return
      end if
      call zm_convr_original()
    case (pc_at_zm_conv_evap)
      if (kernel /= kernel_zm_conv_evap) then
        last_error = 'zmdeep is paused on zm_conv_evap, not on the kernel asked for'; status = 3_c_int; return
      end if
      call zm_conv_evap_original()
    case (pc_at_momtran)
      if (kernel /= kernel_momtran) then
        last_error = 'zmdeep is paused on momtran, not on the kernel asked for'; status = 3_c_int; return
      end if
      call momtran_original()
    case default
      last_error = 'zmdeep is not paused; there is nothing to run'; status = 2_c_int; return
    end select
    status = 0_c_int
  end function pycam_zmdeep_original_v1

  integer(c_int) function pycam_zmdeep_error_v1(context, buffer, length) bind(C, name='pycam_zmdeep_error_v1') result(status)
    integer(c_int), value, intent(in) :: context, length
    character(kind=c_char), intent(out) :: buffer(length)
    integer :: n, i
    n = min(length - 1, len_trim(last_error))
    do i = 1, n
      buffer(i) = last_error(i:i)
    end do
    buffer(n + 1) = c_char_'\0'
    status = 0_c_int
    if (context /= context_id) status = 1_c_int
  end function pycam_zmdeep_error_v1

  integer(c_int) function pycam_zmdeep_reset_v1(context) bind(C, name='pycam_zmdeep_reset_v1') result(status)
    integer(c_int), value, intent(in) :: context
    status = 1_c_int
    if (.not. created .or. context /= context_id) return
    pc = pc_idle
    status = 0_c_int
  end function pycam_zmdeep_reset_v1

  integer(c_int) function pycam_zmdeep_destroy_v1(context) bind(C, name='pycam_zmdeep_destroy_v1') result(status)
    integer(c_int), value, intent(in) :: context
    status = 1_c_int
    if (.not. created .or. context /= context_id) return
    created = .false.
    pc = pc_idle
    status = 0_c_int
  end function pycam_zmdeep_destroy_v1

  ! ------------------------------------------------------------------ !
  ! The state machine
  ! ------------------------------------------------------------------ !

  subroutine advance(event)
    integer(c_int), intent(out) :: event
    do
      select case (pc)
      case (pc_chunk_begin)
        if (lchnk > endchunk) then
          pc = pc_idle
          event = ev_done
          return
        end if
        call glue_enter(lchnk)
        pc = pc_glue_piece_1_1
      case (pc_chunk_end)
        call glue_leave()
        lchnk = lchnk + 1
        pc = pc_chunk_begin
      case (pc_glue_piece_3_1)
        call glue_piece_3()
        pc = pc_chunk_end
      case (pc_deep_piece_3_1)
        call deep_piece_3()
        pc = pc_leave_deep_1
      case (pc_zm_piece_6_1)
        call zm_piece_6()
        pc = pc_leave_zm_1
      case (pc_zm_piece_5_1)
        call zm_piece_5()
        pc = pc_zm_piece_6_1
      case (pc_before_momtran_1)
        if (replace(3)) then
          token = token + 1_c_int
          pc = pc_at_momtran
          event = ev_needs_kernel
          return
        end if
        call momtran_original()
        pc = pc_after_momtran
      case (pc_at_momtran)
        last_error = 'zmdeep is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_momtran)
        call_index = call_index + 1_c_int
        pc = pc_zm_piece_5_1
      case (pc_zm_piece_4_1)
        call zm_piece_4()
        pc = pc_before_momtran_1
      case (pc_if_1)
        if ( .not. cam_physpkg_is('cam3')) then
          pc = pc_zm_piece_4_1
        else
          pc = pc_zm_piece_6_1
        end if
      case (pc_zm_piece_3_1)
        call zm_piece_3()
        pc = pc_if_1
      case (pc_before_zm_conv_evap_1)
        if (replace(2)) then
          token = token + 1_c_int
          pc = pc_at_zm_conv_evap
          event = ev_needs_kernel
          return
        end if
        call zm_conv_evap_original()
        pc = pc_after_zm_conv_evap
      case (pc_at_zm_conv_evap)
        last_error = 'zmdeep is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_zm_conv_evap)
        call_index = call_index + 1_c_int
        pc = pc_zm_piece_3_1
      case (pc_zm_piece_2_1)
        call zm_piece_2()
        pc = pc_before_zm_conv_evap_1
      case (pc_before_zm_convr_1)
        if (replace(1)) then
          token = token + 1_c_int
          pc = pc_at_zm_convr
          event = ev_needs_kernel
          return
        end if
        call zm_convr_original()
        pc = pc_after_zm_convr
      case (pc_at_zm_convr)
        last_error = 'zmdeep is paused; only resume continues it'
        event = ev_error
        return
      case (pc_after_zm_convr)
        call_index = call_index + 1_c_int
        pc = pc_zm_piece_2_1
      case (pc_zm_piece_1_1)
        call zm_piece_1()
        pc = pc_before_zm_convr_1
      case (pc_leave_zm_1)
        pc = pc_deep_piece_3_1
      case (pc_enter_zm_1)
        call deep_bind_zm()
        pc = pc_zm_piece_1_1
      case (pc_deep_piece_2_1)
        call deep_piece_2()
        pc = pc_enter_zm_1
      case (pc_select_1)
        select case ( deep_scheme )
        case ('ZM')
          pc = pc_deep_piece_2_1
        case default
          last_error = 'zmdeep:  deep_scheme  takes a case this runner was not written for'
          event = ev_error
          return
        end select
      case (pc_deep_piece_1_1)
        call deep_piece_1()
        pc = pc_select_1
      case (pc_leave_deep_1)
        pc = pc_glue_piece_3_1
      case (pc_enter_deep_1)
        call glue_bind_deep()
        pc = pc_deep_piece_1_1
      case (pc_glue_piece_2_1)
        call glue_piece_2()
        pc = pc_enter_deep_1
      case (pc_glue_piece_1_1)
        call glue_piece_1()
        pc = pc_glue_piece_2_1
      case default
        last_error = 'zmdeep program counter is corrupt'
        event = ev_error
        return
      end select
    end do
  end subroutine advance

end module pycam_zmdeep_runner
