! radiation_tend's inline arithmetic, as routines the image can be asked
! to run.
!
! GENERATED by tools/generate_pi_cam_rad_kernels.py from the pinned source
! physics/rrtmg/radiation.F90.  Do not edit by hand; edit the generator.
!
! Each body below is the original text with names substituted, never
! rewritten: `state%t` becomes `t`, `cam_in%lwup` becomes `lwup`, a module
! flag becomes an argument.  Every expression, every loop nest and every
! bound is character for character what the pinned source computes, which is
! what lets the bit-for-bit gate mean something.
!
! This module is an addition to the source tree.  radiation_tend is not
! changed to call it, so the oracle's own radiation.o -- the machine code the
! gate validated -- stays untouched; only a Python-driven timestep runs
! these.  The Python-driven run is gated bit-for-bit against the oracle, and
! that gate is what proves the two copies of the arithmetic agree.
!
! Nothing here touches a derived type, the physics buffer, the clock or the
! history file, with one exception noted in the generator: radinp is private
! to radiation.F90 and reads the orbital elements, so its body is lifted
! whole together with the two module uses it needs.

module pycam_rad_kernels

  use shr_kind_mod,    only: r8 => shr_kind_r8
  use ppgrid,          only: pcols, pver, pverp
  use parrrsw,         only: nbndsw
  use parrrtm,         only: nbndlw
  use shr_orb_mod,     only: shr_orb_decl
  use cam_control_mod, only: lambm0, obliqr, mvelpp, eccen
  use time_manager,    only: get_curr_calday

  implicit none
  private

  public :: rad_gather_day_night
  public :: rad_combine_cld_optics_sw
  public :: rad_snow_blend_sw
  public :: rad_combine_cld_optics_lw
  public :: rad_snow_blend_lw
  public :: rad_interface_temperature
  public :: rad_sw_cloud_forcing
  public :: rad_scale_by_cpair
  public :: rad_visible_tau
  public :: rad_lwup_cgs
  public :: rad_lw_cloud_forcing
  public :: rad_emissivity
  public :: rad_snow_gridbox
  public :: rad_heating_unscale
  public :: rad_theta_heating
  public :: rad_heating_scale
  public :: rad_inp

contains

  subroutine rad_gather_day_night( &
         ncol, coszrs, Nday, Nnite, IdxDay, IdxNite)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: coszrs(pcols)
   integer,  intent(out) :: Nday, Nnite
   integer,  intent(out) :: IdxDay(pcols), IdxNite(pcols)

   integer :: i

       Nday = 0
       Nnite = 0
       do i = 1, ncol
          if ( coszrs(i) > 0.0_r8 ) then
             Nday = Nday + 1
             IdxDay(Nday) = i
          else
             Nnite = Nnite + 1
             IdxNite(Nnite) = i
          end if
       end do

  end subroutine rad_gather_day_night

  subroutine rad_combine_cld_optics_sw( &
         ncol, liq_tau, liq_tau_w, liq_tau_w_g, liq_tau_w_f, ice_tau, &
         ice_tau_w, ice_tau_w_g, ice_tau_w_f, cld_tau, cld_tau_w, &
         cld_tau_w_g, cld_tau_w_f)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: liq_tau(nbndsw,pcols,pver), liq_tau_w(nbndsw,pcols,pver)
   real(r8), intent(in)  :: liq_tau_w_g(nbndsw,pcols,pver), liq_tau_w_f(nbndsw,pcols,pver)
   real(r8), intent(in)  :: ice_tau(nbndsw,pcols,pver), ice_tau_w(nbndsw,pcols,pver)
   real(r8), intent(in)  :: ice_tau_w_g(nbndsw,pcols,pver), ice_tau_w_f(nbndsw,pcols,pver)
   real(r8), intent(out) :: cld_tau(nbndsw,pcols,pver), cld_tau_w(nbndsw,pcols,pver)
   real(r8), intent(out) :: cld_tau_w_g(nbndsw,pcols,pver), cld_tau_w_f(nbndsw,pcols,pver)

             cld_tau    (:,1:ncol,:) =  liq_tau    (:,1:ncol,:) + ice_tau    (:,1:ncol,:)
             cld_tau_w  (:,1:ncol,:) =  liq_tau_w  (:,1:ncol,:) + ice_tau_w  (:,1:ncol,:)
             cld_tau_w_g(:,1:ncol,:) =  liq_tau_w_g(:,1:ncol,:) + ice_tau_w_g(:,1:ncol,:)
             cld_tau_w_f(:,1:ncol,:) =  liq_tau_w_f(:,1:ncol,:) + ice_tau_w_f(:,1:ncol,:)

  end subroutine rad_combine_cld_optics_sw

  subroutine rad_snow_blend_sw( &
         ncol, has_snow, cld, cldfsnow, snow_tau, snow_tau_w, snow_tau_w_g, &
         snow_tau_w_f, cld_tau, cld_tau_w, cld_tau_w_g, cld_tau_w_f, &
         cldfprime, c_cld_tau, c_cld_tau_w, c_cld_tau_w_g, c_cld_tau_w_f)

   integer,  intent(in)    :: ncol
   logical,  intent(in)    :: has_snow
   real(r8), intent(in)    :: cld(pcols,pver), cldfsnow(pcols,pver)
   real(r8), intent(in)    :: snow_tau(nbndsw,pcols,pver), snow_tau_w(nbndsw,pcols,pver)
   real(r8), intent(in)    :: snow_tau_w_g(nbndsw,pcols,pver), snow_tau_w_f(nbndsw,pcols,pver)
   real(r8), intent(in)    :: cld_tau(nbndsw,pcols,pver), cld_tau_w(nbndsw,pcols,pver)
   real(r8), intent(in)    :: cld_tau_w_g(nbndsw,pcols,pver), cld_tau_w_f(nbndsw,pcols,pver)
   ! Written only where has_snow; the driver sets it at 993-995 otherwise,
   ! which rad_snow_blend_lw reproduces, so this carries its value out.
   real(r8), intent(inout) :: cldfprime(pcols,pver)
   real(r8), intent(out)   :: c_cld_tau(nbndsw,pcols,pver), c_cld_tau_w(nbndsw,pcols,pver)
   real(r8), intent(out)   :: c_cld_tau_w_g(nbndsw,pcols,pver), c_cld_tau_w_f(nbndsw,pcols,pver)

   integer :: i, k

             if (has_snow) then
               ! add in snow
                do i=1,ncol
                   do k=1,pver
                      cldfprime(i,k)=max(cld(i,k),cldfsnow(i,k))
                      if(cldfprime(i,k) > 0.)then
                         c_cld_tau    (1:nbndsw,i,k)= &
                              (cldfsnow(i,k)*snow_tau    (1:nbndsw,i,k) + cld(i,k)*cld_tau    (1:nbndsw,i,k))/cldfprime(i,k)
                         c_cld_tau_w  (1:nbndsw,i,k)= &
                              (cldfsnow(i,k)*snow_tau_w  (1:nbndsw,i,k) + cld(i,k)*cld_tau_w  (1:nbndsw,i,k))/cldfprime(i,k)
                         c_cld_tau_w_g(1:nbndsw,i,k)= &
                              (cldfsnow(i,k)*snow_tau_w_g(1:nbndsw,i,k) + cld(i,k)*cld_tau_w_g(1:nbndsw,i,k))/cldfprime(i,k)
                         c_cld_tau_w_f(1:nbndsw,i,k)= &
                              (cldfsnow(i,k)*snow_tau_w_f(1:nbndsw,i,k) + cld(i,k)*cld_tau_w_f(1:nbndsw,i,k))/cldfprime(i,k)
                      else
                         c_cld_tau    (1:nbndsw,i,k)= 0._r8
                         c_cld_tau_w  (1:nbndsw,i,k)= 0._r8
                         c_cld_tau_w_g(1:nbndsw,i,k)= 0._r8
                         c_cld_tau_w_f(1:nbndsw,i,k)= 0._r8
                      endif
                   enddo
                enddo
             else
                c_cld_tau    (1:nbndsw,1:ncol,:)= cld_tau    (:,1:ncol,:)
                c_cld_tau_w  (1:nbndsw,1:ncol,:)= cld_tau_w  (:,1:ncol,:)
                c_cld_tau_w_g(1:nbndsw,1:ncol,:)= cld_tau_w_g(:,1:ncol,:)
                c_cld_tau_w_f(1:nbndsw,1:ncol,:)= cld_tau_w_f(:,1:ncol,:)
             endif

  end subroutine rad_snow_blend_sw

  subroutine rad_combine_cld_optics_lw( &
         ncol, liq_lw_abs, ice_lw_abs, cld_lw_abs)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: liq_lw_abs(nbndlw,pcols,pver), ice_lw_abs(nbndlw,pcols,pver)
   real(r8), intent(out) :: cld_lw_abs(nbndlw,pcols,pver)

                cld_lw_abs(:,1:ncol,:) = liq_lw_abs(:,1:ncol,:) + ice_lw_abs(:,1:ncol,:)

  end subroutine rad_combine_cld_optics_lw

  subroutine rad_snow_blend_lw( &
         ncol, has_snow, cld, cldfsnow, snow_lw_abs, cld_lw_abs, cldfprime, &
         c_cld_lw_abs)

   integer,  intent(in)  :: ncol
   logical,  intent(in)  :: has_snow
   real(r8), intent(in)  :: cld(pcols,pver), cldfsnow(pcols,pver)
   real(r8), intent(in)  :: snow_lw_abs(nbndlw,pcols,pver)
   real(r8), intent(in)  :: cld_lw_abs(nbndlw,pcols,pver)
   real(r8), intent(inout) :: cldfprime(pcols,pver)
   real(r8), intent(out) :: c_cld_lw_abs(nbndlw,pcols,pver)

   integer :: i, k

             if (has_snow) then
               ! add in snow
                do i=1,ncol
                   do k=1,pver
                      cldfprime(i,k)=max(cld(i,k),cldfsnow(i,k))
                      if(cldfprime(i,k) > 0.)then
                         c_cld_lw_abs(1:nbndlw,i,k)= &
                              (cldfsnow(i,k)*snow_lw_abs(1:nbndlw,i,k) + cld(i,k)*cld_lw_abs(1:nbndlw,i,k))/cldfprime(i,k)
                      else
                         c_cld_lw_abs(1:nbndlw,i,k)= 0._r8
                      endif
                   enddo
                enddo
             else
                c_cld_lw_abs(1:nbndlw,1:ncol,:)=cld_lw_abs(:,1:ncol,:)
             endif

          if (.not.(has_snow)) then
             cldfprime(1:ncol,:)=cld(1:ncol,:)
          endif

  end subroutine rad_snow_blend_lw

  subroutine rad_interface_temperature( &
         ncol, t, lnpint, lnpmid, lwup, stebol, tint)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: t(pcols,pver), lnpint(pcols,pverp), lnpmid(pcols,pver)
   real(r8), intent(in)  :: lwup(pcols), stebol
   real(r8), intent(out) :: tint(pcols,pverp)

   integer  :: i, k
   real(r8) :: dy

          do i = 1,ncol
             tint(i,1) = t(i,1)
             tint(i,pverp) = sqrt(sqrt(lwup(i)/stebol))
             do k = 2,pver
                dy = (lnpint(i,k) - lnpmid(i,k)) / (lnpmid(i,k-1) - lnpmid(i,k))
                tint(i,k) = t(i,k) - dy * (t(i,k) - t(i,k-1))
             end do
          end do

  end subroutine rad_interface_temperature

  subroutine rad_sw_cloud_forcing( &
         ncol, fsntoa, fsntoac, swcf)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: fsntoa(pcols), fsntoac(pcols)
   real(r8), intent(out) :: swcf(pcols)

   integer :: i

                     do i=1,ncol
                        swcf(i)=fsntoa(i) - fsntoac(i)
                     end do

  end subroutine rad_sw_cloud_forcing

  subroutine rad_scale_by_cpair( &
         ncol, field, cpair, ftem)

   integer,  intent(in)    :: ncol
   real(r8), intent(in)    :: field(pcols,pver), cpair
   real(r8), intent(inout) :: ftem(pcols,pver)

                     ftem(:ncol,:pver) = field(:ncol,:pver)/cpair

  end subroutine rad_scale_by_cpair

  subroutine rad_visible_tau( &
         ncol, Nnite, IdxNite, has_snow, idx_sw_diag, fillvalue, c_cld_tau, &
         liq_tau, ice_tau, snow_tau, cldfprime, tot_cld_vistau, &
         tot_icld_vistau, liq_icld_vistau, ice_icld_vistau, snow_icld_vistau)

   integer,  intent(in)  :: ncol, Nnite, idx_sw_diag
   integer,  intent(in)  :: IdxNite(pcols)
   logical,  intent(in)  :: has_snow
   real(r8), intent(in)  :: fillvalue
   real(r8), intent(in)  :: c_cld_tau(nbndsw,pcols,pver), liq_tau(nbndsw,pcols,pver)
   real(r8), intent(in)  :: ice_tau(nbndsw,pcols,pver), snow_tau(nbndsw,pcols,pver)
   real(r8), intent(in)  :: cldfprime(pcols,pver)
   real(r8), intent(out) :: tot_cld_vistau(pcols,pver), tot_icld_vistau(pcols,pver)
   real(r8), intent(out) :: liq_icld_vistau(pcols,pver), ice_icld_vistau(pcols,pver)
   real(r8), intent(out) :: snow_icld_vistau(pcols,pver)

   integer :: i

             tot_icld_vistau(:ncol,:)  = c_cld_tau(idx_sw_diag,:ncol,:)
             liq_icld_vistau(:ncol,:)  = liq_tau(idx_sw_diag,:ncol,:)
             ice_icld_vistau(:ncol,:)  = ice_tau(idx_sw_diag,:ncol,:)
             if (has_snow) then
                snow_icld_vistau(:ncol,:) = snow_tau(idx_sw_diag,:ncol,:)
             endif
   	  ! multiply by total cloud fraction to get gridbox value
   	  tot_cld_vistau(:ncol,:) = c_cld_tau(idx_sw_diag,:ncol,:)*cldfprime(:ncol,:)

   	  ! add fillvalue for night columns
             do i = 1, Nnite
                 tot_cld_vistau(IdxNite(i),:)   = fillvalue
                 tot_icld_vistau(IdxNite(i),:)  = fillvalue
                 liq_icld_vistau(IdxNite(i),:)  = fillvalue
                 ice_icld_vistau(IdxNite(i),:)  = fillvalue
                 if (has_snow) then
                    snow_icld_vistau(IdxNite(i),:) = fillvalue
                 endif
             end do

  end subroutine rad_visible_tau

  subroutine rad_lwup_cgs( &
         ncol, lwup, refused_scm, lwupcgs)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: lwup(pcols)
   ! The single-column CRM branch is refused at attach; the flag is
   ! passed so the body keeps the driver's text and stays .false.
   logical,  intent(in)  :: refused_scm
   real(r8), intent(out) :: lwupcgs(pcols)

   integer :: i

             do i=1,ncol
                lwupcgs(i) = lwup(i)*1000._r8
                if(refused_scm) &
                     continue
             end do

  end subroutine rad_lwup_cgs

  subroutine rad_lw_cloud_forcing( &
         ncol, flutc, flut, lwcf)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: flutc(pcols), flut(pcols)
   real(r8), intent(out) :: lwcf(pcols)

   integer :: i

                     do i=1,ncol
                        lwcf(i)=flutc(i) - flut(i)
                     end do

  end subroutine rad_lw_cloud_forcing

  subroutine rad_emissivity( &
         ncol, rrtmg_lw_cloudsim_band, cld_lw_abs, emis)

   integer,  intent(in)  :: ncol, rrtmg_lw_cloudsim_band
   real(r8), intent(in)  :: cld_lw_abs(nbndlw,pcols,pver)
   real(r8), intent(out) :: emis(pcols,pver)

          emis(:,:) = 0._r8
          emis(:ncol,:) = 1._r8 - exp(-cld_lw_abs(rrtmg_lw_cloudsim_band,:ncol,:))

  end subroutine rad_emissivity

  subroutine rad_snow_gridbox( &
         ncol, has_snow, rrtmg_sw_cloudsim_band, rrtmg_lw_cloudsim_band, &
         cldfsnow, snow_tau, snow_lw_abs, gb_snow_tau, gb_snow_lw)

   integer,  intent(in)  :: ncol
   logical,  intent(in)  :: has_snow
   integer,  intent(in)  :: rrtmg_sw_cloudsim_band, rrtmg_lw_cloudsim_band
   real(r8), intent(in)  :: cldfsnow(pcols,pver)
   real(r8), intent(in)  :: snow_tau(nbndsw,pcols,pver), snow_lw_abs(nbndlw,pcols,pver)
   real(r8), intent(out) :: gb_snow_tau(pcols,pver), gb_snow_lw(pcols,pver)

   integer :: i, k

          gb_snow_tau(:,:) = 0._r8
          gb_snow_lw(:,:) = 0._r8
          if (has_snow) then
             do i=1,ncol
                do k=1,pver
                   if(cldfsnow(i,k) > 0.)then
                      gb_snow_tau(i,k) = snow_tau(rrtmg_sw_cloudsim_band,i,k)*cldfsnow(i,k)
                      gb_snow_lw(i,k) = snow_lw_abs(rrtmg_lw_cloudsim_band,i,k)*cldfsnow(i,k)
                   end if
                enddo
             enddo
          end if

  end subroutine rad_snow_gridbox

  subroutine rad_heating_unscale( &
         ncol, conserve_energy, pdel, qrs, qrl)

   integer,  intent(in)    :: ncol
   logical,  intent(in)    :: conserve_energy
   real(r8), intent(in)    :: pdel(pcols,pver)
   real(r8), intent(inout) :: qrs(pcols,pver), qrl(pcols,pver)

   integer :: i, k

          ! convert radiative heating rates from Q*dp to Q for energy conservation
          if (conserve_energy) then
   !DIR$ CONCURRENT
             do k =1 , pver
   !DIR$ CONCURRENT
                do i = 1, ncol
                   qrs(i,k) = qrs(i,k)/pdel(i,k)
                   qrl(i,k) = qrl(i,k)/pdel(i,k)
                end do
             end do
          end if

  end subroutine rad_heating_unscale

  subroutine rad_theta_heating( &
         ncol, qrs, qrl, cpair, pmid, cappa, ftem)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: qrs(pcols,pver), qrl(pcols,pver)
   real(r8), intent(in)  :: cpair, pmid(pcols,pver), cappa
   real(r8), intent(out) :: ftem(pcols,pver)

   integer :: i, k

       ! Compute heating rate for dtheta/dt 
       do k=1,pver
          do i=1,ncol
             ftem(i,k) = (qrs(i,k) + qrl(i,k))/cpair * (1.e5_r8/pmid(i,k))**cappa
          end do
       end do

  end subroutine rad_theta_heating

  subroutine rad_heating_scale( &
         ncol, conserve_energy, pdel, qrs, qrl)

   integer,  intent(in)    :: ncol
   logical,  intent(in)    :: conserve_energy
   real(r8), intent(in)    :: pdel(pcols,pver)
   real(r8), intent(inout) :: qrs(pcols,pver), qrl(pcols,pver)

   integer :: i, k

       ! convert radiative heating rates to Q*dp for energy conservation
       if (conserve_energy) then
   !DIR$ CONCURRENT
          do k =1 , pver
   !DIR$ CONCURRENT
             do i = 1, ncol
                qrs(i,k) = qrs(i,k)*pdel(i,k)
                qrl(i,k) = qrl(i,k)*pdel(i,k)
             end do
          end do
       end if

  end subroutine rad_heating_scale

  subroutine rad_inp( &
         ncol, pmid, pint, pmidrd, pintrd, eccf)

   integer,  intent(in)  :: ncol
   real(r8), intent(in)  :: pmid(pcols,pver), pint(pcols,pverp)
   real(r8), intent(out) :: pmidrd(pcols,pver), pintrd(pcols,pverp)
   real(r8), intent(out) :: eccf

   integer  :: i, k
   real(r8) :: calday
   real(r8) :: delta

      calday = get_curr_calday()
      call shr_orb_decl (calday  ,eccen     ,mvelpp  ,lambm0  ,obliqr  , &
                         delta   ,eccf)

   !
   ! Convert pressure from pascals to dynes/cm2
   !
      do k=1,pver
         do i=1,ncol
            pmidrd(i,k) = pmid(i,k)*10.0_r8
            pintrd(i,k) = pint(i,k)*10.0_r8
         end do
      end do
      do i=1,ncol
         pintrd(i,pverp) = pint(i,pverp)*10.0_r8
      end do


  end subroutine rad_inp

end module pycam_rad_kernels
