#!/bin/bash
#PBS -N pycesm-pi-atm-oracle-50
#PBS -A UCUB0188
#PBS -q develop
#PBS -l select=4:ncpus=64:mpiprocs=128:ompthreads=1:mem=64GB
#PBS -l walltime=02:00:00
#PBS -j oe
#PBS -V

set -euo pipefail

case_root=/glade/work/ruitong/CESM_cases/f.e13.F1850C5.ne16_g16.icesm131_ihesp.PI-atm.pycesm-ref.50step
run_dir=/glade/derecho/scratch/ruitong/pyCESM/PI-atm/f.e13.F1850C5.ne16_g16.icesm131_ihesp.PI-atm.pycesm-ref.50step/run
executable=/glade/derecho/scratch/ruitong/pyCESM/PI-atm/f.e13.F1850C5.ne16_g16.icesm131_ihesp.PI-atm.pycesm-ref.50step/bld/cesm.exe

source "${case_root}/.env_mach_specific.sh" >/dev/null 2>&1
export OMP_NUM_THREADS=1
export OMP_STACKSIZE=64M
export FI_CXI_RX_MATCH_MODE=hybrid
export FI_MR_CACHE_MONITOR=memhooks
export MPICH_MPIIO_HINTS='*:romio_cb_read=enable:romio_cb_write=enable:striping_factor=24'

mkdir -p "${run_dir}/timing/checkpoints"
cd "${run_dir}"
mpiexec --label -n 512 "${executable}" > cesm.log.pycesm-oracle-50 2>&1
