"""Generate adapters inside legacy CAM modules.

An external ``use module, only: routine`` adapter cannot call a private module
procedure and cannot declare a private derived type.  This generator inserts a
small ``bind(C)`` pointer-table wrapper immediately before the module's
``end module`` statement.  The numerical procedure is not copied or rewritten;
the wrapper only reconstructs typed Fortran pointers and calls it.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import re
from pathlib import Path
import shutil
from typing import Iterable, Mapping

from .errors import PICAMConfigurationError
from .source_catalog import FortranArgument, FortranProcedure


@dataclass(frozen=True, slots=True)
class InModuleAdapter:
    procedure: FortranProcedure
    symbol: str
    source: str
    strategy: str = "in-module-pointer-table"

    def manifest(self) -> dict[str, object]:
        return {
            "schema_version": 1,
            "name": self.procedure.qualified_name,
            "original_source": self.procedure.source,
            "original_module": self.procedure.module,
            "original_routine": self.procedure.name,
            "symbol": self.symbol,
            "strategy": self.strategy,
            "arguments": [argument.as_dict() for argument in self.procedure.arguments],
            "result": (
                None
                if self.procedure.result is None
                else self.procedure.result.as_dict()
            ),
        }


def in_module_adapter_blockers(procedure: FortranProcedure) -> tuple[str, ...]:
    """Return only blockers that the in-module ABI cannot express."""

    blockers: list[str] = []
    if procedure.procedure_kind == "function" and procedure.result is None:
        blockers.append("unknown_function_result")
    fields = (
        *(argument for argument in procedure.arguments if not argument.procedure),
        *((procedure.result,) if procedure.result else ()),
    )
    if procedure.module is None and any(
        argument.procedure for argument in procedure.arguments
    ):
        blockers.append("external_procedure_dummy")
    for argument in fields:
        if argument.fortran_type == "unknown":
            blockers.append(f"unknown_argument:{argument.name}")
        if argument.allocatable:
            # A POINTER actual argument is not valid for an ALLOCATABLE dummy.
            blockers.append(f"allocatable_argument:{argument.name}")
    return tuple(dict.fromkeys(blockers))


def can_generate_in_module_adapter(procedure: FortranProcedure) -> bool:
    return not in_module_adapter_blockers(procedure)


def in_module_adapter_symbol(procedure: FortranProcedure) -> str:
    identity = sha256(
        (
            f"{procedure.source}\0{procedure.qualified_name}\0"
            f"{procedure.line_start}"
        ).encode("utf-8")
    ).hexdigest()[:16]
    return f"freecam_pi_cam_inline_{procedure.name[:20]}_{identity}_v1"


def generate_in_module_adapter(procedure: FortranProcedure) -> InModuleAdapter:
    blockers = in_module_adapter_blockers(procedure)
    if blockers:
        raise PICAMConfigurationError(
            f"cannot generate in-module adapter for {procedure.qualified_name}: "
            + ", ".join(blockers)
        )
    symbol = in_module_adapter_symbol(procedure)
    fields = (
        *(argument for argument in procedure.arguments if not argument.procedure),
        *((procedure.result,) if procedure.result else ()),
    )
    maximum_rank = max((_abi_rank(argument) for argument in fields), default=0)
    lines = [
        "",
        "! Generated by freecam.pi_cam.in_module_adapter; do not edit.",
        f"integer(c_int) function {symbol}(action_id, nargs, pointers, &",
        "     ndims, shapes, max_rank, fortran_comm, errmsg, errmsg_len) &",
        f"     bind(C, name='{symbol}') result(status)",
        "  use, intrinsic :: iso_c_binding, only: c_char, c_int, c_int32_t, &",
        "       c_int64_t, c_float, c_double, c_null_char, c_ptr, c_f_pointer",
    ]
    # Procedure-scoped USE association is not inherited by a sibling wrapper.
    # Reproduce the exact statements (including ONLY renames such as
    # ``r8 => shr_kind_r8``), otherwise private/local derived-type and kind
    # names are not visible in the generated adapter.
    lines.extend(
        f"  {statement}"
        for statement in procedure.use_statements
        if "iso_c_binding" not in statement.lower()
    )
    lines.extend(
        (
            "  integer(c_int), value, intent(in) :: action_id, nargs, max_rank",
            "  integer(c_int), value, intent(in) :: fortran_comm, errmsg_len",
            "  type(c_ptr), intent(in) :: pointers(*)",
            "  integer(c_int32_t), intent(in) :: ndims(*)",
            "  integer(c_int64_t), intent(in) :: shapes(*)",
            "  character(kind=c_char), intent(out) :: errmsg(*)",
            "  integer :: index",
        )
    )
    for argument in fields:
        lines.extend(f"  {line}" for line in _pointer_declarations(argument))
    lines.extend(
        (
            "",
            "  do index = 1, max(1, int(errmsg_len))",
            "    errmsg(index) = c_null_char",
            "  end do",
            "  status = 0_c_int",
            f"  if (action_id /= 0 .or. nargs /= {len(fields)}) then",
            "    status = 1_c_int",
            "    return",
            "  end if",
        )
    )
    if maximum_rank:
        lines.extend(
            (
                f"  if (max_rank < {maximum_rank}) then",
                "    status = 2_c_int",
                "    return",
                "  end if",
            )
        )
    for index, argument in enumerate(fields, start=1):
        lines.extend(
            (
                f"  if (ndims({index}) /= {argument.rank}) then",
                f"    status = {10 + index}_c_int",
                "    return",
                "  end if",
            )
        )
        if _assumed_character(argument):
            character_length = f"int(shapes({index - 1} * max_rank + {argument.rank + 1}))"
            extents = [
                f"int(shapes({index - 1} * max_rank + {axis}))"
                for axis in range(1, argument.rank + 1)
            ]
            element_count = " * ".join(extents) if extents else "1"
            lines.append(
                f"  call c_f_pointer(pointers({index}), raw_{argument.name}, "
                f"(/ ({element_count}) * {character_length} /))"
            )
            allocation_shape = "" if not extents else "(" + ", ".join(extents) + ")"
            lines.append(
                f"  allocate(character(len={character_length}) :: "
                f"arg_{argument.name}{allocation_shape})"
            )
            if argument.intent != "out":
                lines.append(
                    f"  arg_{argument.name} = transfer(raw_{argument.name}, "
                    f"arg_{argument.name})"
                )
        elif argument.rank:
            shape = ", ".join(
                f"int(shapes({index - 1} * max_rank + {axis}))"
                for axis in range(1, argument.rank + 1)
            )
            lines.append(
                f"  call c_f_pointer(pointers({index}), arg_{argument.name}, "
                f"(/ {shape} /))"
            )
        else:
            lines.append(
                f"  call c_f_pointer(pointers({index}), arg_{argument.name})"
            )
    actuals = ", ".join(
        f"{argument.name}=arg_{argument.name}"
        for argument in procedure.arguments
        if not argument.procedure
    )
    invocation = (
        f"  call {procedure.name}({actuals})"
        if procedure.procedure_kind == "subroutine"
        else f"  arg_{procedure.result.name} = {procedure.name}({actuals})"
    )
    lines.append(invocation)
    for argument in fields:
        if _assumed_character(argument) and argument.intent != "in":
            lines.append(
                f"  raw_{argument.name} = transfer(arg_{argument.name}, "
                f"raw_{argument.name})"
            )
    lines.extend((f"end function {symbol}", ""))
    source = "\n".join(lines)
    strategy = "in-module-pointer-table"
    if procedure.module is None:
        strategy = "external-source-pointer-table"
        source = _external_adapter_module(procedure, symbol, source)
    return InModuleAdapter(procedure, symbol, source, strategy)


def inject_in_module_adapters(
    source: str,
    *,
    module: str,
    procedures: Iterable[FortranProcedure],
) -> tuple[str, tuple[InModuleAdapter, ...]]:
    """Insert generated wrappers before exactly one matching END MODULE."""

    adapters = tuple(generate_in_module_adapter(item) for item in procedures)
    if not adapters:
        return source, ()
    pattern = re.compile(
        rf"(?im)^\s*end\s+module(?:\s+{re.escape(module)})?\s*$"
    )
    matches = tuple(pattern.finditer(source))
    if len(matches) != 1:
        raise PICAMConfigurationError(
            f"expected one END MODULE {module}, found {len(matches)}"
        )
    match = matches[0]
    block = "\n".join(adapter.source for adapter in adapters)
    return source[: match.start()] + block + source[match.start() :], adapters


def generate_in_module_source_tree(
    procedures: Iterable[FortranProcedure],
    *,
    source_root: str | Path,
    output_root: str | Path,
) -> tuple[InModuleAdapter, ...]:
    """Write patched copies grouped by original source and module."""

    source_base = Path(source_root).resolve()
    output_base = Path(output_root).resolve()
    grouped: dict[str, dict[str, list[FortranProcedure]]] = {}
    for procedure in procedures:
        if not can_generate_in_module_adapter(procedure):
            continue
        module = procedure.module or "__external__"
        grouped.setdefault(procedure.source, {}).setdefault(
            module, []
        ).append(procedure)
    generated: list[InModuleAdapter] = []
    for relative, modules in sorted(grouped.items()):
        original = source_base / relative
        if not original.is_file():
            raise PICAMConfigurationError(f"original source is absent: {original}")
        text = original.read_text()
        for module, selected in sorted(modules.items()):
            ordered = sorted(selected, key=lambda item: item.qualified_name)
            if module == "__external__":
                adapters = tuple(generate_in_module_adapter(item) for item in ordered)
                text = text.rstrip() + "\n\n" + "\n".join(
                    adapter.source for adapter in adapters
                )
            else:
                text, adapters = inject_in_module_adapters(
                    text,
                    module=module,
                    procedures=ordered,
                )
            generated.extend(adapters)
        output = output_base / relative
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(text)
        # Quoted preprocessor includes are resolved relative to the patched
        # source, not the original CAM directory.  Keep that source-local
        # context intact (COSP uses this for cosp_defs.h).
        for include in re.findall(
            r'(?im)^\s*#\s*include\s*["<]([^">]+)[">]', text
        ):
            dependency = original.parent / include
            if dependency.is_file():
                destination = output.parent / include
                destination.parent.mkdir(parents=True, exist_ok=True)
                if destination.resolve() != dependency.resolve():
                    shutil.copy2(dependency, destination)
    return tuple(generated)


def _pointer_declarations(argument: FortranArgument) -> tuple[str, ...]:
    if _assumed_character(argument):
        dimensions = (
            "" if argument.rank == 0 else "(" + ",".join(":" for _ in range(argument.rank)) + ")"
        )
        return (
            f"character(kind=c_char), pointer :: raw_{argument.name}(:)",
            f"character(len=:), allocatable :: arg_{argument.name}{dimensions}",
        )
    declaration = _fortran_type(argument)
    dimensions = (
        "" if argument.rank == 0 else "(" + ",".join(":" for _ in range(argument.rank)) + ")"
    )
    return (f"{declaration}, pointer :: arg_{argument.name}{dimensions}",)


def _fortran_type(argument: FortranArgument) -> str:
    base = argument.fortran_type
    if base.startswith("type:"):
        return f"type({base.split(':', 1)[1]})"
    if base.startswith("character"):
        assert argument.character_length is not None
        return f"character(len={argument.character_length})"
    if base not in {"real", "integer", "logical", "complex"}:
        raise PICAMConfigurationError(
            f"unsupported Fortran type {base!r} for {argument.name!r}"
        )
    # The original routine may declare a kind parameter locally (KR8 is a
    # common COSP example).  A sibling wrapper cannot see that local name.
    # Use the catalog's resolved interoperable kind instead; the generated
    # interface remains kind-identical without depending on local scope.
    interoperable = {
        "float32": "real(c_float)",
        "float64": "real(c_double)",
        "int32": "integer(c_int32_t)",
        "int64": "integer(c_int64_t)",
    }.get(str(argument.dtype))
    if argument.kind_local and interoperable is not None:
        return interoperable
    if argument.kind is None:
        return base
    if argument.kind.startswith("star"):
        return f"{base}*{argument.kind.removeprefix('star')}"
    return f"{base}(kind={argument.kind})"


def _assumed_character(argument: FortranArgument) -> bool:
    return argument.fortran_type.startswith("character") and not (
        argument.character_length and argument.character_length.isdigit()
    )


def _abi_rank(argument: FortranArgument) -> int:
    return argument.rank + (1 if _assumed_character(argument) else 0)


def _external_adapter_module(
    procedure: FortranProcedure,
    symbol: str,
    function_source: str,
) -> str:
    digest = symbol.rsplit("_", 2)[-2]
    module = f"freecam_external_adapter_{digest}"
    arguments = ", ".join(argument.name for argument in procedure.arguments)
    lines = [
        f"module {module}",
        "  use, intrinsic :: iso_c_binding",
    ]
    if procedure.use_statements:
        lines.extend(
            f"  {statement}"
            for statement in procedure.use_statements
            if "iso_c_binding" not in statement.lower()
        )
    else:
        for dependency in procedure.uses:
            if dependency != "iso_c_binding":
                lines.append(f"  use {dependency}")
    lines.extend(("  implicit none", "  private", f"  public :: {symbol}", "  interface"))
    if procedure.procedure_kind == "subroutine":
        lines.append(f"    subroutine {procedure.name}({arguments})")
    else:
        lines.append(
            f"    function {procedure.name}({arguments}) result(freecam_result)"
        )
    lines.append("      import")
    for argument in procedure.arguments:
        lines.append(f"      {_dummy_declaration(argument, external_interface=True)}")
    if procedure.procedure_kind == "function":
        assert procedure.result is not None
        lines.append(
            "      "
            + _dummy_declaration(procedure.result, external_interface=True).replace(
                f"::{procedure.result.name}", ":: freecam_result"
            ).replace(
                f":: {procedure.result.name}", ":: freecam_result"
            )
        )
    closing = "subroutine" if procedure.procedure_kind == "subroutine" else "function"
    lines.extend(
        (
            f"    end {closing} {procedure.name}",
            "  end interface",
            "contains",
            function_source,
            f"end module {module}",
            "",
        )
    )
    return "\n".join(lines)


def _dummy_declaration(
    argument: FortranArgument, *, external_interface: bool = False
) -> str:
    attributes: list[str] = []
    if argument.intent is not None:
        attributes.append(f"intent({argument.intent})")
    if argument.optional:
        attributes.append("optional")
    if argument.pointer:
        attributes.append("pointer")
    if argument.allocatable:
        attributes.append("allocatable")
    suffix = "" if not attributes else ", " + ", ".join(attributes)
    dimensions = ""
    if argument.rank:
        declared = argument.dimensions
        if external_interface:
            # External legacy routines receive ordinary base addresses.  The
            # exact bounds may depend on CPP aliases such as NGAS ->
            # carma%f_NGAS, whose spelling is not available to this generated
            # interface.  An assumed-size declaration preserves rank and the
            # address-passing ABI without re-evaluating those expressions.
            declared = ("1",) * (argument.rank - 1) + ("*",)
        dimensions = "(" + ", ".join(declared) + ")"
    return f"{_fortran_type(argument)}{suffix} :: {argument.name}{dimensions}"


def adapter_strategy_counts(
    procedures: Iterable[FortranProcedure],
) -> Mapping[str, int]:
    counts: dict[str, int] = {}
    for procedure in procedures:
        key = (
            "in_module_pointer_table"
            if can_generate_in_module_adapter(procedure)
            else "+".join(in_module_adapter_blockers(procedure))
        )
        counts[key] = counts.get(key, 0) + 1
    return dict(sorted(counts.items()))
