"""Draft a standalone function specification from the kernel inventory.

The reviewed YAML under native/pi_cam/functions is the runtime's only source
of truth, and a human decides the parts that carry judgement: which arguments
are structural, which forcing terms may default to zero, what range an input
may take, and which module state is numerically live.  Everything else -- the
Fortran argument order, dtype, rank, intent, native extents, and the unit in
each declaration comment -- is already recorded, so this tool writes that part
and marks the rest REVIEW for the reviewer to resolve.

    uv run python tools/draft_pi_cam_function_spec.py uwshcu::compute_uwshcu_inv \
        --dimensions mix=pcols mkx=pver ncnst=pcnst --out native/pi_cam/functions/uwshcu.yaml

The draft is never authoritative: tools/verify_pi_cam_function_spec.py still
checks the finished file against the inventory and the source.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
INVENTORY = REPO / "validation/pi_cam_kernel_inventory.json"

# `real(r8), intent(in) :: p0_inv(mix,mkx)   !  Environmental pressure ... [ Pa ]`
UNIT = re.compile(r"\[\s*([^\]]+?)\s*\]\s*\.?\s*$")
DECLARATION = re.compile(r"^\s*(?:integer|real|logical|character)\b.*::\s*(.+)$", re.I)

STRUCTURAL_HINTS = ("lchnk", "ncol", "iend", "pcols", "mix", "mkx", "pver", "pverp", "ncnst", "pcnst")


def declared_names(text: str) -> list[str]:
    """Names on the right of `::`, ignoring commas inside array dimensions."""

    names, current, depth = [], [], 0
    for character in text:
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
        elif depth == 0:
            if character == ",":
                names.append("".join(current)); current = []
            else:
                current.append(character)
    names.append("".join(current))
    return [name.strip() for name in names if name.strip()]


def declaration_comments(source: Path, first: int, last: int) -> dict[str, tuple[str, str]]:
    """name -> (unit, description) recovered from the declaration comments.

    A declaration's comment may run onto the following comment-only lines; any
    line carrying executable code ends the run.
    """

    found: dict[str, tuple[str, str]] = {}
    lines = source.read_text(errors="replace").splitlines()[first - 1 : last]
    pending: list[str] = []
    for line in lines:
        code, _, comment = line.partition("!")
        comment = comment.strip()
        match = DECLARATION.match(code)
        if match:
            pending = declared_names(match.group(1))
        elif code.strip():
            pending = []                       # executable code ends the run
        if not pending or not comment:
            continue
        unit = UNIT.search(comment)
        body = UNIT.sub("", comment).strip(" .")
        for name in pending:
            previous_unit, previous_text = found.get(name, ("", ""))
            found[name] = (unit.group(1) if unit else previous_unit,
                           (previous_text + " " + body).strip() if previous_text else body)
    return found


def public_shape(dimensions: list[str], canonical: dict[str, str]) -> list[str]:
    """Native extents minus the column axis.

    The spec keeps native dimension names here -- `public_axes` renames them
    for the user at the API layer -- so this must match what `spec.py` checks.
    An assumed-shape (`:`) or explicitly bounded (`0:pver`) dimension carries
    no extent the runtime can check, so it is handed to the reviewer.
    """

    public: list[str] = []
    for extent in dimensions:
        key = re.sub(r"\s+", "", extent)
        name = canonical.get(key)
        if name == "pcols":
            continue                           # the column axis never reaches the user
        public.append(name if name is not None else f"REVIEW extent {key}")
    return public


def role_of(argument: dict, canonical: dict[str, str]) -> str:
    name = argument["name"]
    if argument["rank"] == 0 and argument["dtype"] == "int32" and (
        name in STRUCTURAL_HINTS or name in canonical
    ):
        return "structural"
    return {"in": "input", "inout": "inout", "out": "output"}.get(argument["intent"], "REVIEW")


def sequence(items) -> str:
    """A YAML flow sequence whose members may contain `:` (`0:pver`, `:`)."""

    return ", ".join(json.dumps(str(item)) for item in items)


def quoted(text: str) -> str:
    """YAML scalar: a unit may contain `#`, a description a `:`."""

    return json.dumps(text) if text else "REVIEW"


def render(procedure: dict, canonical: dict[str, str], comments) -> str:
    out: list[str] = []
    add = out.append
    add(f"# DRAFT -- generated by tools/draft_pi_cam_function_spec.py; every REVIEW")
    add(f"# marker below needs a human decision before this file is authoritative.")
    add("")
    add("schema_version: 1")
    add(f"function: {procedure['name']}")
    add(f"qualified_name: {procedure['qualified_name']}")
    add(f"routine: {procedure['name']}")
    add(f"source: {procedure['source']}")
    add(f"module: {procedure['module']}")
    add("")
    add("dimensions:")
    add("  pcols: 16")
    add("  pver: 30")
    add("  pverp: 31")
    if "pcnst" in canonical.values():
        add("  pcnst: 57")
    add("public_axes:")
    add("  pver: lev")
    add("  pverp: ilev")
    add("")
    add("arguments:")
    for argument in procedure["arguments"]:
        name = argument["name"]
        role = role_of(argument, canonical)
        unit, description = comments.get(name, ("", ""))
        add(f"  - name: {name}")
        add(f"    role: {role}")
        add(f"    fortran_type: {argument['fortran_type']}")
        add(f"    dtype: {argument['dtype']}")
        add(f"    rank: {argument['rank']}")
        add(f"    intent: {argument['intent']}")
        native = [re.sub(r"\s+", "", d) for d in argument["dimensions"]]
        add(f"    native_shape: [{sequence(canonical.get(d, d) for d in native)}]")
        if role != "structural":
            add(f"    public_shape: [{sequence(public_shape(argument['dimensions'], canonical))}]")
            add(f"    units: {quoted(unit)}")
            add(f"    range: REVIEW")
            add(f"    constraints: REVIEW")
        else:
            add(f"    value: REVIEW")
        if argument.get("optional"):
            add(f"    optional: true   # REVIEW: pass or omit")
        if argument.get("pointer"):
            add(f"    pointer: true    # REVIEW: association required?")
        if argument["fortran_type"] == "logical":
            add(f"    # REVIEW: logical travels as int32; intent(out) needs codegen support")
        add(f"    description: {quoted(description)}")
    add("")
    add("# REVIEW: every namelist tunable this routine reads, with all storage copies.")
    add("parameters: REVIEW")
    add("")
    add("# REVIEW: every module-level value the routine reads that an initializer")
    add("# does not set; one write mode each (verify|declared|snapshot|initializer|parameter).")
    add("module_state: REVIEW")
    add("")
    add("initializers: REVIEW")
    add("image: REVIEW   # archive_members and stubs; see tools/build_pi_cam_standalone_function.py")
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("qualified_name")
    parser.add_argument("--dimensions", nargs="*", default=[], metavar="NATIVE=CANONICAL")
    parser.add_argument("--source-root", type=Path, default=REPO / "build/iCESM1.3.1_PI_cam_only")
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    inventory = json.loads(INVENTORY.read_text())
    matches = [p for p in inventory["procedures"] if p["qualified_name"] == args.qualified_name]
    if not matches:
        raise SystemExit(f"{args.qualified_name} is not in the kernel inventory")
    procedure = matches[0]
    if procedure.get("blockers"):
        print(f"note: inventory records blockers {procedure['blockers']}")

    canonical = dict(pair.split("=", 1) for pair in args.dimensions)
    canonical.setdefault("mkx+1", "pverp")
    for native, name in list(canonical.items()):
        if name == "pver":
            canonical.setdefault(f"{native}+1", "pverp")

    comments = declaration_comments(
        args.source_root / procedure["source"], procedure["line_start"], procedure["line_end"]
    )
    text = render(procedure, canonical, comments)
    if args.out:
        args.out.write_text(text)
        print(f"wrote {args.out} ({len(procedure['arguments'])} arguments, "
              f"{sum(1 for a in procedure['arguments'] if comments.get(a['name'], ('',''))[0])} units recovered, "
              f"{text.count('REVIEW')} REVIEW markers)")
    else:
        print(text)


if __name__ == "__main__":
    main()
