#!/usr/bin/env python
"""Generate the count-only trampolines a counting image links.

Each instrumented kernel gets three x86-64 instructions under its original
symbol; the definition in the oracle object is weakened and aliased at build
time (``build_pi_cam_devices.py``), so every call that goes through the symbol
passes here exactly once:

    <symbol>:
        movslq pycam_kcount_context(%rip), %r11
        incq   pycam_kcount_table + <index>*SLOTS*8(,%r11,8)
        jmp    pycam_orig_<symbol>

A tail jump preserves every argument register, the stack, and the return
address, so the original executes exactly as if called directly -- no calling
convention is guessed, no floating-point operation changes, nothing returns
to Python.  ``%r11`` and the flags are the only state touched; both are
volatile at a call boundary in the x86-64 SysV ABI, and no Fortran procedure
call passes meaning in them.  The table addressing is absolute, matching the
fixed-address non-PIC image.

Selection comes from the committed observability record
(``validation/pi_cam_kernel_observability.json``): kernels whose entry is
``trampoline``, filtered by scope -- ``all``, a comma-separated list of
process ids, or a comma-separated list of routine names.  Indices are the
record's global candidate indices, stable across scopes.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterable, Mapping

REPO = Path(__file__).resolve().parents[1]
OBSERVABILITY = REPO / "validation/pi_cam_kernel_observability.json"
SLOTS = 64
ALIAS_PREFIX = "pycam_orig_"

HEADER = """\
/* Generated by tools/generate_pi_cam_kcount_trampolines.py -- do not edit.
 * Count-only tail-jump trampolines: one increment, then the original kernel.
 * Scope: {scope}; {count} kernels; table indices from the observability record
 * (content {observability_hash}).
 */
\t.section .note.GNU-stack,"",@progbits
\t.data
\t.globl pycam_kcount_kernel_count
\t.align 4
pycam_kcount_kernel_count:
\t.long {kernel_count}
\t.text
"""

TRAMPOLINE = """\
\t.globl {symbol}
\t.type {symbol}, @function
{symbol}:
\tmovslq pycam_kcount_context(%rip), %r11
\tincq pycam_kcount_table+{offset}(,%r11,8)
\tjmp {alias}
\t.size {symbol}, .-{symbol}
"""


def select_kernels(record: Mapping[str, Any], scope: str) -> list[dict[str, Any]]:
    """The instrumentable kernels a scope names, sorted by index."""

    kernels = [k for k in record["kernels"] if k["entry"] == "trampoline"]
    if scope == "all":
        chosen = kernels
    else:
        wanted = {item.strip() for item in scope.split(",") if item.strip()}
        chosen = [k for k in kernels
                  if k["routine"] in wanted or set(k["processes"]) & wanted]
    return sorted(chosen, key=lambda k: k["index"])


def render(record: Mapping[str, Any], kernels: Iterable[Mapping[str, Any]], scope: str) -> str:
    kernels = list(kernels)
    parts = [HEADER.format(scope=scope, count=len(kernels),
                           observability_hash=record["content_hash"][:12],
                           kernel_count=max((k["index"] for k in kernels), default=-1) + 1)]
    for kernel in kernels:
        symbol = kernel["symbol"]
        parts.append(TRAMPOLINE.format(symbol=symbol, alias=ALIAS_PREFIX + symbol,
                                       offset=kernel["index"] * SLOTS * 8))
    return "\n".join(parts)


def trampoline_table(kernels: Iterable[Mapping[str, Any]]) -> list[dict[str, Any]]:
    """What the build applies and the manifest records, one row per kernel."""

    return [{
        "index": k["index"],
        "qualified": k["qualified"],
        "routine": k["routine"],
        "symbol": k["symbol"],
        "alias": ALIAS_PREFIX + k["symbol"],
        "object": k["defining_object"],
        "coverage": k["coverage"],
        "blind_spots": k["blind_spots"],
        "processes": k["processes"],
    } for k in kernels]


def load_observability(path: Path | None = None) -> dict[str, Any]:
    record = json.loads((path or OBSERVABILITY).read_text())
    if record.get("schema_version") != 1:
        raise SystemExit("unsupported observability schema")
    if record["table"]["slots"] != SLOTS:
        raise SystemExit("the observability record's slot count does not match this generator")
    return record


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scope", required=True,
                        help="'all', or comma-separated process ids and/or routine names")
    parser.add_argument("--output", type=Path, required=True, help="the .S file to write")
    parser.add_argument("--table", type=Path, help="also write the JSON table the build applies")
    args = parser.parse_args(argv)
    record = load_observability()
    kernels = select_kernels(record, args.scope)
    if not kernels:
        raise SystemExit(f"scope {args.scope!r} selects no instrumentable kernel")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(record, kernels, args.scope))
    if args.table:
        args.table.write_text(json.dumps(trampoline_table(kernels), indent=1, sort_keys=True) + "\n")
    print(f"wrote {args.output}: {len(kernels)} trampolines (scope {args.scope})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
