#!/usr/bin/env python3
"""Emit the host-pointer module every Tier-1 stage block shares.

The stage-block walkers replace whole tphysbc/tphysac actions, and every
wrapper they call needs the same five hosts: ``phys_state``, ``phys_tend``
and ``pbuf2d`` (cam_comp module pointers, handed over by a binder the state
codegen emits into cam_comp), and ``cam_in``/``cam_out`` (dummies of
cam_run1/cam_run2, so no module owns them -- but under zero-copy state the
records live in Python-owned memory the registry can address, and this
module derives its own pointers from ``pycam_owner_pointer`` exactly as the
generated camsrfexch rebinder does).

One module holds them once; ``pycam_bc_handles`` and ``pycam_ac_handles``
both use it, so a stage block costs one wrapper set, not one binder each.
The shared ``bind(C)`` entries every stage block's runtime asks for -- the
owner latch and the clock -- live here too.

    tools/generate_pi_cam_stage_hosts.py            # write the module
    tools/generate_pi_cam_stage_hosts.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MODULE = REPO / "native/pi_cam/support/pycam_stage_hosts.F90"


def render_module() -> str:
    return '''! The hosts every Tier-1 stage block reaches CAM through.
!
! GENERATED by tools/generate_pi_cam_stage_hosts.py.  Do not edit by hand;
! edit the generator.
!
! This module is an addition: it calls the oracle's routines and replaces
! none.  The host pointers are retained for the model's lifetime, matching
! the lifetime of the records they address -- the same contract the
! generated camsrfexch rebinder already relies on.

module pycam_stage_hosts

  use, intrinsic :: iso_c_binding, only: c_f_pointer, c_int
  use ppgrid,         only: begchunk, endchunk
  use physics_types,  only: physics_state, physics_tend
  use physics_buffer, only: physics_buffer_desc
  use camsrfexch,     only: cam_in_t, cam_out_t
  use time_manager,   only: get_nstep, get_step_size

  implicit none
  private

  public :: host_state, host_tend, host_pbuf2d, host_cam_in, host_cam_out
  public :: pycam_stagehost_bind, stage_hosts_ok

  ! the hosts, bound from the control layer after initialization
  type(physics_state), pointer, save :: host_state(:) => null()
  type(physics_tend),  pointer, save :: host_tend(:) => null()
  type(physics_buffer_desc), pointer, save :: host_pbuf2d(:,:) => null()
  type(cam_in_t),  pointer, save :: host_cam_in(:) => null()
  type(cam_out_t), pointer, save :: host_cam_out(:) => null()

  logical, save :: python_owns_stage = .false.

contains

  logical function stage_hosts_ok(lchnk)
    integer(c_int), intent(in) :: lchnk
    stage_hosts_ok = associated(host_state) .and. associated(host_tend) &
         .and. associated(host_pbuf2d) .and. associated(host_cam_in) &
         .and. lchnk >= begchunk .and. lchnk <= endchunk
  end function stage_hosts_ok

  integer function pycam_stagehost_bind(state, tend, pbuf2d) result(status)
    ! Called from the binder the state codegen emits into cam_comp, which
    ! owns the three arguments.  cam_in/cam_out are derived here from the
    ! zero-copy state registry: owner 1 and owner 2 of the state bridge are
    ! the cam_in_t/cam_out_t record arrays themselves, so a plain
    ! c_f_pointer over them is the same storage tphysac receives -- the
    ! idiom of the generated pycam_bind_cam_in.
    use pycam_python_state_registry, only: pycam_owner_pointer, pycam_state_is_ready
    type(physics_state), pointer, intent(in) :: state(:)
    type(physics_tend),  pointer, intent(in) :: tend(:)
    type(physics_buffer_desc), pointer, intent(in) :: pbuf2d(:,:)
    type(cam_in_t),  pointer :: cam_in_records(:)
    type(cam_out_t), pointer :: cam_out_records(:)
    integer :: nchunks
    host_state => state
    host_tend => tend
    host_pbuf2d => pbuf2d
    status = 1
    if (.not. pycam_state_is_ready()) return
    nchunks = endchunk - begchunk + 1
    if (nchunks < 1) then
      status = 2
      return
    endif
    call c_f_pointer(pycam_owner_pointer(1), cam_in_records, (/ nchunks /))
    host_cam_in(begchunk:endchunk) => cam_in_records
    call c_f_pointer(pycam_owner_pointer(2), cam_out_records, (/ nchunks /))
    host_cam_out(begchunk:endchunk) => cam_out_records
    status = 0
  end function pycam_stagehost_bind

  ! ------------------------------------------------------------------ !
  ! Ownership and the clock, shared by every stage block
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_stage_owner_v1(owns) &
       bind(C, name='pycam_stage_owner_v1') result(status)
    integer(c_int), value, intent(in) :: owns
    python_owns_stage = owns /= 0_c_int
    status = 0_c_int
  end function pycam_stage_owner_v1

  integer(c_int) function pycam_stage_nstep_v1() bind(C, name='pycam_stage_nstep_v1') result(status)
    status = int(get_nstep(), c_int)
  end function pycam_stage_nstep_v1

  integer(c_int) function pycam_stage_dt_v1() bind(C, name='pycam_stage_dt_v1') result(status)
    status = int(get_step_size(), c_int)
  end function pycam_stage_dt_v1

end module pycam_stage_hosts
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render_module()
    if arguments.check:
        current = MODULE.read_text() if MODULE.is_file() else ""
        if current != rendered:
            sys.stderr.write("".join(difflib.unified_diff(
                current.splitlines(keepends=True), rendered.splitlines(keepends=True),
                fromfile=f"{MODULE.name} (committed)", tofile=f"{MODULE.name} (generated)"))[:3000])
            sys.stderr.write(f"\nstale: {MODULE.relative_to(REPO)}\n")
            return 1
        return 0
    MODULE.write_text(rendered)
    print(f"wrote {MODULE.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
