#!/usr/bin/env python3
"""Emit the pausable runners: one module set per spec under native/pi_cam/pausable/.

    tools/generate_pi_cam_pausable_runners.py            # write every module and the frame table
    tools/generate_pi_cam_pausable_runners.py --check    # fail if any is stale or a range moved
    tools/generate_pi_cam_pausable_runners.py --only dry_adjustment

Each spec yields `pycam_<prefix>_glue.F90`, one `pycam_<prefix>_<unit>.F90`
per further unit, and `pycam_<prefix>_runner.F90` under native/pi_cam/support,
plus its kernels' frame descriptors in native/pi_cam/segment_frames.yaml.
The pinned ranges every module transcribes are hashed into the spec's
`anchors`; a source that moves fails --check before anything is rebuilt.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import pi_cam_pausable as pausable  # noqa: E402


def _stale(path: Path, text: str) -> bool:
    current = path.read_text() if path.is_file() else ""
    if current == text:
        return False
    sys.stderr.write("".join(difflib.unified_diff(
        current.splitlines(keepends=True), text.splitlines(keepends=True),
        fromfile=f"{path.name} (committed)", tofile=f"{path.name} (generated)"))[:4000])
    sys.stderr.write(f"\nstale: {path.relative_to(pausable.REPO)}\n")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--only", help="one spec's stem")
    arguments = parser.parse_args(argv)

    specs = sorted(pausable.SPECS.glob("*.yaml"))
    if arguments.only:
        specs = [p for p in specs if p.stem == arguments.only]
    if not specs:
        print("no specs", file=sys.stderr)
        return 1
    stale = False
    frames: dict = {}
    if pausable.FRAMES.is_file():
        frames = yaml.safe_load(pausable.FRAMES.read_text()).get("kernels", {}) or {}
    for path in specs:
        spec = pausable.load_spec(path)
        for unit in spec.units.values():
            gaps = pausable.coverage_gaps(unit)
            if gaps:
                print(f"{path.name}: unit {unit.key} leaves lines uncovered: {gaps[:12]}{' ...' if len(gaps) > 12 else ''}",
                      file=sys.stderr)
                return 1
        anchors = pausable.spec_digest(spec)
        recorded = (yaml.safe_load(path.read_text()) or {}).get("anchors") or {}
        if recorded and recorded != anchors:
            moved = [k for k in anchors if recorded.get(k) != anchors[k]]
            print(f"{path.name}: the pinned source moved under {moved}", file=sys.stderr)
            return 1
        if not recorded and not arguments.check:
            text = path.read_text().rstrip("\n") + "\nanchors:\n" + "".join(f"  {k!r}: {v}\n" for k, v in anchors.items())
            path.write_text(text)
        for target, text in pausable.render_all(spec).items():
            if arguments.check:
                stale |= _stale(target, text)
            else:
                target.write_text(text)
                print(f"wrote {target.relative_to(pausable.REPO)}")
        frames.update(pausable.frame_descriptors(spec))
    table = ("# GENERATED by tools/generate_pi_cam_pausable_runners.py -- do not edit.\n"
             "# The frame of every kernel a pausable runner stops at: the paused call's\n"
             "# arguments in the callee's order, as the runner serves them.\n"
             + yaml.safe_dump({"schema_version": 1, "kernels": frames}, sort_keys=False))
    if arguments.check:
        stale |= _stale(pausable.FRAMES, table)
        return 1 if stale else 0
    pausable.FRAMES.write_text(table)
    print(f"wrote {pausable.FRAMES.relative_to(pausable.REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
