#!/usr/bin/env python3
"""Emit the handles module a Python-driven microp_aero_run calls.

``microp_aero_run`` (``microp_aero.F90:345-713``) computes twenty numbers
of its own -- lifted into ``pycam_aero_kernels`` -- and otherwise calls
four routines that take derived types, reads the physics buffer, and hands
its tendency object to the stage.  None of those can be a direct kernel, so
each gets one ``bind(C)`` wrapper here, in the driver's exact form:

* ``nucleate_ice_cam_calc(state, wsubi, pbuf)`` -- ice nucleation,
* ``dropmixnuc(state, ptend, dtmicro, pbuf, wsub, cldn, cldo, tendnd,
  factnum)`` -- droplet activation, whose ``ptend`` is the stage's,
* ``hetfrz_classnuc_cam_save_cbaero(state, pbuf)`` and
  ``hetfrz_classnuc_cam_calc(state, deltatin, factnum, pbuf)`` -- classical
  heterogeneous freezing, both guarded by ``use_hetfrz_classnuc``,
* ``rad_cnst_get_info`` / ``_get_mode_num`` / ``_get_aer_mmr`` -- the modal
  aerosol fields, which are pointers into the constituent arrays.

The routine's own locals that outlive one call -- the tendency object, the
activation fraction and the droplet tendency -- live here per chunk, and
Python gets views of them.  This module is an addition: it calls the
oracle's routines and replaces none.

    tools/generate_pi_cam_aero_handles.py            # write the module
    tools/generate_pi_cam_aero_handles.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MODULE = REPO / "native/pi_cam/support/pycam_aero_handles.F90"

#: ``pycam_aero_view_v1`` codes: name -> (code, rank, expression, guard).
VIEWS = {
    "state_t": (1, 2, "state%t", "associated(state)"),
    "state_q": (2, 3, "state%q", "associated(state)"),
    "state_pmid": (3, 2, "state%pmid", "associated(state)"),
    "ptend_aero_s": (11, 2, "aero_ptend(lchnk)%s", "allocated(aero_ptend(lchnk)%s)"),
    "ptend_aero_q": (12, 3, "aero_ptend(lchnk)%q", "allocated(aero_ptend(lchnk)%q)"),
    "nctend_mixnuc": (21, 2, "nctend_mixnuc", None),
    "factnum": (22, 3, "factnum", "allocated(factnum)"),
    "num_coarse": (31, 2, "num_coarse", "associated(num_coarse)"),
    "coarse_dust": (32, 2, "coarse_dust", "associated(coarse_dust)"),
    "coarse_nacl": (33, 2, "coarse_nacl", "associated(coarse_nacl)"),
}


def render_module() -> str:
    nl = "\n"
    codes = nl.join(f"  integer(c_int), parameter, public :: view_{n} = {c}"
                    for n, (c, _, _, _) in sorted(VIEWS.items(), key=lambda kv: kv[1][0]))
    cases = []
    for name, (code, rank, expression, guard) in sorted(VIEWS.items(), key=lambda kv: kv[1][0]):
        cases.append(f"    case (view_{name})")
        if guard:
            cases.append(f"      if (.not. {guard}) return")
        cases.append(f"      call view{rank}({expression}, ptr, ndims, extents)")
    return f'''! The calls a Python-driven microp_aero_run makes into CAM.
!
! GENERATED by tools/generate_pi_cam_aero_handles.py.  Do not edit by hand;
! edit the generator.
!
! Everything microp_aero_run does that takes a derived type is here, in the
! driver's own form: the two activation cores, the two freezing calls, the
! modal-aerosol getters, and the tendency object the stage takes afterwards.
! This module is an addition: microp_aero.F90 is not patched, so the
! oracle's own microp_aero.o stays untouched.

module pycam_aero_handles

  use, intrinsic :: iso_c_binding, only: c_double, c_int, c_int64_t, c_loc, &
       c_null_ptr, c_ptr
  use shr_kind_mod,   only: r8 => shr_kind_r8
  use ppgrid,         only: pcols, pver, pverp, begchunk, endchunk
  use constituents,   only: pcnst
  use physics_types,  only: physics_state, physics_ptend, physics_ptend_init
  use physics_buffer, only: physics_buffer_desc, pbuf_get_chunk
  use rad_constituents, only: rad_cnst_get_info, rad_cnst_get_mode_num, rad_cnst_get_aer_mmr
  use ndrop,          only: dropmixnuc
  use nucleate_ice_cam, only: nucleate_ice_cam_calc
  use hetfrz_classnuc_cam, only: hetfrz_classnuc_cam_calc, hetfrz_classnuc_cam_save_cbaero
  use time_manager,   only: get_nstep, get_step_size

  implicit none
  private

  public :: pycam_aero_bind_hosts, python_owns_aero, aero_ptend

  logical, save :: python_owns_aero = .false.

  ! the routine's tendency object and the locals that outlive one call
  type(physics_ptend), allocatable, target, save :: aero_ptend(:)
  real(r8), save :: nctend_mixnuc(pcols,pver)
  real(r8), allocatable, target, save :: factnum(:,:,:)
  real(r8), pointer, save :: num_coarse(:,:) => null()
  real(r8), pointer, save :: coarse_dust(:,:) => null()
  real(r8), pointer, save :: coarse_nacl(:,:) => null()

  ! the hosts, bound from the control layer
  type(physics_state), pointer, save :: host_state(:) => null()
  type(physics_buffer_desc), pointer, save :: host_pbuf2d(:,:) => null()
  type(physics_state), pointer, save :: state => null()
  integer, save :: lchnk = 0

{codes}

contains

  logical function chunk_ok(chunk)
    integer(c_int), intent(in) :: chunk
    chunk_ok = allocated(aero_ptend) .and. chunk >= begchunk .and. chunk <= endchunk
  end function chunk_ok

  subroutine pycam_aero_bind_hosts(phys_state, pbuf2d)
    type(physics_state), pointer, intent(in) :: phys_state(:)
    type(physics_buffer_desc), pointer, intent(in) :: pbuf2d(:,:)
    host_state => phys_state
    host_pbuf2d => pbuf2d
    if (.not. allocated(aero_ptend)) allocate(aero_ptend(begchunk:endchunk))
  end subroutine pycam_aero_bind_hosts

  subroutine view2(field, ptr, ndims, extents)
    real(r8), intent(in), target :: field(:,:)
    type(c_ptr), intent(out) :: ptr
    integer(c_int), intent(out) :: ndims
    integer(c_int64_t), intent(out) :: extents(5)
    ptr = c_loc(field(1,1)); ndims = 2_c_int
    extents(1) = int(size(field, 1), c_int64_t)
    extents(2) = int(size(field, 2), c_int64_t)
  end subroutine view2

  subroutine view3(field, ptr, ndims, extents)
    real(r8), intent(in), target :: field(:,:,:)
    type(c_ptr), intent(out) :: ptr
    integer(c_int), intent(out) :: ndims
    integer(c_int64_t), intent(out) :: extents(5)
    ptr = c_loc(field(1,1,1)); ndims = 3_c_int
    extents(1) = int(size(field, 1), c_int64_t)
    extents(2) = int(size(field, 2), c_int64_t)
    extents(3) = int(size(field, 3), c_int64_t)
  end subroutine view3

  ! ------------------------------------------------------------------ !
  ! Ownership, the clock, the chunk, views
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_aero_set_owner_v1(owns) &
       bind(C, name='pycam_aero_set_owner_v1') result(res)
    integer(c_int), value, intent(in) :: owns
    python_owns_aero = owns /= 0_c_int
    res = 0_c_int
  end function pycam_aero_set_owner_v1

  integer(c_int) function pycam_aero_nstep_v1() bind(C, name='pycam_aero_nstep_v1') result(res)
    res = int(get_nstep(), c_int)
  end function pycam_aero_nstep_v1

  integer(c_int) function pycam_aero_dt_v1() bind(C, name='pycam_aero_dt_v1') result(res)
    res = int(get_step_size(), c_int)
  end function pycam_aero_dt_v1

  integer(c_int) function pycam_aero_nmodes_v1() bind(C, name='pycam_aero_nmodes_v1') result(res)
    ! microp_aero.F90:441
    integer :: nmodes
    call rad_cnst_get_info(0, nmodes=nmodes)
    res = int(nmodes, c_int)
  end function pycam_aero_nmodes_v1

  integer(c_int) function pycam_aero_begin_v1(chunk) &
       bind(C, name='pycam_aero_begin_v1') result(res)
    ! the chunk this walk is on, and the state it was given
    integer(c_int), value, intent(in) :: chunk
    res = 1_c_int
    if (.not. chunk_ok(chunk) .or. .not. associated(host_state)) return
    lchnk = chunk
    state => host_state(lchnk)
    res = 0_c_int
  end function pycam_aero_begin_v1

  integer(c_int) function pycam_aero_view_v1(chunk, code, ptr, ndims, extents) &
       bind(C, name='pycam_aero_view_v1') result(res)
    integer(c_int), value, intent(in) :: chunk, code
    type(c_ptr), intent(out) :: ptr
    integer(c_int), intent(out) :: ndims
    integer(c_int64_t), intent(out) :: extents(5)
    ptr = c_null_ptr; ndims = 0_c_int; extents = 0_c_int64_t
    res = 1_c_int
    if (.not. chunk_ok(chunk) .or. chunk /= lchnk) return
    res = 2_c_int
    select case (code)
{nl.join(cases)}
    case default
      res = 3_c_int
      return
    end select
    res = 0_c_int
  end function pycam_aero_view_v1

  ! ------------------------------------------------------------------ !
  ! The routine's calls, in its own form
  ! ------------------------------------------------------------------ !

  integer(c_int) function pycam_aero_modal_fields_v1(mode_coarse_dst_idx, &
       mode_coarse_slt_idx, coarse_dust_idx, coarse_nacl_idx) &
       bind(C, name='pycam_aero_modal_fields_v1') result(res)
    ! microp_aero.F90:473-477: the coarse mode's number and its dust and
    ! sea-salt mass, as pointers into the constituent arrays
    integer(c_int), value, intent(in) :: mode_coarse_dst_idx, mode_coarse_slt_idx
    integer(c_int), value, intent(in) :: coarse_dust_idx, coarse_nacl_idx
    type(physics_buffer_desc), pointer :: pbuf(:)
    res = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_pbuf2d)) return
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk)
    call rad_cnst_get_mode_num(0, int(mode_coarse_dst_idx), 'a', state, pbuf, num_coarse)
    call rad_cnst_get_aer_mmr(0, int(mode_coarse_dst_idx), int(coarse_dust_idx), 'a', &
         state, pbuf, coarse_dust)
    call rad_cnst_get_aer_mmr(0, int(mode_coarse_slt_idx), int(coarse_nacl_idx), 'a', &
         state, pbuf, coarse_nacl)
    res = 0_c_int
  end function pycam_aero_modal_fields_v1

  integer(c_int) function pycam_aero_save_cbaero_v1() &
       bind(C, name='pycam_aero_save_cbaero_v1') result(res)
    ! microp_aero.F90:461
    type(physics_buffer_desc), pointer :: pbuf(:)
    res = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_pbuf2d)) return
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk)
    call hetfrz_classnuc_cam_save_cbaero(state, pbuf)
    res = 0_c_int
  end function pycam_aero_save_cbaero_v1

  integer(c_int) function pycam_aero_nucleate_ice_v1(wsubi) &
       bind(C, name='pycam_aero_nucleate_ice_v1') result(res)
    ! microp_aero.F90:559
    real(c_double), intent(in) :: wsubi(pcols,pver)
    type(physics_buffer_desc), pointer :: pbuf(:)
    res = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_pbuf2d)) return
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk)
    call nucleate_ice_cam_calc(state, wsubi, pbuf)
    res = 0_c_int
  end function pycam_aero_nucleate_ice_v1

  integer(c_int) function pycam_aero_dropmixnuc_v1(deltatin, nmodes, wsub, lcldn, lcldo) &
       bind(C, name='pycam_aero_dropmixnuc_v1') result(res)
    ! microp_aero.F90:592-594.  factnum is the routine's own local, sized
    ! from the mode count (444) and read afterwards by the freezing call.
    real(c_double), value, intent(in) :: deltatin
    integer(c_int), value, intent(in) :: nmodes
    real(c_double), intent(in) :: wsub(pcols,pver), lcldn(pcols,pver), lcldo(pcols,pver)
    type(physics_buffer_desc), pointer :: pbuf(:)
    res = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_pbuf2d)) return
    if (allocated(factnum)) deallocate(factnum)
    allocate(factnum(pcols,pver,nmodes))
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk)
    call dropmixnuc(state, aero_ptend(lchnk), deltatin, pbuf, wsub, &
         lcldn, lcldo, nctend_mixnuc, factnum)
    res = 0_c_int
  end function pycam_aero_dropmixnuc_v1

  integer(c_int) function pycam_aero_hetfrz_v1(deltatin) &
       bind(C, name='pycam_aero_hetfrz_v1') result(res)
    ! microp_aero.F90:703
    real(c_double), value, intent(in) :: deltatin
    type(physics_buffer_desc), pointer :: pbuf(:)
    res = 1_c_int
    if (.not. chunk_ok(lchnk) .or. .not. associated(host_pbuf2d)) return
    if (.not. allocated(factnum)) return
    pbuf => pbuf_get_chunk(host_pbuf2d, lchnk)
    call hetfrz_classnuc_cam_calc(state, deltatin, factnum, pbuf)
    res = 0_c_int
  end function pycam_aero_hetfrz_v1

  integer(c_int) function pycam_aero_end_v1() &
       bind(C, name='pycam_aero_end_v1') result(res)
    ! what the routine's exit did for its allocatable local
    res = 1_c_int
    if (.not. chunk_ok(lchnk)) return
    if (allocated(factnum)) deallocate(factnum)
    nullify(num_coarse, coarse_dust, coarse_nacl)
    res = 0_c_int
  end function pycam_aero_end_v1

end module pycam_aero_handles
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render_module()
    if arguments.check:
        current = MODULE.read_text() if MODULE.is_file() else ""
        if current != rendered:
            sys.stderr.write("".join(difflib.unified_diff(
                current.splitlines(keepends=True), rendered.splitlines(keepends=True),
                fromfile=f"{MODULE.name} (committed)", tofile=f"{MODULE.name} (generated)"))[:3000])
            sys.stderr.write(f"\nstale: {MODULE.relative_to(REPO)}\n")
            return 1
        return 0
    MODULE.write_text(rendered)
    print(f"wrote {MODULE.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
