#!/usr/bin/env python3
"""Emit pycam_state_copy.F90: physics_state_copy's copy, into storage already allocated.

    tools/generate_pi_cam_state_copy.py            # write native/pi_cam/support/pycam_state_copy.F90
    tools/generate_pi_cam_state_copy.py --check    # fail if the committed module is stale

``physics_state_copy(state_in, state_out)`` (physics_types.F90) allocates
``state_out`` and copies the live columns into it; the drivers call it on
entry and ``physics_state_dealloc`` on exit, so the copy's storage moves
between calls.  A Python walk keeps a view of that storage per chunk and
re-resolves every kernel call site that reads it when it moves.  The module
written here holds the copy's own statements, verbatim from the pinned
source, without the allocation: the handles modules call it once the copy
exists and keep the storage from call to call.  Memory movement only; no
arithmetic.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PINNED = REPO / "external/iCESM1.3.1_fzhu/components/cam/src/physics/cam/physics_types.F90"
MODULE = REPO / "native/pi_cam/support/pycam_state_copy.F90"

#: the routine hoisted, and the one statement left out of it
ROUTINE = "physics_state_copy"
ALLOCATION = "call physics_state_alloc"


def routine_lines(source: Path = PINNED) -> tuple[int, list[str]]:
    """The body of physics_state_copy as the pinned source has it: (first line number, lines)."""

    lines = source.read_text().splitlines()
    first = next(i for i, line in enumerate(lines) if line.strip().startswith(f"subroutine {ROUTINE}("))
    last = next(i for i in range(first, len(lines)) if lines[i].strip().startswith(f"end subroutine {ROUTINE}"))
    return first + 1, lines[first:last + 1]


def render(source: Path = PINNED) -> str:
    first, lines = routine_lines(source)
    body = lines[1:-1]                                   # inside subroutine ... end subroutine
    kept: list[str] = []
    dropped = 0
    for line in body:
        stripped = line.strip()
        if stripped.startswith(("use ", "implicit none", "type(physics_state)")):
            continue                                     # the module's own header carries these
        if stripped.startswith(ALLOCATION):
            dropped += 1
            continue
        if stripped.startswith("!") and "Allocate" in stripped:
            continue                                     # the comment on the statement left out
        if not stripped and (not kept or not kept[-1].strip()):
            continue                                     # one blank line at most
        kept.append(line.rstrip())
    if dropped != 1:
        raise SystemExit(f"expected one {ALLOCATION!r} statement in {ROUTINE}, found {dropped}")
    last = first + len(lines) - 1
    header = f"""! Generated by tools/generate_pi_cam_state_copy.py -- do not edit.
!
! physics_state_copy without its allocation: physics_types.F90:{first}-{last}
! of the pinned source, statement for statement, less the one call that
! allocates state_out.  A handles module calls this when the driver's local
! copy of the state already exists from an earlier call, so the copy's
! storage stays where a Python walk's views of it point.  Memory movement
! only: every statement is an assignment of the live columns.
module pycam_state_copy
  use shr_kind_mod, only: r8 => shr_kind_r8
  use physics_types, only: physics_state
  implicit none
  private
  public :: pycam_state_copy_into

contains

  subroutine pycam_state_copy_into(state_in, state_out)
    use ppgrid,       only: pver, pverp
    use constituents, only: pcnst
    type(physics_state), intent(in)    :: state_in
    type(physics_state), intent(inout) :: state_out
"""
    return header + "\n".join(kept) + "\n  end subroutine pycam_state_copy_into\n\nend module pycam_state_copy\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = MODULE.read_text() if MODULE.exists() else ""
        if current != text:
            sys.stdout.writelines(difflib.unified_diff(
                current.splitlines(True), text.splitlines(True), str(MODULE), "generated"))
            return 1
        print(f"{MODULE.relative_to(REPO)} is current")
        return 0
    MODULE.write_text(text)
    print(f"wrote {MODULE.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
